"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const { localSeoCoverageForSite, auditLocalSeoCoverage } = require("../src/modules/minisite-structured-data/local-seo-coverage");
function site({ title = "Agence de voyages", meta = "Conseils voyages", body = "Nos experts vous accompagnent.", heading = "Votre agence de voyages", city = "Gien", completeNap = true, extraPages = [] } = {}) { return { slug: "gien", agency: { name: "Mondescale Gien", city, address: completeNap ? "12 rue de Paris" : null, postalCode: completeNap ? "45500" : null, phone: completeNap ? "02 38 00 00 00" : null }, pages: [{ slug: "accueil", title: "Accueil", seoTitle: title, metaDescription: meta, status: "published", published: true, blocks: [{ status: "published", content: { heading, text: body } }] }, ...extraPages] }; }
function publishedPage(slug, content = {}) { return { slug, title: slug, seoTitle: slug, metaDescription: slug, status: "published", published: true, blocks: [{ status: "published", content }] }; }
test("MSE-25.24 detects a missing primary locality in title, meta, H1 and content", () => { const audit = localSeoCoverageForSite(site()); assert.equal(audit.primaryCity, "Gien"); assert.ok(audit.gaps.some((gap) => gap.code === "homepage-title-locality-missing")); assert.ok(audit.gaps.some((gap) => gap.code === "homepage-meta-locality-missing")); assert.ok(audit.gaps.some((gap) => gap.code === "homepage-h1-locality-missing")); assert.ok(audit.gaps.some((gap) => gap.code === "homepage-content-locality-missing")); assert.equal(audit.status, "weak"); });
test("MSE-25.26 requires semantic depth beyond merely repeating the city", () => { const audit = localSeoCoverageForSite(site({ title: "Agence de voyages à Gien", meta: "Votre agence à Gien", heading: "Agence de voyages à Gien", body: "Notre agence de voyages à Gien vous accueille à Gien pour préparer votre voyage à Gien." })); assert.equal(audit.semanticDepth.status, "shallow"); assert.ok(audit.gaps.some((gap) => gap.code === "local-semantic-services-missing")); assert.ok(audit.gaps.some((gap) => gap.code === "local-semantic-proof-missing")); assert.notEqual(audit.status, "strong"); });
test("MSE-25.26 recognizes service expertise proof and geographic context", () => { const body = "Notre équipe de conseillères vous accompagne depuis plusieurs années dans notre agence physique de Gien. Nous préparons circuits, séjours, croisières, vols et voyages sur mesure. Nos clients de Gien, Briare et des communes voisines bénéficient de conseils personnalisés et peuvent prendre rendez-vous sur place. Partenaires de nombreux tour-opérateurs, nos spécialistes connaissent les départs, hôtels et clubs adaptés à chaque projet. Cette présence locale et notre expérience permettent un accompagnement avant, pendant et après le voyage. Retrouvez également les avis de nos clients et échangez directement avec notre équipe pour construire un séjour adapté à votre budget et à vos envies."; const audit = localSeoCoverageForSite(site({ title: "Agence de voyages à Gien | Mondescale", meta: "Votre agence de voyages à Gien pour circuits, séjours et conseils sur mesure.", heading: "Votre agence de voyages à Gien", body }), { targetCities: ["Briare"] }); assert.equal(audit.semanticDepth.status, "deep"); assert.equal(audit.semanticDepth.depthScore, 100); assert.equal(audit.semanticDepth.dimensions.services, true); assert.equal(audit.semanticDepth.dimensions.expertise, true); assert.equal(audit.semanticDepth.dimensions.proof, true); assert.equal(audit.semanticDepth.dimensions.localContext, true); assert.equal(audit.gaps.filter((gap) => gap.code.startsWith("local-semantic-")).length, 0); });
test("MSE-25.24 flags incomplete NAP before local indexation quality is considered strong", () => { const audit = localSeoCoverageForSite(site({ title: "Agence de voyages à Gien", meta: "Votre agence à Gien", heading: "Agence de voyages à Gien", body: "Conseillers voyages à Gien.", completeNap: false })); assert.equal(audit.nap.complete, false); assert.ok(audit.gaps.some((gap) => gap.code === "nap-incomplete")); assert.ok(audit.gaps.some((gap) => gap.code === "local-schema-nap-incomplete")); assert.notEqual(audit.status, "strong"); });
test("MSE-25.24 reports uncovered secondary target cities without creating doorway pages", () => { const result = auditLocalSeoCoverage([site({ title: "Agence de voyages à Gien", meta: "Votre agence à Gien", heading: "Agence de voyages à Gien", body: "Conseillers voyages à Gien." })], { gien: { targetCities: ["Montargis", "Briare"] } }); assert.deepEqual(result.sites[0].missingCities, ["Montargis", "Briare"]); assert.equal(result.sites[0].gaps.filter((gap) => gap.code === "target-city-uncovered").length, 2); });
test("MSE-25.24 detects published orphan pages and missing homepage internal links", () => { const audit = localSeoCoverageForSite(site({ title: "Agence de voyages à Gien", meta: "Votre agence à Gien", heading: "Agence de voyages à Gien", body: "Conseillers voyages à Gien.", extraPages: [publishedPage("circuits", { heading: "Circuits à Gien", text: "Nos circuits au départ de Gien." })] })); assert.equal(audit.linking.hasOrphans, true); assert.deepEqual(audit.linking.orphanPaths, ["/agence/gien/circuits"]); assert.ok(audit.gaps.some((gap) => gap.code === "internal-link-orphans")); assert.ok(audit.gaps.some((gap) => gap.code === "homepage-internal-links-missing")); });
test("MSE-25.24 accepts explicit internal links from the homepage to published content", () => { const linkedSite = site({ title: "Agence de voyages à Gien", meta: "Votre agence à Gien", heading: "Agence de voyages à Gien", body: "Conseillers voyages à Gien.", extraPages: [publishedPage("circuits", { heading: "Circuits à Gien", text: "Nos circuits au départ de Gien." })] }); linkedSite.pages[0].blocks[0].content.ctaUrl = "/agence/gien/circuits"; const linkedAudit = localSeoCoverageForSite(linkedSite); assert.equal(linkedAudit.pages[0].internalLinkCount, 1); assert.equal(linkedAudit.linking.hasOrphans, false); });
