"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");const {run,deriveCurrentVersion}=require("../scripts/mse-25-59-version-check");
function source(){return{type:"MSE_25_58_VERSIONED_WRITE_INTENT_REPORT",certified:true,readOnly:true,writes:false,publicWrites:false,intent:{type:"MSE_25_58_VERSIONED_WRITE_INTENT",humanApproved:true,intentOnly:true,versionBound:true,requiresFreshVersionCheck:true,requiresSeparateExecutionAuthorization:true,executable:false,automaticWrite:false,writes:false,publicWrites:false,websiteDesignerMutationAllowed:false,baseVersion:"42",intentFingerprint:"intent-fp",sourceApprovalFingerprint:"approval-fp",sourceDiffFingerprint:"diff-fp",sourceObservationFingerprint:"obs-fp",siteSlug:"gien",page:"/services",pageIdentity:"page-1"}}}
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-59-"));const sourcePath=path.join(dir,"source.json");fs.writeFileSync(sourcePath,JSON.stringify(source()));return{dir,sourcePath}}
function prisma(page){let calls=0;return{agencySitePage:{findFirst:async(q)=>{calls++;assert.equal(q.where.id,"page-1");assert.equal(q.where.path,"/services");assert.equal(q.where.site.is.slug,"gien");return page}},get calls(){return calls}}}
test("runner reads actual Website Designer version and seals non executable matching gate",async()=>{const f=fixture();const db=prisma({id:"page-1",path:"/services",version:42,site:{slug:"gien"}});const r=await run({prisma:db,sourceReportPath:f.sourcePath,reportDir:f.dir,emitOutput:false});assert.equal(db.calls,1);assert.equal(r.certified,true);assert.equal(r.gate.versionFresh,true);assert.equal(r.gate.executionAuthorized,false);assert.equal(r.summary.executableCount,0);assert.equal(r.summary.websiteDesignerMutationCount,0);assert.equal(fs.existsSync(r.reportPath),true)});
test("runner detects stale approved base and returns to editorial review",async()=>{const f=fixture();const r=await run({prisma:prisma({id:"page-1",path:"/services",version:43,site:{slug:"gien"}}),sourceReportPath:f.sourcePath,reportDir:f.dir,emitOutput:false});assert.equal(r.gate.versionFresh,false);assert.equal(r.gate.state,"STALE_WRITE_INTENT_REVIEW_REQUIRED");assert.equal(r.gate.nextStep,"RETURN_TO_EDITORIAL_REVIEW");assert.equal(r.summary.executableCount,0)});
test("runner never invents Website Designer version",async()=>{const f=fixture();await assert.rejects(()=>run({prisma:prisma({id:"page-1",path:"/services",site:{slug:"gien"}}),sourceReportPath:f.sourcePath,reportDir:f.dir,emitOutput:false}),/WEBSITE_DESIGNER_VERSION_REQUIRED/)});
test("deriveCurrentVersion accepts persisted revision and updatedAt fallback",()=>{assert.equal(deriveCurrentVersion({id:"p",revision:7}),"7");assert.equal(deriveCurrentVersion({id:"p",updatedAt:new Date("2026-08-26T07:00:00.000Z")}),"2026-08-26T07:00:00.000Z")});
