"use strict";
const test=require("node:test");const assert=require("node:assert/strict");
const {buildPreApplyGate,certifyGate}=require("../src/modules/minisite-semantic-engine/pre-apply-version-rollback-gate");
function source(overrides={}){return{type:"MSE_25_62_FINAL_APPLY_CONFIRMATION_REPORT",certified:true,readOnly:true,writes:false,publicWrites:false,confirmation:{type:"MSE_25_62_FINAL_APPLY_CONFIRMATION",decision:"CONFIRM_FINAL_APPLY",humanDecision:true,finalApplyConfirmed:true,nextStep:"PRE_APPLY_FRESH_VERSION_RECHECK",requiresFreshVersionRecheckBeforeApply:true,requiresRollbackPreparation:true,executionAuthorized:false,executable:false,writes:false,publicWrites:false,websiteDesignerMutationAllowed:false,confirmationFingerprint:"confirm-fp",sourceExecutionPlanFingerprint:"plan-fp",sourceIntentFingerprint:"intent-fp",siteSlug:"gien",page:"/services",pageIdentity:"page-1",baseVersion:"42",...overrides}}}
function rollback(overrides={}){return{ready:true,snapshotFingerprint:"snapshot-fp",restoreTargetVersion:"42",...overrides}}
test("fresh version identical page and persisted rollback pass safety gate without authorizing apply",()=>{const g=buildPreApplyGate({sourceReport:source(),currentVersion:"42",currentPageIdentity:"page-1",rollbackMaterial:rollback()});assert.equal(g.gatePassed,true);assert.equal(g.versionFresh,true);assert.equal(g.identityFresh,true);assert.equal(g.rollbackReady,true);assert.equal(g.applyAuthorized,false);assert.equal(g.executable,false);assert.equal(g.websiteDesignerMutationAllowed,false);assert.equal(certifyGate(g).certified,true)});
test("version drift blocks pre-apply",()=>{const g=buildPreApplyGate({sourceReport:source(),currentVersion:"43",currentPageIdentity:"page-1",rollbackMaterial:rollback()});assert.equal(g.gatePassed,false);assert.equal(g.reason,"VERSION_CHANGED_SINCE_APPROVAL");assert.equal(g.applyAuthorized,false)});
test("page identity drift blocks pre-apply",()=>{const g=buildPreApplyGate({sourceReport:source(),currentVersion:"42",currentPageIdentity:"page-2",rollbackMaterial:rollback()});assert.equal(g.gatePassed,false);assert.equal(g.reason,"PAGE_IDENTITY_CHANGED")});
test("missing rollback material blocks pre-apply",()=>{const g=buildPreApplyGate({sourceReport:source(),currentVersion:"42",currentPageIdentity:"page-1",rollbackMaterial:{ready:false}});assert.equal(g.gatePassed,false);assert.equal(g.reason,"ROLLBACK_MATERIAL_NOT_READY")});
test("rejected final confirmation cannot enter pre-apply gate",()=>{assert.throws(()=>buildPreApplyGate({sourceReport:source({decision:"REJECT_FINAL_APPLY",finalApplyConfirmed:false,nextStep:"STOP_NO_APPLY"}),currentVersion:"42",currentPageIdentity:"page-1",rollbackMaterial:rollback()}),/SOURCE_CERTIFICATION_FAILED/)});
