"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");const {run,buildRollbackMaterial}=require("../scripts/mse-25-63-pre-apply-gate");
function source(){return{type:"MSE_25_62_FINAL_APPLY_CONFIRMATION_REPORT",certified:true,readOnly:true,writes:false,publicWrites:false,confirmation:{type:"MSE_25_62_FINAL_APPLY_CONFIRMATION",decision:"CONFIRM_FINAL_APPLY",humanDecision:true,finalApplyConfirmed:true,nextStep:"PRE_APPLY_FRESH_VERSION_RECHECK",requiresFreshVersionRecheckBeforeApply:true,requiresRollbackPreparation:true,executionAuthorized:false,executable:false,writes:false,publicWrites:false,websiteDesignerMutationAllowed:false,confirmationFingerprint:"confirm-fp",sourceExecutionPlanFingerprint:"plan-fp",sourceIntentFingerprint:"intent-fp",siteSlug:"gien",page:"/services",pageIdentity:"page-1",baseVersion:"42"}}}
function fixture(){const d=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-63-"));const f=path.join(d,"source.json");fs.writeFileSync(f,JSON.stringify(source()));return{d,f}}
function prisma(page){let writes=0;return{get writes(){return writes},agencySitePage:{findFirst:async q=>{assert.equal(q.where.id,"page-1");assert.equal(q.where.path,"/services");assert.equal(q.where.site.is.slug,"gien");return page},update:async()=>{writes++;throw new Error("WRITE_FORBIDDEN")}}}}
test("runner reads latest persisted page version and prepares rollback without database writes",async()=>{const {d,f}=fixture();const db=prisma({id:"page-1",path:"/services",site:{slug:"gien"},versions:[{id:"v42",version:42,snapshot:{title:"before"},createdAt:new Date("2026-08-26T08:00:00.000Z")}]});const r=await run({prisma:db,sourceReportPath:f,reportDir:d,emitOutput:false});assert.equal(r.certified,true);assert.equal(r.gate.gatePassed,true);assert.equal(r.rollbackMaterial.ready,true);assert.equal(r.rollbackMaterial.restoreTargetVersion,"42");assert.equal(r.summary.websiteDesignerMutationCount,0);assert.equal(db.writes,0);assert.equal(fs.statSync(r.reportPath).mode&0o777,0o600)});
test("runner blocks when latest Website Designer version drifted",async()=>{const {d,f}=fixture();const r=await run({prisma:prisma({id:"page-1",path:"/services",site:{slug:"gien"},versions:[{id:"v43",version:43,snapshot:{title:"changed"},createdAt:new Date()}]}),sourceReportPath:f,reportDir:d,emitOutput:false});assert.equal(r.gate.gatePassed,false);assert.equal(r.gate.reason,"VERSION_CHANGED_SINCE_APPROVAL");assert.equal(r.gate.applyAuthorized,false)});
test("runner fails closed without persisted rollback version",async()=>{const {d,f}=fixture();await assert.rejects(()=>run({prisma:prisma({id:"page-1",path:"/services",site:{slug:"gien"},versions:[]}),sourceReportPath:f,reportDir:d,emitOutput:false}),/WEBSITE_DESIGNER_VERSION_NOT_FOUND/)});
test("rollback fingerprint binds persisted snapshot and version",()=>{const a=buildRollbackMaterial({id:"page-1"},{id:"v1",version:1,snapshot:{a:1},createdAt:"x"});const b=buildRollbackMaterial({id:"page-1"},{id:"v1",version:1,snapshot:{a:2},createdAt:"x"});assert.notEqual(a.snapshotFingerprint,b.snapshotFingerprint)});
