"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");const {run,lifecycleAction}=require("../scripts/mse-25-operational-status");
function obs(overrides={}){return async()=>({certified:true,readOnly:true,writes:false,publicWrites:false,automaticWriteCount:0,dataState:"NO_DATA_YET",lifecycleState:"WAITING_FOR_SEARCH_DEMAND_DATA",reviewItemCount:0,prioritizedReviewItemCount:0,packetCount:0,highPriorityPacketCount:0,mediumPriorityPacketCount:0,lowPriorityPacketCount:0,reportPath:"/tmp/source.json",...overrides})}
function absentStages(){return ["humanDecision","editorialMandate","editorialDiff","diffApproval","writeIntent","versionGate","executionAuthorization","executionPlan","finalApplyConfirmation","preApplyGate","guardedApply","postApplyVerification","rollbackIntent","rollbackAuthorization","guardedRollback","postRollbackVerification"].map(key=>({key,state:"ABSENT",writes:null,publicWrites:null}))}
async function withEnv(fn){const saved={DATABASE_URL:process.env.DATABASE_URL,MSE_25_48_ENV_FILE:process.env.MSE_25_48_ENV_FILE,MSE_25_48_HOST_DATABASE_URL:process.env.MSE_25_48_HOST_DATABASE_URL,MSE_25_OPERATIONAL_REPORT_DIR:process.env.MSE_25_OPERATIONAL_REPORT_DIR};const reportDir=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-op-test-"));process.env.DATABASE_URL="postgresql://test:test@127.0.0.1:5432/test";process.env.MSE_25_OPERATIONAL_REPORT_DIR=reportDir;try{return await fn()}finally{for(const [k,v] of Object.entries(saved))v===undefined?delete process.env[k]:process.env[k]=v;fs.rmSync(reportDir,{recursive:true,force:true})}}
test("no Search Console data produces one operational waiting verdict",async()=>withEnv(async()=>{const r=await run({emitOutput:false,observeReviewQueue:obs(),observePriority:obs(),observePackets:obs(),stageScanner:absentStages});assert.equal(r.nextAction,"WAIT_FOR_SEARCH_CONSOLE_DATA");assert.equal(r.humanGate.required,false);assert.equal(r.safety.automaticWriteCount,0);assert.equal(r.downstream.summary.presentCount,0);assert.equal(r.runtimeEnv.databaseConfigured,true)}));
test("decision packets stop at human review",async()=>withEnv(async()=>{const r=await run({emitOutput:false,observeReviewQueue:obs({dataState:"DATA_AVAILABLE",reviewItemCount:1}),observePriority:obs({dataState:"DATA_AVAILABLE",prioritizedReviewItemCount:1}),observePackets:obs({dataState:"DATA_AVAILABLE",packetCount:1,highPriorityPacketCount:1}),stageScanner:absentStages});assert.equal(r.nextAction,"HUMAN_REVIEW_REQUIRED");assert.equal(r.humanGate.required,true);assert.equal(r.humanGate.automaticDecision,false)}));
test("operational runner loads DATABASE_URL from explicit backend env before observations",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-op-env-"));const reportDir=path.join(root,"reports");const envFile=path.join(root,"backend.env");fs.writeFileSync(envFile,"DATABASE_URL=postgresql://runtime:secret@db-runtime.internal:5432/mondescale\n");const saved={DATABASE_URL:process.env.DATABASE_URL,MSE_25_48_ENV_FILE:process.env.MSE_25_48_ENV_FILE,MSE_25_OPERATIONAL_REPORT_DIR:process.env.MSE_25_OPERATIONAL_REPORT_DIR};delete process.env.DATABASE_URL;process.env.MSE_25_48_ENV_FILE=envFile;process.env.MSE_25_OPERATIONAL_REPORT_DIR=reportDir;try{const r=await run({emitOutput:false,observeReviewQueue:obs(),observePriority:obs(),observePackets:obs(),stageScanner:absentStages});assert.equal(r.runtimeEnv.databaseConfigured,true);assert.equal(r.runtimeEnv.databaseHost,"db-runtime.internal");assert.ok(r.runtimeEnv.loadedFiles.includes(path.resolve(envFile)))}finally{for(const [k,v] of Object.entries(saved))v===undefined?delete process.env[k]:process.env[k]=v;fs.rmSync(root,{recursive:true,force:true})}});
test("existing editorial diff reports the exact next human gate",()=>{const stages=absentStages();stages.find(s=>s.key==="editorialDiff").state="PRESENT";const summary={unsafeCount:0};assert.equal(lifecycleAction({dataState:"DATA_AVAILABLE",reviewItemCount:1,packetCount:1,stages,stageSummary:summary}),"HUMAN_DIFF_APPROVAL_REQUIRED")});
test("unsafe read-only observation fails closed",async()=>withEnv(async()=>{await assert.rejects(()=>run({emitOutput:false,observeReviewQueue:obs({writes:true}),observePriority:obs(),observePackets:obs(),stageScanner:absentStages}),/UNSAFE_REVIEW_OBSERVATION/)}));
