"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");
const {run}=require("../scripts/mse-25-57-readiness");
function env(values){const before={};for(const[k,v]of Object.entries(values)){before[k]=process.env[k];if(v===null)delete process.env[k];else process.env[k]=v}return()=>{for(const[k,v]of Object.entries(before))v===undefined?delete process.env[k]:process.env[k]=v}}
function diff(dir,overrides={}){const file=path.join(dir,"mse-25-56-observation-test.json");fs.writeFileSync(file,JSON.stringify({type:"MSE_25_56_EDITORIAL_DIFF_OBSERVATION",certified:true,readOnly:true,writes:false,publicWrites:false,observationFingerprint:"obs-fp",summary:{executableCount:0,automaticWriteCount:0,pageCreationCount:0,publicationCount:0,websiteDesignerMutationCount:0},preview:{siteSlug:"gien",page:"/services",pageIdentity:"page-1",diffFingerprint:"diff-fp",policy:{previewOnly:true,humanReviewRequired:true,humanApprovalRequiredBeforeMutation:true}},...overrides}));return file}

test("no MSE-25.56 diff remains waiting and does not synthesize approval",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-57-"));const restore=env({MSE_25_56_REPORT_DIR:dir,MSE_25_57_SOURCE_REPORT:null});try{const r=await run({emitOutput:false});assert.equal(r.ready,false);assert.equal(r.state,"WAITING_FOR_EDITORIAL_DIFF");assert.equal(r.sourceDiffReportPath,null);assert.equal(r.executableCount,0);assert.equal(r.automaticWriteCount,0);assert.equal(r.policy.noSyntheticApproval,true);assert.equal(r.policy.automaticApproval,false)}finally{restore()}});
test("certified MSE-25.56 diff becomes ready for human review only",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-57-"));const file=diff(dir);const restore=env({MSE_25_56_REPORT_DIR:dir,MSE_25_57_SOURCE_REPORT:file});try{const r=await run({emitOutput:false});assert.equal(r.ready,true);assert.equal(r.state,"READY_FOR_HUMAN_EDITORIAL_DIFF_REVIEW");assert.equal(r.sourceDiffReportPath,file);assert.equal(r.writes,false);assert.equal(r.publicWrites,false);assert.equal(r.policy.humanDecisionRequired,true);assert.equal(r.policy.websiteDesignerMutation,false)}finally{restore()}});
test("unsafe MSE-25.56 diff fails readiness closed",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-57-"));const file=diff(dir,{writes:true});const restore=env({MSE_25_57_SOURCE_REPORT:file});try{await assert.rejects(()=>run({emitOutput:false}),/UNSAFE_SOURCE_DIFF/)}finally{restore()}});
