"use strict";
const test=require("node:test");const assert=require("node:assert/strict");
const {buildApplyManifest}=require("../src/modules/minisite-semantic-engine/guarded-website-designer-apply");
function gate(overrides={}){return{type:"MSE_25_63_PRE_APPLY_VERSION_ROLLBACK_GATE_REPORT",certified:true,readOnly:true,writes:false,publicWrites:false,rollbackMaterial:{ready:true,snapshotFingerprint:"rollback-fp"},gate:{type:"MSE_25_63_PRE_APPLY_VERSION_ROLLBACK_GATE",gatePassed:true,versionFresh:true,identityFresh:true,rollbackReady:true,applyAuthorized:false,executable:false,writes:false,publicWrites:false,websiteDesignerMutationAllowed:false,sourceConfirmationFingerprint:"confirm-fp",sourceExecutionPlanFingerprint:"plan-fp",sourceIntentFingerprint:"intent-fp",gateFingerprint:"gate-fp",rollbackSnapshotFingerprint:"rollback-fp",siteSlug:"gien",page:"/services",expectedPageIdentity:"page-1",currentVersion:"42",...overrides}}}
function diff(overrides={}){return{type:"MSE_25_56_EDITORIAL_DIFF_OBSERVATION",certified:true,writes:false,publicWrites:false,preview:{type:"MSE_25_56_EDITORIAL_DIFF_PREVIEW",siteSlug:"gien",page:"/services",pageIdentity:"page-1",diffFingerprint:"diff-fp",changedFields:["title","introduction"],before:{title:"Avant",introduction:"Intro avant"},after:{title:"Après",introduction:"Intro après"},policy:{humanReviewRequired:true,humanApprovalRequiredBeforeMutation:true,executable:false,writes:false,publicWrites:false},...overrides}}}
test("passed gate plus approved diff and explicit token produce one guarded manifest",()=>{const m=buildApplyManifest({gateReport:gate(),diffReport:diff(),explicitApplyToken:"APPLY_APPROVED_DIFF"});assert.equal(m.guardedMutationAllowed,true);assert.equal(m.transactionRequired,true);assert.equal(m.recheckVersionInsideTransaction,true);assert.equal(m.rollbackMaterialRequired,true);assert.deepEqual(m.changedFields,["title","introduction"]);assert.equal(m.pageCreationAllowed,false);assert.equal(m.publicationAllowed,false)});
test("missing explicit token blocks apply manifest",()=>{assert.throws(()=>buildApplyManifest({gateReport:gate(),diffReport:diff(),explicitApplyToken:""}),/EXPLICIT_APPLY_TOKEN_REQUIRED/)});
test("stale or rollback-less pre-apply gate blocks apply manifest",()=>{assert.throws(()=>buildApplyManifest({gateReport:gate({versionFresh:false,gatePassed:false}),diffReport:diff(),explicitApplyToken:"APPLY_APPROVED_DIFF"}),/GATE_CERTIFICATION_FAILED/);assert.throws(()=>buildApplyManifest({gateReport:gate({rollbackReady:false,gatePassed:false}),diffReport:diff(),explicitApplyToken:"APPLY_APPROVED_DIFF"}),/GATE_CERTIFICATION_FAILED/)});
test("target mismatch and unsupported changed field fail closed",()=>{assert.throws(()=>buildApplyManifest({gateReport:gate(),diffReport:diff({pageIdentity:"other"}),explicitApplyToken:"APPLY_APPROVED_DIFF"}),/DIFF_CERTIFICATION_FAILED/);assert.throws(()=>buildApplyManifest({gateReport:gate(),diffReport:diff({changedFields:["seoTitle"]}),explicitApplyToken:"APPLY_APPROVED_DIFF"}),/UNSUPPORTED_CHANGED_FIELD/)});
