"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const {buildRollbackExecutionManifest,certifyAuthorizationReport}=require("../src/modules/minisite-semantic-engine/guarded-transactional-rollback");
function authReport(overrides={}){return{type:"MSE_25_66_HUMAN_ROLLBACK_AUTHORIZATION_REPORT",certified:true,readOnly:true,writes:false,publicWrites:false,authorization:{type:"MSE_25_66_HUMAN_ROLLBACK_AUTHORIZATION",humanDecision:true,decision:"AUTHORIZE_ROLLBACK",reviewer:"seo-director",rationale:"Restore approved persisted snapshot.",sourceRollbackIntentFingerprint:"ri-fp",sourceVerificationFingerprint:"verify-fp",sourceApplyAuditFingerprint:"apply-fp",rollbackSnapshotFingerprint:"rollback-fp",siteSlug:"gien",page:"/services",pageIdentity:"page-1",failedVersion:43,restoreVersion:42,rollbackAuthorized:true,nextStep:"PREPARE_GUARDED_ROLLBACK",explicitRollbackTokenRequired:true,requiresCurrentFailedVersionRecheck:true,requiresRollbackSnapshotRecheck:true,executable:false,automaticWrite:false,writes:false,publicWrites:false,websiteDesignerMutationAllowed:false,authorizationFingerprint:"auth-fp",...overrides}}}
function intentReport(overrides={}){return{type:"MSE_25_65_ROLLBACK_INTENT_REPORT",intent:{type:"MSE_25_65_ROLLBACK_INTENT",rollbackIntentFingerprint:"ri-fp",sourceApplyAuditFingerprint:"apply-fp",rollbackSnapshotFingerprint:"rollback-fp",siteSlug:"gien",page:"/services",pageIdentity:"page-1",failedVersion:43,restoreVersion:42,...overrides}}}
function applyReport(overrides={}){return{audit:{auditFingerprint:"apply-fp",pageIdentity:"page-1",newVersion:43,previousVersion:42,...overrides.audit},manifest:{rollbackSnapshotFingerprint:"rollback-fp",...overrides.manifest}}}
test("authorized rollback becomes explicit transactional manifest only with token",()=>{const m=buildRollbackExecutionManifest({authorizationReport:authReport(),rollbackIntentReport:intentReport(),applyReport:applyReport(),explicitRollbackToken:"ROLLBACK_APPROVED_VERSION"});assert.equal(m.rollbackAuthorized,true);assert.equal(m.transactionRequired,true);assert.equal(m.currentFailedVersionRecheckRequired,true);assert.equal(m.rollbackSnapshotRecheckRequired,true);assert.equal(m.automaticWrite,false);assert.equal(m.pageCreationAllowed,false);assert.equal(m.publicationAllowed,false)});
test("rollback token is mandatory",()=>{assert.throws(()=>buildRollbackExecutionManifest({authorizationReport:authReport(),rollbackIntentReport:intentReport(),applyReport:applyReport(),explicitRollbackToken:""}),/EXPLICIT_ROLLBACK_TOKEN_REQUIRED/)});
test("denied human rollback cannot produce manifest",()=>{const r=authReport({decision:"DENY_ROLLBACK",rollbackAuthorized:false,nextStep:"STOP_NO_ROLLBACK"});assert.equal(certifyAuthorizationReport(r).certified,false);assert.throws(()=>buildRollbackExecutionManifest({authorizationReport:r,rollbackIntentReport:intentReport(),applyReport:applyReport(),explicitRollbackToken:"ROLLBACK_APPROVED_VERSION"}),/AUTHORIZATION_FAILED/)});
test("provenance mismatch fails closed",()=>{assert.throws(()=>buildRollbackExecutionManifest({authorizationReport:authReport(),rollbackIntentReport:intentReport({rollbackIntentFingerprint:"other"}),applyReport:applyReport(),explicitRollbackToken:"ROLLBACK_APPROVED_VERSION"}),/PROVENANCE_MISMATCH/)});
