"use strict";
const test=require("node:test");const assert=require("node:assert/strict");
const {buildHumanEditorialDiffApproval,certifyHumanEditorialDiffApproval}=require("../src/modules/minisite-semantic-engine/human-editorial-diff-approval");
function source(overrides={}){return{type:"MSE_25_56_EDITORIAL_DIFF_OBSERVATION",certified:true,readOnly:true,writes:false,publicWrites:false,observationFingerprint:"obs-fp",summary:{executableCount:0,automaticWriteCount:0,pageCreationCount:0,publicationCount:0,websiteDesignerMutationCount:0},preview:{siteSlug:"gien",page:"/services",pageIdentity:"page-1",changedFields:["introduction"],diffFingerprint:"diff-fp",policy:{previewOnly:true,humanReviewRequired:true,humanApprovalRequiredBeforeMutation:true}},...overrides}}

test("APPROVE_DIFF remains non executable and only authorizes write-intent preparation",()=>{const a=buildHumanEditorialDiffApproval({diffReport:source(),decision:"APPROVE_DIFF",reviewer:"seo-director",rationale:"The proposed refinement is accurate and preserves the page.",decidedAt:"2026-08-26T09:00:00.000Z"});assert.equal(a.nextStep,"PREPARE_NON_EXECUTABLE_VERSIONED_WRITE_INTENT");assert.equal(a.executable,false);assert.equal(a.websiteDesignerMutationAllowed,false);assert.equal(a.sourceObservationFingerprint,"obs-fp");assert.equal(certifyHumanEditorialDiffApproval(a).certified,true)});
test("REJECT_DIFF creates no change request",()=>{const a=buildHumanEditorialDiffApproval({diffReport:source(),decision:"REJECT_DIFF",reviewer:"seo-director",rationale:"The current version should remain unchanged."});assert.equal(a.nextStep,"NO_CHANGE_REQUESTED")});
test("REQUEST_CHANGES returns to preview without writes",()=>{const a=buildHumanEditorialDiffApproval({diffReport:source(),decision:"REQUEST_CHANGES",reviewer:"seo-director",rationale:"The wording needs another editorial pass."});assert.equal(a.nextStep,"RETURN_TO_EDITORIAL_DIFF_PREVIEW");assert.equal(a.writes,false)});
test("unsafe source and invalid decision fail closed",()=>{assert.throws(()=>buildHumanEditorialDiffApproval({diffReport:source({writes:true}),decision:"APPROVE_DIFF",reviewer:"seo",rationale:"Enough rationale here."}),/SOURCE_CERTIFICATION_FAILED/);assert.throws(()=>buildHumanEditorialDiffApproval({diffReport:source(),decision:"PUBLISH",reviewer:"seo",rationale:"Enough rationale here."}),/INVALID_DECISION/)});
test("missing observation provenance fails closed",()=>{assert.throws(()=>buildHumanEditorialDiffApproval({diffReport:source({observationFingerprint:null}),decision:"APPROVE_DIFF",reviewer:"seo",rationale:"Enough rationale here."}),/SOURCE_CERTIFICATION_FAILED/)});
test("source mutation counters fail closed",()=>{assert.throws(()=>buildHumanEditorialDiffApproval({diffReport:source({summary:{executableCount:0,automaticWriteCount:0,pageCreationCount:0,publicationCount:0,websiteDesignerMutationCount:1}}),decision:"APPROVE_DIFF",reviewer:"seo",rationale:"Enough rationale here."}),/SOURCE_CERTIFICATION_FAILED/)});
test("tampered executable approval fails certification",()=>{const a=buildHumanEditorialDiffApproval({diffReport:source(),decision:"APPROVE_DIFF",reviewer:"seo",rationale:"The proposed change is acceptable."});a.executable=true;a.websiteDesignerMutationAllowed=true;const c=certifyHumanEditorialDiffApproval(a);assert.equal(c.certified,false);assert.ok(c.reasons.includes("WRITE_OR_EXECUTION_FORBIDDEN"));assert.ok(c.reasons.includes("PUBLIC_MUTATION_FORBIDDEN"))});
