"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");
const {run}=require("../scripts/mse-25-57-human-approval");
function source(dir,overrides={}){const f=path.join(dir,"diff.json");fs.writeFileSync(f,JSON.stringify({type:"MSE_25_56_EDITORIAL_DIFF_OBSERVATION",certified:true,readOnly:true,writes:false,publicWrites:false,observationFingerprint:"obs-fp",summary:{executableCount:0,automaticWriteCount:0},preview:{siteSlug:"gien",page:"/services",pageIdentity:"page-1",changedFields:["introduction"],diffFingerprint:"diff-fp",policy:{previewOnly:true,humanReviewRequired:true}},...overrides}));return f}
function setEnv(values){const before={};for(const[k,v]of Object.entries(values)){before[k]=process.env[k];process.env[k]=v}return()=>{for(const[k,v]of Object.entries(before))v===undefined?delete process.env[k]:process.env[k]=v}}

test("runner persists approved diff as human-only non executable report",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-57-"));const restore=setEnv({MSE_25_57_SOURCE_REPORT:source(dir),MSE_25_57_DECISION:"APPROVE_DIFF",MSE_25_57_REVIEWER:"seo-director",MSE_25_57_RATIONALE:"The proposed refinement is accurate and can move to write-intent preparation.",MSE_25_57_REPORT_DIR:dir});try{const r=await run({emitOutput:false});assert.equal(r.certified,true);assert.equal(r.approval.nextStep,"PREPARE_NON_EXECUTABLE_VERSIONED_WRITE_INTENT");assert.equal(r.summary.executableCount,0);assert.equal(r.summary.websiteDesignerMutationCount,0);assert.equal((fs.statSync(r.reportPath).mode&0o777),0o600)}finally{restore()}});
test("runner requires real human reviewer and rationale",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-57-"));const restore=setEnv({MSE_25_57_SOURCE_REPORT:source(dir),MSE_25_57_DECISION:"APPROVE_DIFF",MSE_25_57_REVIEWER:"",MSE_25_57_RATIONALE:"Valid rationale text.",MSE_25_57_REPORT_DIR:dir});try{await assert.rejects(()=>run({emitOutput:false}),/REVIEWER_REQUIRED/)}finally{restore()}});
test("runner refuses writable source diff",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-57-"));const restore=setEnv({MSE_25_57_SOURCE_REPORT:source(dir,{writes:true}),MSE_25_57_DECISION:"REJECT_DIFF",MSE_25_57_REVIEWER:"seo-director",MSE_25_57_RATIONALE:"The source must remain strictly read-only.",MSE_25_57_REPORT_DIR:dir});try{await assert.rejects(()=>run({emitOutput:false}),/SOURCE_CERTIFICATION_FAILED/)}finally{restore()}});
