"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");
const {run}=require("../scripts/mse-25-56-editorial-diff-preview");
function mandate(){return{type:"MSE_25_55_EDITORIAL_MANDATE_REPORT",certified:true,readOnly:true,writes:false,publicWrites:false,sourceDecisionFingerprint:"decision",sourcePacketFingerprint:"packet",summary:{executableCount:0,automaticWriteCount:0},mandate:{mandateFingerprint:"mandate",siteSlug:"gien",page:"/services",proposal:{introduction:"Votre agence de voyages à Gien vous accompagne pour vos billets d’avion."},constraints:{existingPageOnly:true,pageCreationAllowed:false,publicationAllowed:false,websiteDesignerMutationAllowed:false,humanApprovalRequiredBeforeAnyFutureMutation:true}}}}
function fakePrisma(){let writes=0;return{get writes(){return writes},agencySitePage:{findFirst:async()=>({id:"page-1",slug:"services",path:"/services",title:"Services",h1:"Billetterie et vols à Gien",status:"published",published:true,site:{slug:"gien"},sections:[{sectionType:"hero",displayOrder:0,jsonContent:{__builderType:"hero",title:"Billetterie et vols à Gien",introduction:"Votre agence vous accompagne pour vos billets."}}],blocks:[]}),update:async()=>{writes++;throw new Error("WRITE_FORBIDDEN")},create:async()=>{writes++;throw new Error("WRITE_FORBIDDEN")}},agencySiteSection:{update:async()=>{writes++;throw new Error("WRITE_FORBIDDEN")}}}}
function sourceFile(dir,value=mandate()){const f=path.join(dir,"mandate.json");fs.writeFileSync(f,JSON.stringify(value));return f}

test("runner seals Website Designer diff and performs zero database writes",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-56-"));const prisma=fakePrisma();const result=await run({prisma,sourceReportPath:sourceFile(dir),reportDir:dir});assert.equal(result.certified,true);assert.equal(result.readOnly,true);assert.equal(result.summary.websiteDesignerMutationCount,0);assert.equal(result.summary.publicationCount,0);assert.equal(result.summary.pageCreationCount,0);assert.equal(prisma.writes,0);assert.equal(result.nextStep,"HUMAN_REVIEW_EDITORIAL_DIFF");assert.ok(fs.existsSync(result.reportPath))});

test("runner fails closed when mandate has no explicit editorial proposal",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-56-"));const value=mandate();delete value.mandate.proposal;await assert.rejects(()=>run({prisma:fakePrisma(),sourceReportPath:sourceFile(dir,value),reportDir:dir}),/EDITORIAL_PROPOSAL_MISSING/)});

test("runner fails closed when Website Designer page is missing",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-56-"));const prisma={agencySitePage:{findFirst:async()=>null}};await assert.rejects(()=>run({prisma,sourceReportPath:sourceFile(dir),reportDir:dir}),/WEBSITE_DESIGNER_PAGE_REQUIRED/)});

test("runner refuses unsafe source mandate before producing a diff",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-56-"));const value=mandate();value.writes=true;await assert.rejects(()=>run({prisma:fakePrisma(),sourceReportPath:sourceFile(dir,value),reportDir:dir}),/SOURCE_CERTIFICATION_FAILED/)});
