"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");const crypto=require("node:crypto");
const {run}=require("../scripts/mse-25-64-guarded-apply");
function stable(v){if(Array.isArray(v))return v.map(stable);if(!v||typeof v!=="object")return v;return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]))}function fp(v){return crypto.createHash("sha256").update(JSON.stringify(stable(v))).digest("hex")}
const createdAt=new Date("2026-08-26T10:00:00.000Z");const previousSnapshot={h1:"Avant",sections:[{id:"hero-1"}]};
function rollbackFingerprint(){return fp({pageIdentity:"page-1",version:"42",snapshot:previousSnapshot,sourceVersionId:"ver-42",sourceVersionCreatedAt:createdAt.toISOString()})}
function gateReport(){const rfp=rollbackFingerprint();return{type:"MSE_25_63_PRE_APPLY_VERSION_ROLLBACK_GATE_REPORT",certified:true,readOnly:true,writes:false,publicWrites:false,rollbackMaterial:{ready:true,snapshotFingerprint:rfp},gate:{type:"MSE_25_63_PRE_APPLY_VERSION_ROLLBACK_GATE",gatePassed:true,versionFresh:true,identityFresh:true,rollbackReady:true,applyAuthorized:false,executable:false,writes:false,publicWrites:false,websiteDesignerMutationAllowed:false,sourceConfirmationFingerprint:"confirm",sourceExecutionPlanFingerprint:"plan",sourceIntentFingerprint:"intent",gateFingerprint:"gate",rollbackSnapshotFingerprint:rfp,siteSlug:"gien",page:"/services",expectedPageIdentity:"page-1",currentVersion:"42"}}}
function diffReport(){return{type:"MSE_25_56_EDITORIAL_DIFF_OBSERVATION",certified:true,writes:false,publicWrites:false,preview:{type:"MSE_25_56_EDITORIAL_DIFF_PREVIEW",siteSlug:"gien",page:"/services",pageIdentity:"page-1",diffFingerprint:"diff",changedFields:["title","introduction"],before:{title:"Avant",introduction:"Intro avant"},after:{title:"Après",introduction:"Intro après"},policy:{humanReviewRequired:true,humanApprovalRequiredBeforeMutation:true,executable:false,writes:false,publicWrites:false}}}}
function files(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mse-25-64-"));const g=path.join(dir,"gate.json"),d=path.join(dir,"diff.json");fs.writeFileSync(g,JSON.stringify(gateReport()));fs.writeFileSync(d,JSON.stringify(diffReport()));return{dir,g,d}}
function basePage(){return{id:"page-1",siteId:"site-1",parentId:null,title:"Page",slug:"services",path:"/services",pageType:"services",menuTitle:"Services",menuLocation:"main",displayOrder:1,seoTitle:"SEO",metaDescription:"Meta",h1:"Avant",schemaType:"WebPage",status:"published",published:true,site:{slug:"gien"},sections:[{id:"hero-1",sectionType:"hero",displayOrder:0,jsonContent:{__builderType:"hero",title:"Avant",introduction:"Intro avant"}}],blocks:[],versions:[{id:"ver-42",version:42,snapshot:previousSnapshot,createdAt}]}}
function fakePrisma({version=42,failOnVersionCreate=false}={}){const state={page:basePage(),writes:[]};state.page.versions[0].version=version;return{state,$transaction:async fn=>{const backup=JSON.parse(JSON.stringify(state));const tx={agencySitePage:{findFirst:async()=>state.page,update:async({data})=>{state.writes.push("page.update");Object.assign(state.page,data);return state.page},findUnique:async()=>state.page},agencySiteSection:{update:async({where,data})=>{state.writes.push("section.update");const s=state.page.sections.find(x=>x.id===where.id);s.jsonContent=data.jsonContent;return s}},agencySitePageVersion:{create:async({data})=>{state.writes.push("version.create");if(failOnVersionCreate)throw new Error("VERSION_CREATE_FAILED");return{id:"ver-43",...data}}}};try{return await fn(tx)}catch(e){state.page=backup.page;state.writes=backup.writes;throw e}}}}
test("transactional runner mutates only approved fields and creates version N+1",async()=>{const f=files();const db=fakePrisma();const r=await run({prisma:db,gateReportPath:f.g,diffReportPath:f.d,applyToken:"APPLY_APPROVED_DIFF",reportDir:f.dir,emitOutput:false});assert.equal(r.ok,true);assert.equal(r.audit.previousVersion,42);assert.equal(r.audit.newVersion,43);assert.equal(r.audit.websiteDesignerMutationCount,1);assert.equal(db.state.page.h1,"Après");assert.equal(db.state.page.sections[0].jsonContent.title,"Après");assert.equal(db.state.page.sections[0].jsonContent.introduction,"Intro après");assert.deepEqual(db.state.writes,["section.update","page.update","version.create"])});
test("changed version blocks before any mutation",async()=>{const f=files();const db=fakePrisma({version:43});await assert.rejects(()=>run({prisma:db,gateReportPath:f.g,diffReportPath:f.d,applyToken:"APPLY_APPROVED_DIFF",reportDir:f.dir,emitOutput:false}),/VERSION_CHANGED/);assert.deepEqual(db.state.writes,[]);assert.equal(db.state.page.h1,"Avant")});
test("rollback proof change blocks before mutation",async()=>{const f=files();const db=fakePrisma();db.state.page.versions[0].snapshot={tampered:true};await assert.rejects(()=>run({prisma:db,gateReportPath:f.g,diffReportPath:f.d,applyToken:"APPLY_APPROVED_DIFF",reportDir:f.dir,emitOutput:false}),/ROLLBACK_PROOF_CHANGED/);assert.deepEqual(db.state.writes,[])});
test("failure while creating N+1 version rolls back page and section changes",async()=>{const f=files();const db=fakePrisma({failOnVersionCreate:true});await assert.rejects(()=>run({prisma:db,gateReportPath:f.g,diffReportPath:f.d,applyToken:"APPLY_APPROVED_DIFF",reportDir:f.dir,emitOutput:false}),/VERSION_CREATE_FAILED/);assert.equal(db.state.page.h1,"Avant");assert.equal(db.state.page.sections[0].jsonContent.title,"Avant");assert.equal(db.state.page.sections[0].jsonContent.introduction,"Intro avant");assert.deepEqual(db.state.writes,[])});
test("missing hero section fails closed and transaction stays clean",async()=>{const f=files();const db=fakePrisma();db.state.page.sections=[];await assert.rejects(()=>run({prisma:db,gateReportPath:f.g,diffReportPath:f.d,applyToken:"APPLY_APPROVED_DIFF",reportDir:f.dir,emitOutput:false}),/HERO_SECTION_REQUIRED/);assert.deepEqual(db.state.writes,[])});
