"use strict";

require("../src/modules/presence/presence-foundation.test");
require("../src/modules/presence/presence-convergence.test");
require("../src/modules/presence/directory-response-adapter.test");
require("../src/modules/presence/directory-schema-audit.test");
require("../src/modules/presence/provider-readiness.test");
require("../src/modules/presence/citation-observation.test");
require("../src/modules/presence/citation-recording.test");
require("../src/modules/presence/citation-discovery.test");
require("../src/modules/presence/citation-discovery-dataforseo.test");
require("../src/modules/presence/citation-discovery-recording.test");
require("../src/modules/presence/network-discovery.test");
require("../src/modules/presence/network-coverage.test");
require("../src/modules/presence/anomaly-queue.test");
require("../src/modules/presence/remediation-planner.test");
require("../src/modules/presence/google-remediation.test");
require("../src/modules/presence/remediation-execution-routes.test");
require("../src/modules/presence/network-google-remediation.test");
require("../src/modules/presence/runtime-listing-state.test");
require("../src/modules/presence/operational-readiness.test");
require("../src/modules/presence/operation-audit.test");
require("../src/modules/presence/operation-snapshots.test");
require("../src/modules/presence/propagation-watch.test");
require("../src/modules/presence/propagation-control.test");
require("../src/modules/presence/propagation-dashboard.test");
