"use client";
import {useEffect,useMemo,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"";
const labels={"2027-01-02":"02/01","2027-01-09":"09/01","2027-01-16":"16/01","2027-01-23":"23/01","2027-01-30":"30/01","2027-02-06":"06/02"};
export default function GroupsAdmin(){const [analytics,setAnalytics]=useState(null),[items,setItems]=useState([]),[error,setError]=useState("");
useEffect(()=>{Promise.all([fetch(API+"/api/group-campaigns/gloire-des-pharaons-2027/analytics",{credentials:"include"}),fetch(API+"/api/group-campaigns/gloire-des-pharaons-2027/pre-registrations",{credentials:"include"})]).then(async([a,b])=>{if(!a.ok||!b.ok)throw new Error("API");setAnalytics(await a.json());setItems((await b.json()).items||[])}).catch(()=>setError("Impossible de charger les données."))},[]);
const total=useMemo(()=>items.reduce((s,x)=>s+(x.travellerCount||0),0),[items]); const best=analytics?Object.entries(analytics.dates||{}).sort((a,b)=>b[1].travellers-a[1].travellers)[0]:null;
return <main style={S.main}><div style={S.head}><div><div style={S.kicker}>GROUPES · MONDESCALE</div><h1 style={S.h1}>Gloire des Pharaons 2027</h1></div><a href="/groupes/gloire-des-pharaons-2027" style={S.link}>Voir le tunnel ↗</a></div>{error&&<p>{error}</p>}<div style={S.cards}><K n={items.length} l="Préinscriptions"/><K n={total} l="Voyageurs potentiels"/><K n={best?labels[best[0]]:"—"} l="Date la plus compatible"/><K n={best?best[1].travellers:"—"} l="Voyageurs compatibles"/></div>
<h2 style={S.h2}>Compatibilité par date</h2><div style={S.tableWrap}><table style={S.table}><thead><tr><th>Date</th><th>Voyageurs</th><th>Intention forte</th><th>Préférence</th><th>Paris</th><th>Lyon</th></tr></thead><tbody>{analytics&&Object.entries(analytics.dates).map(([d,x])=><tr key={d}><td>{labels[d]}</td><td><b>{x.travellers}</b></td><td>{x.highIntent}</td><td>{x.preferred}</td><td>{x.paris}</td><td>{x.lyon}</td></tr>)}</tbody></table></div>
<h2 style={S.h2}>Préinscrits</h2><div style={S.tableWrap}><table style={S.table}><thead><tr><th>Contact</th><th>Voy.</th><th>Aéroport</th><th>Dates possibles</th><th>Préférence</th><th>Intention</th><th>Source</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.name}</b><br/><small>{x.email}{x.phone?" · "+x.phone:""}</small></td><td>{x.travellerCount}</td><td>{(x.origins||[]).join(" / ")}</td><td>{(x.departures||[]).map(d=>labels[d]).join(", ")}</td><td>{labels[x.preferredDeparture]||"Flexible"}</td><td>{x.intent==="HIGH"?"Forte":x.intent==="MEDIUM"?"À confirmer":"Information"}</td><td>{x.source||"Direct"}</td></tr>)}</tbody></table></div></main>}
function K({n,l}){return <div style={S.card}><div style={S.n}>{n}</div><div>{l}</div></div>}
const S={main:{padding:32,maxWidth:1400,margin:"auto",fontFamily:"Arial,sans-serif",color:"#17212b"},head:{display:"flex",justifyContent:"space-between",gap:20,alignItems:"center",flexWrap:"wrap"},kicker:{fontSize:12,fontWeight:800,letterSpacing:2,color:"#9a6a22"},h1:{fontFamily:"Georgia,serif",fontSize:42,margin:"8px 0 22px"},h2:{fontFamily:"Georgia,serif",fontSize:26,marginTop:36},link:{padding:"12px 16px",borderRadius:10,background:"#17212b",color:"#fff",textDecoration:"none"},cards:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12},card:{padding:20,border:"1px solid #e3e3e3",borderRadius:16,background:"#fff"},n:{fontSize:34,fontWeight:800,color:"#9a6a22",marginBottom:6},tableWrap:{overflowX:"auto",border:"1px solid #e5e5e5",borderRadius:14},table:{width:"100%",borderCollapse:"collapse",textAlign:"left",fontSize:14}};
