"use client";
import {useEffect,useState} from "react";
import {campaignApi} from "../../lib/campaign-api";
export default function CampaignsClient(){const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[name,setName]=useState("");
 const load=async()=>{setLoading(true);try{setItems(await campaignApi.list());setError("");}catch(e){setError(e.message);}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const create=async e=>{e.preventDefault();if(!name.trim())return;try{await campaignApi.create({name:name.trim(),objective:"sales"});setName("");await load();}catch(e){setError(e.message);}};
 const generate=async id=>{try{await campaignApi.generate(id);await load();}catch(e){setError(e.message);}};
 return <main className="campaign-shell"><header className="campaign-header"><div><p className="eyebrow">Marketing Engine</p><h1>Campagnes marketing</h1><p>Créez, orchestrez et validez les contenus de chaque campagne.</p></div><form onSubmit={create} className="create-form"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex. Hiver 2026" minLength={3}/><button>Nouvelle campagne</button></form></header>{error&&<div className="error-box">{error}</div>}{loading?<p>Chargement…</p>:<section className="campaign-grid">{items.length===0?<div className="empty">Aucune campagne. Créez la première campagne du réseau.</div>:items.map(c=><article key={c.id} className="campaign-card"><div className="card-top"><span className={`status status-${c.status}`}>{c.status}</span><span>{c.objective}</span></div><h2>{c.name}</h2><p>{c.description||"Campagne prête à être configurée."}</p><div className="metrics"><div><strong>{c.metrics?.agencies||0}</strong><span>agences</span></div><div><strong>{c.metrics?.destinations||0}</strong><span>destinations</span></div><div><strong>{c.metrics?.tasks||0}</strong><span>tâches</span></div><div><strong>{c.metrics?.assets||0}</strong><span>contenus</span></div></div><div className="progress"><span style={{width:`${c.metrics?.progress||0}%`}}/></div><footer><small>{c.metrics?.progress||0}% réalisé</small><button onClick={()=>generate(c.id)}>Préparer les tâches</button></footer></article>)}</section>}</main>}
