"use strict";
const express=require("express");
const {CampaignService}=require("./service");
module.exports=({prisma})=>{ const r=express.Router(); const s=req=>new CampaignService(prisma,req.tenantId);
 r.get("/campaigns/health",(req,res)=>res.json(s(req).health()));
 r.get("/campaigns",async(req,res,next)=>{try{res.json(await s(req).list());}catch(e){next(e);}});
 r.post("/campaigns",async(req,res,next)=>{try{res.status(201).json(await s(req).create(req.body||{}));}catch(e){next(e);}});
 r.get("/campaigns/:id",async(req,res,next)=>{try{res.json(await s(req).get(req.params.id));}catch(e){next(e);}});
 r.put("/campaigns/:id",async(req,res,next)=>{try{res.json(await s(req).update(req.params.id,req.body||{}));}catch(e){next(e);}});
 r.delete("/campaigns/:id",async(req,res,next)=>{try{res.json(await s(req).remove(req.params.id));}catch(e){next(e);}});
 r.post("/campaigns/:id/generate",async(req,res,next)=>{try{res.status(202).json(await s(req).generate(req.params.id,req.body||{}));}catch(e){next(e);}});
 r.get("/campaigns/:id/tasks",async(req,res,next)=>{try{res.json((await s(req).get(req.params.id)).tasks);}catch(e){next(e);}});
 r.get("/campaigns/:id/assets",async(req,res,next)=>{try{res.json((await s(req).get(req.params.id)).assets);}catch(e){next(e);}});
 return r; };
