"use strict";

const express = require("express");
const { randomUUID } = require("node:crypto");

const FUNNEL_VERSION = "mse-25.203-v1";
const CONSENT_VERSION = "2026-09-v1";
const FUNNELS = Object.freeze({
  "bois-colombes/soleil-hiver": Object.freeze({
    id:"bois-colombes-soleil-hiver",version:FUNNEL_VERSION,siteSlug:"bois-colombes",agencyCity:"Bois-Colombes",campaign:"soleil-hiver",
    title:"Trouvons votre prochain voyage au soleil",subtitle:"Quelques questions suffisent pour orienter nos premières recommandations.",
    questions:[
      {id:"departureWindow",type:"single",label:"Quand souhaitez-vous partir ?",required:true,options:["decembre","janvier","fevrier","mars","pas-encore-decide"]},
      {id:"travellers",type:"single",label:"Combien de voyageurs ?",required:true,options:["1","2","3-4","5-plus"]},
      {id:"budgetPerPerson",type:"single",label:"Quel budget envisagez-vous par personne ?",required:true,options:["moins-2000","2000-3000","3000-5000","5000-plus","a-definir"]},
      {id:"travelStyle",type:"multi",label:"Quel voyage vous attire ?",required:true,options:["plage","circuit","safari","croisiere","combine","a-decouvrir"]},
      {id:"departureAirport",type:"single",label:"D'où souhaitez-vous partir ?",required:true,options:["paris","autre","a-definir"]},
      {id:"maturity",type:"single",label:"Où en êtes-vous dans votre projet ?",required:true,options:["idees","comparaison","reservation-prochaine"]}
    ],
    contact:{required:["name","email","postalCode"],optional:["phone"],consentVersion:CONSENT_VERSION,consents:{emailMarketing:{required:false,label:"J’accepte de recevoir par e-mail des idées, conseils et offres de Mondescale Voyages."},phoneProjectContact:{requiredWhen:"phone",label:"Je souhaite être contacté(e) par téléphone par Mondescale Voyages au sujet de ce projet de voyage."}}}
  })
});
function clean(v,max=500){return String(v??"").trim().replace(/\s+/g," ").slice(0,max)}
function getFunnel(siteSlug,campaign){return FUNNELS[`${clean(siteSlug,160)}/${clean(campaign,160)}`]||null}
function scoreSubmission(input={}){const a=input.answers||{};let score=0;const reasons=[];if(a.maturity==="reservation-prochaine"){score+=40;reasons.push("reservation-prochaine")}else if(a.maturity==="comparaison"){score+=22;reasons.push("comparaison-active")}else if(a.maturity==="idees"){score+=8;reasons.push("inspiration")}const bp={"5000-plus":24,"3000-5000":20,"2000-3000":14,"moins-2000":8,"a-definir":3};const b=bp[a.budgetPerPerson]||0;score+=b;if(b)reasons.push(`budget:${a.budgetPerPerson}`);if(a.departureWindow&&a.departureWindow!=="pas-encore-decide"){score+=14;reasons.push("periode-definie")}if(a.departureAirport&&a.departureAirport!=="a-definir"){score+=6;reasons.push("depart-defini")}const styles=Array.isArray(a.travelStyle)?a.travelStyle:[a.travelStyle].filter(Boolean);if(styles.length&&!styles.includes("a-decouvrir")){score+=6;reasons.push("style-defini")}if(input.phone&&input.consents?.phoneProjectContact===true){score+=10;reasons.push("rappel-demande")}score=Math.min(score,100);const temperature=score>=70?"HOT":score>=40?"WARM":"COLD";return{score,temperature,recommendedAction:temperature==="HOT"?"CONTACT_PRIORITY":temperature==="WARM"?"CONTACT_OR_NURTURE":"NURTURE",reasons}}
function buildConsentEvidence(input={},context={}){return{version:CONSENT_VERSION,capturedAt:context.capturedAt||new Date().toISOString(),source:clean(context.source||"acquisition-funnel",120),funnelId:clean(context.funnelId,180),siteSlug:clean(context.siteSlug,160),emailMarketing:input.emailMarketing===true,phoneProjectContact:input.phoneProjectContact===true,phoneProvided:Boolean(clean(context.phone,50))}}
function buildErpLeadEnvelope({leadId,funnel,submission,qualification,consentEvidence}){return{schemaVersion:"mondescale.acquisition-lead.v1",eventType:"ACQUISITION_LEAD_QUALIFIED",leadId:clean(leadId,160),occurredAt:new Date().toISOString(),agency:{siteSlug:funnel.siteSlug,city:funnel.agencyCity},campaign:{id:funnel.campaign,funnelId:funnel.id,funnelVersion:funnel.version},contact:{name:clean(submission.name,120),email:clean(submission.email,180).toLowerCase(),phone:clean(submission.phone,50)||null,postalCode:clean(submission.postalCode,20)},project:submission.answers||{},qualification,consentEvidence}}
class DisabledErpConnector{async publish(envelope){return{status:"DISABLED",externalId:null,schemaVersion:envelope.schemaVersion}}}
function validateSubmission(funnel,body={}){const name=clean(body.name,120),email=clean(body.email,180).toLowerCase(),postalCode=clean(body.postalCode,20),phone=clean(body.phone,50),answers=body.answers||{},consents=body.consents||{};if(name.length<2)return"INVALID_NAME";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return"INVALID_EMAIL";if(!/^[0-9]{5}$/.test(postalCode))return"INVALID_POSTAL_CODE";if(phone&&phone.replace(/\D/g,"").length<8)return"INVALID_PHONE";if(phone&&consents.phoneProjectContact!==true)return"PHONE_CONSENT_REQUIRED";for(const q of funnel.questions){const value=answers[q.id];if(q.required&&(value==null||value===""||(Array.isArray(value)&&!value.length)))return`MISSING_${q.id.toUpperCase()}`}return null}
async function persistQualifiedLead(prisma,{funnel,submission,qualification,consentEvidence,context={}}){const site=await prisma.agencySite.findFirst({where:{slug:funnel.siteSlug},select:{id:true,agencyId:true,slug:true}});if(!site){const e=new Error("SITE_NOT_FOUND");e.code="SITE_NOT_FOUND";throw e}const id=`lead_${randomUUID().replaceAll("-","")}`;const phone=clean(submission.phone,50)||null;const a=submission.answers||{};const projectSummary=`Funnel ${funnel.id} | ${a.departureWindow||""} | ${a.travelStyle||""} | score ${qualification.score}/${qualification.temperature}`;const sourcePath=clean(context.sourcePath,1000)||`/voyage/${funnel.campaign}`;const rows=await prisma.$queryRawUnsafe(`INSERT INTO "PublicLead" ("id","agencyId","agencySiteId","siteSlug","projectType","source","sourcePage","sourcePath","sourceReferrer","utmSource","utmMedium","utmCampaign","utmContent","utmTerm","name","phone","email","destination","travelDates","travellers","budget","wishes","status","erpSyncStatus","notificationStatus","funnelId","funnelVersion","qualificationScore","leadTemperature","recommendedAction","funnelAnswers","consentEvidence","createdAt","updatedAt") VALUES ($1,$2,$3,$4,'leisure','acquisition-funnel',$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,'NEW','DISABLED','PENDING',$21,$22,$23,$24,$25,$26::jsonb,$27::jsonb,NOW(),NOW()) RETURNING "id","status","erpSyncStatus","createdAt"`,id,site.agencyId,site.id,site.slug,funnel.title,sourcePath,clean(context.referrer,2000)||null,clean(context.utmSource,240)||null,clean(context.utmMedium,240)||null,clean(context.utmCampaign,240)||funnel.campaign,clean(context.utmContent,240)||null,clean(context.utmTerm,240)||null,clean(submission.name,120),phone,clean(submission.email,180).toLowerCase(),Array.isArray(a.travelStyle)?a.travelStyle.join(", "):clean(a.travelStyle,240),clean(a.departureWindow,160),clean(a.travellers,120),clean(a.budgetPerPerson,160),projectSummary,funnel.id,funnel.version,qualification.score,qualification.temperature,qualification.recommendedAction,JSON.stringify(a),JSON.stringify(consentEvidence));return rows[0]}
function createRoutes({prisma,erpConnector=new DisabledErpConnector()}={}){const router=express.Router();router.get("/api/public/acquisition-funnels/:siteSlug/:campaign",(req,res)=>{const funnel=getFunnel(req.params.siteSlug,req.params.campaign);return funnel?res.json({ok:true,funnel}):res.status(404).json({ok:false,error:"FUNNEL_NOT_FOUND"})});router.post("/api/public/acquisition-funnels/:siteSlug/:campaign/qualify",(req,res)=>{const funnel=getFunnel(req.params.siteSlug,req.params.campaign);if(!funnel)return res.status(404).json({ok:false,error:"FUNNEL_NOT_FOUND"});return res.json({ok:true,funnelId:funnel.id,funnelVersion:funnel.version,qualification:scoreSubmission(req.body||{})})});router.post("/api/public/acquisition-funnels/:siteSlug/:campaign/submit",async(req,res)=>{const funnel=getFunnel(req.params.siteSlug,req.params.campaign);if(!funnel)return res.status(404).json({ok:false,error:"FUNNEL_NOT_FOUND"});const error=validateSubmission(funnel,req.body||{});if(error)return res.status(400).json({ok:false,error});if(!prisma)return res.status(503).json({ok:false,error:"PERSISTENCE_UNAVAILABLE"});try{const qualification=scoreSubmission(req.body);const consentEvidence=buildConsentEvidence(req.body.consents,{funnelId:funnel.id,siteSlug:funnel.siteSlug,phone:req.body.phone});const lead=await persistQualifiedLead(prisma,{funnel,submission:req.body,qualification,consentEvidence,context:req.body.context||{}});const envelope=buildErpLeadEnvelope({leadId:lead.id,funnel,submission:req.body,qualification,consentEvidence});const erp=await erpConnector.publish(envelope);return res.status(201).json({ok:true,lead,qualification,erp})}catch(e){if(e.code==="SITE_NOT_FOUND")return res.status(404).json({ok:false,error:e.code});console.error("[acquisition-funnel] submit failed",e);return res.status(500).json({ok:false,error:"ACQUISITION_SUBMIT_FAILED"})}});return router}
module.exports={CONSENT_VERSION,FUNNEL_VERSION,DisabledErpConnector,buildConsentEvidence,buildErpLeadEnvelope,getFunnel,persistQualifiedLead,routes:({prisma}={})=>createRoutes({prisma}),scoreSubmission,validateSubmission};
