import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
async function source(path){return readFile(new URL(`../${path}`,import.meta.url),"utf8")}
test("Presence server actions keep explicit confirmation on campaign mutations",async()=>{const code=await source("app/presence/campaigns/actions.js");assert.match(code,/confirm:true/);assert.match(code,/\/execute/);assert.match(code,/\/verify/);assert.match(code,/report\/freeze/);assert.match(code,/\/recovery/);assert.match(code,/recovery\/qualify/)});
test("campaign detail exposes lifecycle rollout decision and recovery entry without raw external URLs",async()=>{const code=await source("app/presence/campaigns/[campaignId]/page.js");assert.match(code,/Approuver/);assert.match(code,/Démarrer/);assert.match(code,/Exécuter les items figés/);assert.match(code,/Vérifier la propagation/);assert.match(code,/Décision rollout réseau/);assert.match(code,/readyForNetworkRollout/);assert.match(code,/Examiner une reprise/);assert.match(code,/NO-GO/);assert.doesNotMatch(code,/googleapis\.com/)});
test("campaign recovery UI separates untouched uncertain excluded and read-only qualified items",async()=>{const code=await source("app/presence/campaigns/[campaignId]/recovery/page.js");const actions=await source("app/presence/campaigns/actions.js");assert.match(code,/Recovery gate/);assert.match(code,/Sûrs à reprendre/);assert.match(code,/Ambigus à vérifier/);assert.match(code,/Déjà traités \/ exclus/);assert.match(code,/Qualifier par lecture Google/);assert.match(code,/Retry automatique : interdit/);assert.match(code,/Déjà appliqué chez Google/);assert.match(code,/Non appliqué chez Google/);assert.match(code,/État partiel \/ différent/);assert.match(code,/aucune écriture externe/);assert.match(code,/nouvelle campagne/);assert.match(code,/Création désactivée/);assert.match(actions,/recoverPresenceCampaign/);assert.match(actions,/qualifyPresenceRecoveryItem/);assert.match(actions,/recovery\/qualify/);assert.match(actions,/confirm:true/)});
test("daily agency provider actions confirm observations discovery and manual remediation",async()=>{const code=await source("app/presence/agency-provider-actions.js");assert.match(code,/\/observe/);assert.match(code,/discovery\/start/);assert.match(code,/discovery\/result/);assert.match(code,/candidateUrl/);assert.match(code,/confirmLowConfidence/);assert.match(code,/manual-remediation\/start/);assert.match(code,/manual-remediation\/verify/);assert.match(code,/confirm:true/)});
test("agency provider page exposes discovery and guided remediation without claiming provider write",async()=>{const code=await source("app/presence/agencies/[agencyId]/providers/[providerKey]/page.js");assert.match(code,/Canonique/);assert.match(code,/Observé/);assert.match(code,/Historique des observations/);assert.match(code,/Candidats détectés/);assert.match(code,/reste en statut pending/);assert.match(code,/Sélectionner cette fiche/);assert.match(code,/Remédiation manuelle guidée/);assert.match(code,/Local Engine prépare l’action, mais n’écrit pas chez ce provider/);assert.match(code,/Recontrôler et clôturer si conforme/);assert.doesNotMatch(code,/googleapis\.com/)});
test("Presence cockpit links deployment readiness pilot matrix and intervention details",async()=>{const code=await source("app/presence/page.js");assert.match(code,/summary\.agencies/);assert.match(code,/summary\.executableRemediations/);assert.match(code,/item\.priority/);assert.match(code,/\/presence\/agencies\//);assert.match(code,/\/presence\/matrix/);assert.match(code,/\/presence\/readiness/);assert.match(code,/\/presence\/pilot/)});
test("deployment readiness UI separates and freezes read-only preflight evidence",async()=>{const code=await source("app/presence/readiness/page.js");const actions=await source("app/presence/readiness/actions.js");assert.match(code,/deployment-readiness/);assert.match(code,/Préflight lecture seule/);assert.match(code,/readyForReadOnlyPreflight/);assert.match(code,/Migrations Presence/);assert.match(code,/Catalogue providers/);assert.match(code,/Couverture Google/);assert.match(code,/Google API lecture \/ validation/);assert.match(code,/PRESENCE_GOOGLE_WRITES_ENABLED/);assert.match(code,/Preuve de préflight/);assert.match(code,/Figer ce préflight/);assert.match(code,/aucune écriture externe/);assert.match(code,/DataForSEO discovery/);assert.match(actions,/deployment-readiness\/freeze/);assert.match(actions,/confirm:true/)});
test("deployment readiness UI exposes frozen-preflight pilot activation gate",async()=>{const code=await source("app/presence/readiness/page.js");assert.match(code,/Gate d’activation du pilote/);assert.match(code,/activationGate/);assert.match(code,/Activation pilote GO/);assert.match(code,/Activation pilote NO-GO/);assert.match(code,/Maximum 24 h/);assert.match(code,/preflightId/);assert.match(code,/googleWritesEnabled/)});
test("pilot UI exposes canary extended and progressive 50 100 rollout modes",async()=>{const code=await source("app/presence/pilot/page.js");const actions=await source("app/presence/pilot/actions.js");assert.match(code,/Canari 1×1/);assert.match(code,/Pilote étendu/);assert.match(code,/Rollout 50 %/);assert.match(code,/Rollout 100 %/);assert.match(code,/Preuve du palier précédent/);assert.match(code,/Prochain palier autorisé/);assert.match(code,/activationGate/);assert.match(code,/preflightId/);assert.doesNotMatch(code,/\/execute/);assert.match(actions,/\/api\/presence\/pilot\/campaign/);assert.match(actions,/rolloutStage/);assert.match(actions,/extended/);assert.match(actions,/confirm:true/)});
test("provider matrix distinguishes conformity automation manual monitor and blocked states",async()=>{const code=await source("app/presence/matrix/page.js");assert.match(code,/Matrice Presence/);assert.match(code,/Automatisables/);assert.match(code,/Manuelles/);assert.match(code,/Surveillance/);assert.match(code,/Bloquées/);assert.match(code,/automationEligible/)});
test("provider readiness UI exposes operational modes rather than theoretical capability",async()=>{const code=await source("app/presence/providers/page.js");assert.match(code,/Mode opérationnel/);assert.match(code,/API gérée/);assert.match(code,/Portail \/ correction manuelle/);assert.match(code,/Intégration bloquée/)});
test("admin network links to Presence cockpit",async()=>{const code=await source("app/admin-network/page.js");assert.match(code,/Presence réseau/);assert.match(code,/\/presence/)});
