import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
async function source(path){return readFile(new URL(`../${path}`,import.meta.url),"utf8")}
test("Presence server actions keep explicit confirmation on campaign mutations",async()=>{const code=await source("app/presence/campaigns/actions.js");assert.match(code,/confirm:true/);assert.match(code,/\/execute/);assert.match(code,/\/verify/);assert.match(code,/report\/freeze/);assert.match(code,/recovery\/qualify/);assert.match(code,/recovery\/resolve/);assert.match(code,/verify-resolution/);assert.match(code,/freeze-stabilization/)});
test("campaign detail exposes lifecycle rollout and recursive recovery trust",async()=>{const code=await source("app/presence/campaigns/[campaignId]/page.js");assert.match(code,/Approuver/);assert.match(code,/Démarrer/);assert.match(code,/Exécuter les items figés/);assert.match(code,/Vérifier la propagation/);assert.match(code,/Décision rollout réseau/);assert.match(code,/Examiner une reprise/);assert.match(code,/Chaîne de confiance recovery/);assert.match(code,/Profondeur/);assert.match(code,/Racine/);assert.match(code,/Toutes les preuves de stabilisation amont sont encore valides/);assert.match(code,/NO-GO/);assert.doesNotMatch(code,/googleapis\.com/)});
test("campaign recovery UI verifies and freezes stabilization before recovery",async()=>{const code=await source("app/presence/campaigns/[campaignId]/recovery/page.js");const actions=await source("app/presence/campaigns/actions.js");assert.match(code,/Recovery gate/);assert.match(code,/Sûrs à reprendre/);assert.match(code,/Ambigus \/ incidents/);assert.match(code,/Qualifier par lecture Google/);assert.match(code,/Retry automatique : interdit/);assert.match(code,/Corrigé et à recontrôler/);assert.match(code,/Recontrôler Google en lecture seule/);assert.match(code,/Figer la stabilisation/);assert.match(code,/Stabilisation figée/);assert.match(code,/Toute nouvelle preuve d’incident rend le snapshot obsolète/);assert.match(actions,/verifyPresenceRecoveryResolution/);assert.match(actions,/freezePresenceRecoveryStabilization/);assert.match(actions,/confirm:true/)});
test("daily agency provider actions confirm observations discovery and manual remediation",async()=>{const code=await source("app/presence/agency-provider-actions.js");assert.match(code,/\/observe/);assert.match(code,/discovery\/start/);assert.match(code,/manual-remediation\/verify/);assert.match(code,/confirm:true/)});
test("agency provider page exposes guided remediation without raw google api url",async()=>{const code=await source("app/presence/agencies/[agencyId]/providers/[providerKey]/page.js");assert.match(code,/Canonique/);assert.match(code,/Observé/);assert.match(code,/Remédiation manuelle guidée/);assert.doesNotMatch(code,/googleapis\.com/)});
test("Presence cockpit links readiness pilot and matrix",async()=>{const code=await source("app/presence/page.js");assert.match(code,/\/presence\/matrix/);assert.match(code,/\/presence\/readiness/);assert.match(code,/\/presence\/pilot/)});
test("deployment readiness UI exposes read-only preflight and activation gate",async()=>{const code=await source("app/presence/readiness/page.js");assert.match(code,/Préflight lecture seule/);assert.match(code,/readyForReadOnlyPreflight/);assert.match(code,/PRESENCE_GOOGLE_WRITES_ENABLED/);assert.match(code,/Gate d’activation du pilote/);assert.match(code,/preflightId/)});
test("pilot UI exposes canary extended and progressive rollout modes",async()=>{const code=await source("app/presence/pilot/page.js");assert.match(code,/Canari 1×1/);assert.match(code,/Pilote étendu/);assert.match(code,/Rollout 50 %/);assert.match(code,/Rollout 100 %/);assert.doesNotMatch(code,/\/execute/)});
test("provider matrix distinguishes automation and manual states",async()=>{const code=await source("app/presence/matrix/page.js");assert.match(code,/Automatisables/);assert.match(code,/Manuelles/);assert.match(code,/Bloquées/)});
test("provider readiness UI exposes operational modes",async()=>{const code=await source("app/presence/providers/page.js");assert.match(code,/Mode opérationnel/);assert.match(code,/API gérée/);assert.match(code,/Portail \/ correction manuelle/)});
test("admin network links to Presence cockpit",async()=>{const code=await source("app/admin-network/page.js");assert.match(code,/Presence réseau/);assert.match(code,/\/presence/)});
