import Link from "next/link";
import MainLayout from "../../components/MainLayout";
import MarkSeoActionDoneButton from "./MarkSeoActionDoneButton";
import SeoHealthActionPlan from "./SeoHealthActionPlan";
import SeoHealthGoal from "./SeoHealthGoal";
export const dynamic="force-dynamic";
function backendOrigin(){return String(process.env.BACKEND_INTERNAL_URL||process.env.API_INTERNAL_URL||"http://backend:4000").replace(/\/+$/g,"")}
async function api(path){const r=await fetch(`${backendOrigin()}${path}`,{headers:{Accept:"application/json","x-tenant-slug":process.env.NEXT_PUBLIC_TENANT_SLUG||"mondescale"},cache:"no-store"});if(!r.ok)throw new Error(`SEO agency HTTP ${r.status}: ${await r.text()}`);return r.json()}
function check(report,code){return(report?.checks||[]).find(x=>x?.code===code)||{}}
function Stat({label,value,hint}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-sm text-slate-500">{label}</div><div className="mt-2 text-3xl font-bold">{value}</div>{hint?<div className="mt-1 text-xs text-slate-500">{hint}</div>:null}</div>}
function momentum(s){return s==="improving"?"En progression":s==="declining"?"En recul":s==="stable"?"Stable":"Données insuffisantes"}
export default async function Page({params}){const {agencyId:id}=await params;const agencyId=Number(id);let report,history,error;try{[report,history]=await Promise.all([api(`/api/agency-launch/agencies/${agencyId}/readiness`),api(`/api/agency-launch/agencies/${agencyId}/seo-actions/history?limit=50`)])}catch(e){error=e}
const agency=report?.agency||{},rankings=check(report,"LOCAL_RANKINGS"),citations=check(report,"LOCAL_CITATIONS"),trust=check(report,"LOCAL_TRUST"),localSeo=check(report,"LOCAL_SEO"),content=check(report,"LOCAL_CONTENT"),similarity=check(report,"CONTENT_SIMILARITY"),health=report?.seoHealth||{},healthGoal=report?.seoHealthGoal||{},components=health.components||[],plan=report?.seoActionPlan||{},goals=report?.seoGoals||{},primary=goals.primary||{},keywordGoals=goals.keywords||[],actions=report?.seoActions?.actions||[],observing=report?.seoActions?.suppressed||[],items=rankings.items||[],inconsistencies=citations.inconsistencies||[],past=history?.actions||[];
return <MainLayout title={`SEO · ${agency.name||`Agence #${agencyId}`}`} subtitle={`${agency.city||"Ville non renseignée"} · visibilité locale, actions et mesure d'impact.`}><div className="mb-5 flex gap-3"><Link href="/seo-cockpit" className="rounded-xl border px-4 py-2 text-sm font-semibold">← Cockpit réseau</Link><Link href={`/website-builder?agencyId=${agencyId}`} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Ouvrir le Designer</Link></div>{error?<div className="rounded-2xl bg-red-50 p-5 text-red-800">{error.message}</div>:<>
<div className="grid grid-cols-2 gap-4 xl:grid-cols-8"><Stat label="Santé SEO" value={`${health.score??0}/100`} hint={`Note ${health.grade||"—"} · ${health.status==="healthy"?"Saine":health.status==="watch"?"À surveiller":"Prioritaire"}`}/><Stat label="Prochain palier" value={`${healthGoal.target??"—"}/100`} hint={healthGoal.requiredGain!=null?`+${healthGoal.requiredGain} point${Number(healthGoal.requiredGain)>1?"s":""}`:null}/><Stat label="Top 10" value={rankings.top10Keywords||0}/><Stat label="Top 20" value={rankings.top20Keywords||0}/><Stat label="En progression" value={rankings.improvingKeywords||0}/><Stat label="En recul" value={rankings.decliningKeywords||0}/><Stat label="Actions ouvertes" value={actions.length}/><Stat label="En observation" value={observing.length}/></div>
<SeoHealthGoal goal={healthGoal}/>
<section className="mt-6 rounded-2xl border bg-white shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-xl font-bold">Santé SEO détaillée</h2><p className="text-sm text-slate-500">Score post-publication indépendant de la readiness : chaque composante montre les points obtenus et les points récupérables.</p></div><div className="grid gap-4 p-6 md:grid-cols-2 xl:grid-cols-3">{components.map(c=><div key={c.code} className="rounded-xl border bg-slate-50 p-4"><div className="flex justify-between gap-3"><strong>{c.label}</strong><strong>{Number(c.points||0).toFixed(1)} / {c.weight}</strong></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-slate-800" style={{width:`${Math.min(100,Number(c.ratio||0)*100)}%`}}/></div><div className="mt-3 text-sm text-slate-600">{c.detail}</div><div className="mt-2 text-xs text-slate-500">Points à récupérer : {Math.max(0,c.weight-c.points).toFixed(1)}</div></div>)}</div><div className="border-t px-6 py-4 text-xs text-slate-500">{health.disclaimer}</div></section>
<SeoHealthActionPlan plan={plan}/>
{primary.status!=="not_applicable"?<section className="mt-6 rounded-2xl border border-violet-200 bg-violet-50 p-6"><h2 className="text-xl font-bold text-violet-950">Objectifs SEO locaux</h2><div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-xl bg-white p-4"><div className="text-3xl font-black">{primary.current||0} / {primary.target||0}</div><div className="text-sm">mots-clés dans le Top 10</div></div><div className="space-y-2">{keywordGoals.map(g=><div key={g.keywordId} className="rounded-xl bg-white p-3"><strong>{g.keyword}</strong><div className="text-sm">Position {g.currentPosition} → Top 10 · {momentum(g.momentum?.status)}</div></div>)}</div></div></section>:null}
<div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border bg-white shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-xl font-bold">Positions locales</h2></div>{items.map(i=><div key={i.keywordId} className="grid grid-cols-[1fr_auto] border-b px-6 py-4"><div><strong>{i.keyword}</strong><div className="text-xs text-slate-500">{momentum(i.momentum?.status)}</div></div><div className="text-2xl font-black">{i.position??"—"}</div></div>)}</section><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Santé locale</h2><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span>Google local</span><strong>{localSeo.passed?"Complet":"À compléter"}</strong></div><div className="flex justify-between"><span>Avis</span><strong>{trust.passed?"Sain":"À travailler"}</strong></div><div className="flex justify-between"><span>Contenu</span><strong>{content.passed?"Différencié":"À enrichir"}</strong></div><div className="flex justify-between"><span>Anti-clone</span><strong>{similarity.passed===false?"Alerte":"OK"}</strong></div><div className="flex justify-between"><span>Citations</span><strong>{Math.round((citations.consistencyRate||0)*100)} %</strong></div></div></section></div>
{observing.length?<section className="mt-6 rounded-2xl border border-blue-200 bg-blue-50 p-6"><h2 className="text-xl font-bold">En observation</h2>{observing.map((o,n)=><div key={n} className="mt-3 rounded-xl bg-white p-3"><strong>{o.action?.title}</strong><div className="text-sm">Réalisée il y a {o.ageDays} j · réévaluation dans {o.remainingDays} j</div></div>)}</section>:null}
<div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border bg-white shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-xl font-bold">Actions recommandées</h2></div>{actions.map((a,n)=><div key={n} className="border-b px-6 py-4"><strong>{a.title}</strong><p className="text-sm text-slate-600">{a.detail}</p><MarkSeoActionDoneButton agencyId={agencyId} action={a}/></div>)}</section><section className="rounded-2xl border bg-white shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-xl font-bold">Citations à corriger</h2></div>{inconsistencies.map(i=><div key={i.listingId} className="border-b px-6 py-4"><strong>{i.directory}</strong><div className="text-sm">{i.fields.join(", ")}</div></div>)}</section></div>
<section className="mt-6 rounded-2xl border bg-white shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-xl font-bold">Historique des actions et impact</h2></div>{past.map(a=><div key={a.id} className="grid gap-3 border-b px-6 py-4 lg:grid-cols-3"><strong>{a.title}</strong><span>Baseline : {a.impact?.baseline?.position??"—"}</span><div>{(a.impact?.windows||[]).map(w=><span key={w.days} className="mr-2 rounded bg-slate-100 px-2 py-1 text-xs">J+{w.days}: {w.result?.position??"—"}</span>)}</div></div>)}</section>
</>}</MainLayout>}
