"use strict";

const express = require("express");
const { tenantIdForRequest } = require("../minisite-structured-data/routes");
const { SEARCH_CONSOLE_OWNER_PERMISSION } = require("./provider");
const { createSearchConsoleProvider, searchConsoleProviderReadiness } = require("./provider-factory");
const { runSearchConsolePreflight } = require("./preflight");
const { SearchConsoleSubmissionService } = require("./service");
const { SearchConsoleObservabilityService } = require("./observability");
const { SearchConsolePerformanceService } = require("./performance");
const { IndexationCoverageService } = require("./indexation-coverage");
const { PublicIndexabilityObserver } = require("./public-indexability-observer");
const { RuntimeIndexabilityAuditService } = require("./runtime-indexability-audit");
const { createRuntimeFetchTransport } = require("./runtime-fetch-transport");
const { buildIndexationIncidentQueue } = require("./indexation-incident-queue");
const { SeoOpportunityWorkQueueService } = require("./opportunity-work-queue");
const { resolveLocalSeoContext } = require("./local-seo-intent");

function sendError(response, error) {
  response.status(Number(error?.statusCode || error?.status || 500)).json({ error: error?.code || "SEARCH_CONSOLE_SUBMISSION_ERROR", message: error?.message || "Erreur Search Console.", details: error?.details || {} });
}
function normalizeCoveragePagePrefix(value, fallback) { const raw=String(value||fallback||"").trim(); if(!raw)return null; const withProtocol=/^https?:\/\//i.test(raw)?raw:`https://${raw}`; try{const url=new URL(withProtocol);const pathname=url.pathname==="/"?"/":`${url.pathname.replace(/\/+$/g,"")}/`;return `${url.protocol}//${url.host}${pathname}`;}catch(_error){return raw;} }
function coverageScope(request, submissionService) { const publicOrigin=String(submissionService.structuredDataService.publicOrigin||"https://agences.mondescale.com").replace(/\/+$/g,""); const rawPrefix=request.query?.pagePrefix||process.env.SEARCH_CONSOLE_PAGE_PREFIX||process.env.SEARCH_CONSOLE_PREFERRED_HOST||`${publicOrigin}/`; return {siteUrl:request.query?.siteUrl||process.env.SEARCH_CONSOLE_SITE_URL||process.env.SEARCH_CONSOLE_PROPERTY||"sc-domain:mondescale.com",pagePrefix:normalizeCoveragePagePrefix(rawPrefix,`${publicOrigin}/`),days:request.query?.days}; }
function publicAuditLimit(value) { const parsed=Number.parseInt(value,10);if(!Number.isFinite(parsed))return 200;return Math.max(1,Math.min(500,parsed)); }
async function readPublicAudit({tenantId,request,submissionService,observer}) { const sitemap=await submissionService.structuredDataService.previewSitemap({tenantId});const allUrls=(sitemap?.entries||[]).map((entry)=>entry?.url).filter(Boolean);const limit=publicAuditLimit(request.query?.limit);const selectedUrls=allUrls.slice(0,limit);const audit=await observer.audit({urls:selectedUrls,publicOrigin:submissionService.structuredDataService.publicOrigin});return {audit,sitemapUrlCount:allUrls.length,auditedUrlCount:selectedUrls.length,truncated:allUrls.length>selectedUrls.length}; }

function routes({ prisma, service, provider } = {}) {
  const router=express.Router();
  const activeProvider=(provider && provider.name !== "disabled") ? provider : createSearchConsoleProvider({prisma});
  const submissionService=service||new SearchConsoleSubmissionService({prisma,provider:activeProvider});
  const observabilityService=new SearchConsoleObservabilityService({prisma,structuredDataService:submissionService.structuredDataService,provider:submissionService.provider});
  const performanceService=new SearchConsolePerformanceService({provider:submissionService.provider});
  const indexationCoverageService=new IndexationCoverageService({structuredDataService:submissionService.structuredDataService,performanceService});
  const publicOrigin=submissionService.structuredDataService.publicOrigin;
  const fetchOrigin=process.env.PUBLIC_INDEXABILITY_FETCH_ORIGIN||null;
  const runtimeFetch=createRuntimeFetchTransport({publicOrigin,fetchOrigin});
  const publicIndexabilityObserver=new PublicIndexabilityObserver({fetchImpl:runtimeFetch,timeoutMs:Number(process.env.PUBLIC_INDEXABILITY_TIMEOUT_MS||5000),concurrency:Number(process.env.PUBLIC_INDEXABILITY_CONCURRENCY||6)});
  const runtimeAuditService=new RuntimeIndexabilityAuditService({structuredDataService:submissionService.structuredDataService,publicIndexabilityObserver,fetchImpl:runtimeFetch,timeoutMs:Number(process.env.PUBLIC_INDEXABILITY_TIMEOUT_MS||5000)});
  const opportunityQueue=new SeoOpportunityWorkQueueService({prisma});

  router.get("/search-console-submissions/health",async(_request,response)=>{const active=submissionService.provider;const readiness=await searchConsoleProviderReadiness({prisma});response.json({ok:true,capability:"search-console-submission-journal",provider:active?.name||"unknown",credentialMode:active?.credentialMode||null,providerConfigured:readiness.configured===true,providerTransportConfigured:active?.isConfigured?.()===true,tokenReadiness:readiness,requiredPermissionLevel:SEARCH_CONSOLE_OWNER_PERMISSION,explicitApprovalRequired:true,autoSubmit:false,readOnlySitemapObservability:true,readOnlySearchPerformance:true,readOnlyIndexationCoverage:true,readOnlyPublicHttpIndexability:true,readOnlyIndexationIncidentQueue:true,readOnlyRuntimeReadiness:true,publicAuditFetchOrigin:fetchOrigin||publicOrigin});});
  router.get("/search-console-submissions/properties",async(request,response)=>{try{await tenantIdForRequest(prisma,request);const properties=await submissionService.provider.listSites();response.json({provider:submissionService.provider?.name||"unknown",count:properties.length,requiredPermissionLevel:SEARCH_CONSOLE_OWNER_PERMISSION,properties:properties.map((property)=>({siteUrl:property?.siteUrl||null,permissionLevel:property?.permissionLevel||null,eligibleForSitemapSubmission:property?.permissionLevel===SEARCH_CONSOLE_OWNER_PERMISSION}))});}catch(error){sendError(response,error);}});
  router.get("/search-console-submissions/candidates",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);response.json(await submissionService.candidates({tenantId}));}catch(error){sendError(response,error);}});
  router.get("/search-console-submissions/indexation-coverage",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);response.json(await indexationCoverageService.diagnoseNetwork({tenantId,...coverageScope(request,submissionService)}));}catch(error){sendError(response,error);}});
  router.get("/search-console-submissions/public-indexability",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);const result=await readPublicAudit({tenantId,request,submissionService,observer:publicIndexabilityObserver});response.json({...result.audit,sitemapUrlCount:result.sitemapUrlCount,auditedUrlCount:result.auditedUrlCount,truncated:result.truncated,invariants:{readOnlyHttp:true,googleSubmission:false,pageCreation:false,publicationMutation:false,websiteDesignerMutation:false}});}catch(error){sendError(response,error);}});
  router.get("/search-console-submissions/runtime-readiness",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);const scope=coverageScope(request,submissionService);const coverage=await indexationCoverageService.diagnoseNetwork({tenantId,...scope});const result=await runtimeAuditService.audit({tenantId,coverage,limit:publicAuditLimit(request.query?.limit)});response.json({...result,scope});}catch(error){sendError(response,error);}});
  router.get("/search-console-submissions/indexation-incidents",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);const scope=coverageScope(request,submissionService);const [coverage,publicResult]=await Promise.all([indexationCoverageService.diagnoseNetwork({tenantId,...scope}),readPublicAudit({tenantId,request,submissionService,observer:publicIndexabilityObserver})]);response.json({...buildIndexationIncidentQueue({coverage,publicAudit:publicResult.audit}),scope,sitemapUrlCount:publicResult.sitemapUrlCount,auditedUrlCount:publicResult.auditedUrlCount,truncated:publicResult.truncated});}catch(error){sendError(response,error);}});
  router.get("/search-console-submissions/sites/:siteSlug/status",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);response.json(await observabilityService.sitemapStatus({tenantId,siteSlug:request.params.siteSlug,siteUrl:request.query?.siteUrl}));}catch(error){sendError(response,error);}});
  router.get("/search-console-submissions/sites/:siteSlug/indexation-coverage",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);response.json(await indexationCoverageService.diagnose({tenantId,siteSlug:request.params.siteSlug,...coverageScope(request,submissionService)}));}catch(error){sendError(response,error);}});
  router.get("/search-console-submissions/performance",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);const dimensions=String(request.query?.dimensions||"query").split(",").map((item)=>item.trim()).filter(Boolean);const siteSlug=String(request.query?.siteSlug||"").trim();const localContext=siteSlug?await resolveLocalSeoContext(prisma,tenantId,siteSlug):null;response.json(await performanceService.query({siteUrl:request.query?.siteUrl,pagePrefix:request.query?.pagePrefix,days:request.query?.days,dimensions,rowLimit:request.query?.rowLimit,localContext}));}catch(error){sendError(response,error);}});
  router.get("/seo-opportunity-work-queue",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);response.json(await opportunityQueue.list({tenantId,status:request.query?.status,limit:request.query?.limit}));}catch(error){sendError(response,error);}});
  router.post("/seo-opportunity-work-queue",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);const siteSlug=String(request.body?.siteSlug||"").trim();const site=siteSlug?await submissionService.structuredDataService.repository.findSiteBySlug(siteSlug,tenantId):null;if(!site)throw Object.assign(new Error("Mini-site SEO introuvable."),{code:"SEO_OPPORTUNITY_SITE_NOT_FOUND",statusCode:404});response.status(201).json(await opportunityQueue.create({tenantId,siteId:String(site.id),siteSlug,opportunity:request.body?.opportunity,createdBy:request.body?.createdBy||request.user?.id||null}));}catch(error){sendError(response,error);}});
  router.post("/seo-opportunity-work-queue/:runId/status",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);response.json(await opportunityQueue.transition({tenantId,runId:request.params.runId,status:request.body?.status,actor:request.body?.actor||request.user?.id||null,measurement:request.body?.measurement}));}catch(error){sendError(response,error);}});
  router.get("/search-console-submissions",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);response.json(await submissionService.list({tenantId,status:request.query?.status,limit:request.query?.limit}));}catch(error){sendError(response,error);}});
  router.post("/search-console-submissions/preflight",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);response.json(await runSearchConsolePreflight({tenantId,siteSlug:request.body?.siteSlug,siteUrl:request.body?.siteUrl,structuredDataService:submissionService.structuredDataService,provider:submissionService.provider}));}catch(error){sendError(response,error);}});
  router.post("/search-console-submissions/prepare",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);const result=await submissionService.prepare({tenantId,siteSlug:request.body?.siteSlug,siteUrl:request.body?.siteUrl,sitemapUrl:request.body?.sitemapUrl,requestedBy:request.body?.requestedBy||request.user?.id||null});response.status(201).json(result);}catch(error){sendError(response,error);}});
  router.post("/search-console-submissions/:runId/approve",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);response.json(await submissionService.approve({tenantId,runId:request.params.runId,approvedBy:request.body?.approvedBy||request.user?.id||null}));}catch(error){sendError(response,error);}});
  router.post("/search-console-submissions/:runId/submit",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);response.json(await submissionService.submit({tenantId,runId:request.params.runId}));}catch(error){sendError(response,error);}});
  router.get("/search-console-submissions/:runId",async(request,response)=>{try{const tenantId=await tenantIdForRequest(prisma,request);const result=await submissionService.get({tenantId,runId:request.params.runId});if(!result)return response.status(404).json({error:"SEARCH_CONSOLE_SUBMISSION_NOT_FOUND"});response.json(result);}catch(error){sendError(response,error);}});
  return router;
}
module.exports={coverageScope,normalizeCoveragePagePrefix,publicAuditLimit,readPublicAudit,routes,sendError};
