import Link from "next/link";
import MainLayout from "../components/MainLayout";

export const dynamic = "force-dynamic";

function backendOrigin() { return String(process.env.BACKEND_INTERNAL_URL || process.env.API_INTERNAL_URL || "http://backend:4000").replace(/\/+$/g, ""); }
async function loadSeoCockpit() { const response = await fetch(`${backendOrigin()}/api/agency-launch/network`, { headers: { Accept: "application/json", "x-tenant-slug": process.env.NEXT_PUBLIC_TENANT_SLUG || "mondescale" }, cache: "no-store" }); if (!response.ok) throw new Error(`SEO cockpit HTTP ${response.status}: ${await response.text()}`); return response.json(); }
function Card({ label, value, hint }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-sm font-medium text-slate-500">{label}</div><div className="mt-2 text-3xl font-bold text-slate-950">{value}</div>{hint ? <div className="mt-2 text-xs text-slate-500">{hint}</div> : null}</div>; }
function signed(value) { if (value == null) return "—"; return value > 0 ? `+${value}` : String(value); }
function deltaClass(value) { if (value > 0) return "text-emerald-700"; if (value < 0) return "text-red-700"; return "text-slate-700"; }
function healthClass(status) { if (status === "healthy") return "bg-emerald-100 text-emerald-800"; if (status === "watch") return "bg-amber-100 text-amber-800"; return "bg-red-100 text-red-800"; }

export default async function SeoCockpitPage() {
  let payload = null; let error = null; try { payload = await loadSeoCockpit(); } catch (loadError) { error = loadError; }
  const priorities = payload?.seoPriorities || {}; const learning = payload?.seoLearning || {}; const goals = payload?.seoGoals || {}; const trend = payload?.seoVisibilityTrend || {}; const health = payload?.seoHealth || {};
  const actions = Array.isArray(priorities.actions) ? priorities.actions : []; const priorityAgencies = Array.isArray(goals.priorityAgencies) ? goals.priorityAgencies : []; const trendWindows = Array.isArray(trend.windows) ? trend.windows : []; const healthPriorityAgencies = Array.isArray(health.priorityAgencies) ? health.priorityAgencies : [];

  return <MainLayout title="Cockpit SEO réseau" subtitle="Santé SEO, objectifs Top 10, évolution de visibilité et priorités des mini-sites Mondescale.">
    {error ? <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-red-800">Impossible de charger le cockpit SEO : {error.message}</div> : <>
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-6">
        <Card label="Santé SEO réseau" value={`${Number(health.averageScore || 0).toFixed(1)}/100`} hint={`${health.healthy || 0} saines · ${health.watch || 0} à surveiller · ${health.priority || 0} prioritaires`} />
        <Card label="Top 10 actuel" value={goals.currentTop10 || 0} hint={`${goals.agenciesObserved || 0} agences observées`} />
        <Card label="Objectif Top 10" value={goals.targetTop10 || 0} hint={`${goals.remainingTop10 || 0} entrées restantes`} />
        <Card label="Progression objectif" value={`${Number(goals.progress || 0).toFixed(1)} %`} hint={`${goals.opportunityKeywords || 0} requêtes proches`} />
        <Card label="Actions prioritaires" value={priorities.highPriority || 0} />
        <Card label="Actions mesurées" value={learning.measuredActions || 0} />
      </div>

      <section className="mt-6 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="text-xl font-bold text-slate-950">Santé SEO des agences</h2><p className="mt-1 text-sm text-slate-500">Classement post-publication distinct de la readiness de mise en ligne.</p></div><div className="divide-y divide-slate-100">{healthPriorityAgencies.map((row) => <div key={row.agency?.id} className="grid gap-4 px-6 py-4 md:grid-cols-[1.4fr_0.6fr_1fr] md:items-center"><div><Link href={`/seo-cockpit/${row.agency?.id}`} className="font-bold text-slate-950 hover:underline">{row.agency?.name || `Agence #${row.agency?.id}`}</Link><div className="mt-1 text-xs text-slate-500">{row.agency?.city || "Ville non renseignée"}</div></div><div><div className="text-2xl font-black text-slate-950">{row.seoHealth?.score || 0}/100</div><span className={`mt-1 inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${healthClass(row.seoHealth?.status)}`}>{row.seoHealth?.grade || "—"}</span></div><div className="text-sm text-slate-600">{(row.seoHealth?.components || []).sort((a,b)=>a.ratio-b.ratio).slice(0,2).map((item)=><div key={item.code}>{item.label} : {Math.round(Number(item.ratio || 0)*100)} %</div>)}</div></div>)}{!healthPriorityAgencies.length ? <div className="px-6 py-10 text-center text-emerald-700">Aucune agence prioritaire actuellement.</div> : null}</div></section>

      <section className="mt-6 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="text-xl font-bold text-slate-950">Évolution de la visibilité réseau</h2></div><div className="grid gap-4 p-6 md:grid-cols-3">{trendWindows.map((window)=><div key={window.days} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="font-bold">Sur {window.days} jours</div>{window.comparable?<div className="mt-4 grid grid-cols-2 gap-3"><div><div className="text-xs text-slate-500">Top 10</div><div className={`text-2xl font-black ${deltaClass(window.top10Delta)}`}>{signed(window.top10Delta)}</div></div><div><div className="text-xs text-slate-500">Top 20</div><div className={`text-2xl font-black ${deltaClass(window.top20Delta)}`}>{signed(window.top20Delta)}</div></div></div>:<div className="mt-4 text-sm text-slate-500">Historique insuffisant.</div>}</div>)}</div></section>

      <section className="mt-6 rounded-2xl border border-cyan-200 bg-cyan-50 shadow-sm"><div className="border-b border-cyan-200 px-6 py-5"><h2 className="text-xl font-bold text-cyan-950">Potentiel Top 10 du réseau</h2></div><div className="divide-y divide-cyan-100">{priorityAgencies.map((row)=><div key={row.agency?.id} className="grid gap-4 px-6 py-4 lg:grid-cols-[1.3fr_0.7fr_0.7fr_1fr] lg:items-center"><div><Link href={`/seo-cockpit/${row.agency?.id}`} className="font-bold text-cyan-950 hover:underline">{row.agency?.name || `Agence #${row.agency?.id}`}</Link><div className="mt-1 text-xs text-cyan-800">{row.agency?.city || ""}</div></div><div><span className="text-sm text-cyan-700">Top 10</span><div className="font-bold">{row.currentTop10} → {row.targetTop10}</div></div><div><span className="text-sm text-cyan-700">Opportunités</span><div className="font-bold">{row.opportunityKeywords}</div></div><div className="text-sm text-cyan-950">{row.nearestOpportunity ? `${row.nearestOpportunity.keyword} · position ${row.nearestOpportunity.currentPosition}` : "Pas d’opportunité proche"}</div></div>)}</div></section>

      <section className="mt-6 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="text-xl font-bold text-slate-950">Actions SEO prioritaires</h2></div><div className="divide-y divide-slate-100">{actions.map((action,index)=><article key={`${action.agency?.id||"network"}-${action.code}-${index}`} className="px-6 py-5"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-orange-100 px-2.5 py-1 text-xs font-bold uppercase text-orange-800">{action.priority}</span>{action.agency?.id?<Link href={`/seo-cockpit/${action.agency.id}`} className="font-semibold text-cyan-900 hover:underline">{action.agency?.name}{action.agency?.city?` · ${action.agency.city}`:""}</Link>:null}</div><h3 className="mt-3 text-lg font-bold">{action.title}</h3><p className="mt-1 text-sm text-slate-600">{action.detail}</p><div className="mt-3 text-xs text-slate-500">Score final : {action.score?.final ?? action.opportunityScore ?? 0}</div></article>)}</div></section>
    </>}
  </MainLayout>;
}
