import Link from "next/link";
import MainLayout from "../components/MainLayout";
export const dynamic="force-dynamic";
function backendOrigin(){return String(process.env.BACKEND_INTERNAL_URL||process.env.API_INTERNAL_URL||"http://backend:4000").replace(/\/+$/g,"")}
async function loadSeoCockpit(){const r=await fetch(`${backendOrigin()}/api/agency-launch/network`,{headers:{Accept:"application/json","x-tenant-slug":process.env.NEXT_PUBLIC_TENANT_SLUG||"mondescale"},cache:"no-store"});if(!r.ok)throw new Error(`SEO cockpit HTTP ${r.status}: ${await r.text()}`);return r.json()}
function Card({label,value,hint}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-sm text-slate-500">{label}</div><div className="mt-2 text-3xl font-bold">{value}</div>{hint?<div className="mt-1 text-xs text-slate-500">{hint}</div>:null}</div>}
function healthClass(status){return status==="healthy"?"bg-emerald-100 text-emerald-800":status==="watch"?"bg-amber-100 text-amber-800":"bg-red-100 text-red-800"}
function automationLabel(status){return status==="healthy"?"À jour":status==="attention"?"À contrôler":"Sans données"}
function automationClass(status){return status==="healthy"?"border-emerald-200 bg-emerald-50 text-emerald-950":status==="attention"?"border-amber-200 bg-amber-50 text-amber-950":"border-red-200 bg-red-50 text-red-950"}
export default async function Page(){let payload,error;try{payload=await loadSeoCockpit()}catch(e){error=e}const health=payload?.seoHealth||{},automation=payload?.seoHealthAutomation||{},goals=payload?.seoGoals||{},priorities=payload?.seoPriorities||{},learning=payload?.seoLearning||{},trend=payload?.seoVisibilityTrend||{},rows=health.priorityAgencies||[],quickWins=[...rows].filter(r=>r.seoHealthGoal?.reachable&&Number(r.seoHealthGoal?.requiredGain||999)<=5).sort((a,b)=>Number(a.seoHealthGoal.requiredGain)-Number(b.seoHealthGoal.requiredGain)).slice(0,8),trendWindows=trend.windows||[],actions=priorities.actions||[],automationIssues=automation.issues||[];
return <MainLayout title="Cockpit SEO réseau" subtitle="Santé SEO, paliers de progression, visibilité locale et priorités des mini-sites Mondescale.">{error?<div className="rounded-2xl bg-red-50 p-5 text-red-800">{error.message}</div>:<>
<div className="grid grid-cols-2 gap-4 lg:grid-cols-7"><Card label="Santé SEO réseau" value={`${Number(health.averageScore||0).toFixed(1)}/100`} hint={`${health.healthy||0} saines · ${health.watch||0} à surveiller · ${health.priority||0} prioritaires`}/><Card label="Snapshots SEO" value={automationLabel(automation.status)} hint={`${automation.healthy||0} à jour · ${automation.stale||0} en retard · ${automation.missing||0} absentes`}/><Card label="Quick wins santé" value={quickWins.length} hint="Palier atteignable avec ≤ 5 points"/><Card label="Top 10 actuel" value={goals.currentTop10||0}/><Card label="Objectif Top 10" value={goals.targetTop10||0}/><Card label="Actions prioritaires" value={priorities.highPriority||0}/><Card label="Actions mesurées" value={learning.measuredActions||0}/></div>
<section className={`mt-6 rounded-2xl border shadow-sm ${automationClass(automation.status)}`}><div className="border-b border-current/10 px-6 py-5"><h2 className="text-xl font-bold">Collecte automatique des snapshots SEO</h2><p className="mt-1 text-sm opacity-80">La fraîcheur est évaluée à partir des captures réellement enregistrées en base, avec un seuil de {automation.freshnessTargetHours||36} heures.</p></div><div className="grid gap-4 p-6 md:grid-cols-4"><div><div className="text-xs uppercase opacity-70">Statut</div><div className="mt-1 text-2xl font-black">{automationLabel(automation.status)}</div></div><div><div className="text-xs uppercase opacity-70">Agences à jour</div><div className="mt-1 text-2xl font-black">{automation.healthy||0}</div></div><div><div className="text-xs uppercase opacity-70">En retard</div><div className="mt-1 text-2xl font-black">{automation.stale||0}</div></div><div><div className="text-xs uppercase opacity-70">Sans snapshot</div><div className="mt-1 text-2xl font-black">{automation.missing||0}</div></div></div>{automation.latestCapturedAt?<div className="px-6 pb-5 text-sm opacity-80">Dernière capture réseau observée : {new Date(automation.latestCapturedAt).toLocaleString("fr-FR")}</div>:null}{automationIssues.length?<div className="border-t border-current/10 px-6 py-4"><div className="font-semibold">Agences à contrôler</div><div className="mt-2 flex flex-wrap gap-2">{automationIssues.map(row=><Link key={row.agency?.id} href={`/seo-cockpit/${row.agency?.id}`} className="rounded-full bg-white/70 px-3 py-1 text-sm font-semibold hover:underline">{row.agency?.name||`Agence #${row.agency?.id}`}{row.snapshotStatus?.status==="stale"&&row.snapshotStatus?.ageHours!=null?` · ${row.snapshotStatus.ageHours} h`:" · aucune capture"}</Link>)}</div></div>:null}</section>
<section className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 shadow-sm"><div className="border-b border-emerald-200 px-6 py-5"><h2 className="text-xl font-bold text-emerald-950">Paliers de santé SEO rapidement atteignables</h2><p className="mt-1 text-sm text-emerald-800">Agences pouvant franchir leur prochain palier avec un faible nombre de points à récupérer et des leviers déjà identifiés.</p></div><div className="divide-y divide-emerald-100">{quickWins.map(row=><div key={row.agency?.id} className="grid gap-4 px-6 py-4 lg:grid-cols-[1.2fr_0.7fr_0.7fr_1.2fr] lg:items-center"><div><Link href={`/seo-cockpit/${row.agency?.id}`} className="font-bold text-emerald-950 hover:underline">{row.agency?.name||`Agence #${row.agency?.id}`}</Link><div className="text-xs text-emerald-700">{row.agency?.city||""}</div></div><div><div className="text-xs text-emerald-700">Santé actuelle</div><div className="text-xl font-black text-emerald-950">{row.seoHealth?.score||0}/100</div></div><div><div className="text-xs text-emerald-700">Prochain palier</div><div className="text-xl font-black text-emerald-950">{row.seoHealthGoal?.target||"—"}/100</div></div><div className="text-sm text-emerald-900"><strong>+{row.seoHealthGoal?.requiredGain||0} points</strong> · {(row.seoHealthGoal?.recommendedSteps||[])[0]?.action?.title||"Levier identifié"}</div></div>)}{!quickWins.length?<div className="px-6 py-10 text-center text-emerald-800">Aucun palier rapide clairement atteignable actuellement.</div>:null}</div></section>
<section className="mt-6 rounded-2xl border bg-white shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-xl font-bold">Santé SEO des agences</h2></div><div className="divide-y">{rows.map(row=><div key={row.agency?.id} className="grid gap-4 px-6 py-4 md:grid-cols-[1.2fr_0.5fr_0.7fr_1fr]"><div><Link href={`/seo-cockpit/${row.agency?.id}`} className="font-bold">{row.agency?.name||`Agence #${row.agency?.id}`}</Link><div className="text-xs text-slate-500">{row.agency?.city||""}</div></div><div><div className="text-2xl font-black">{row.seoHealth?.score||0}</div><span className={`rounded-full px-2 py-1 text-xs font-bold ${healthClass(row.seoHealth?.status)}`}>{row.seoHealth?.grade||"—"}</span></div><div className="text-sm"><div className="text-slate-500">Palier</div><strong>{row.seoHealthGoal?.current??row.seoHealth?.score??0} → {row.seoHealthGoal?.target??"—"}</strong><div className="text-xs text-slate-500">+{row.seoHealthGoal?.requiredGain??0} points</div></div><div className="text-sm text-slate-600">{(row.seoHealth?.components||[]).sort((a,b)=>a.ratio-b.ratio).slice(0,2).map(c=><div key={c.code}>{c.label}: {Math.round(Number(c.ratio||0)*100)} %</div>)}</div></div>)}</div></section>
<section className="mt-6 rounded-2xl border bg-white shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-xl font-bold">Évolution de la visibilité réseau</h2></div><div className="grid gap-4 p-6 md:grid-cols-3">{trendWindows.map(w=><div key={w.days} className="rounded-xl border bg-slate-50 p-4"><strong>Sur {w.days} jours</strong><div className="mt-3 text-sm">Top 10: {w.top10Delta==null?"—":w.top10Delta>0?`+${w.top10Delta}`:w.top10Delta} · Top 20: {w.top20Delta==null?"—":w.top20Delta>0?`+${w.top20Delta}`:w.top20Delta}</div></div>)}</div></section>
<section className="mt-6 rounded-2xl border bg-white shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-xl font-bold">Actions SEO prioritaires</h2></div>{actions.map((a,n)=><div key={n} className="border-b px-6 py-4"><div className="text-xs font-bold uppercase text-orange-700">{a.priority}</div><strong>{a.agency?.name?`${a.agency.name} · `:""}{a.title}</strong><p className="text-sm text-slate-600">{a.detail}</p></div>)}</section>
</>}</MainLayout>}
