"use strict";
const express=require("express");
const {randomUUID}=require("node:crypto");
const CAMPAIGN={
 slug:"gloire-des-pharaons-2027", title:"Croisière Gloire des Pharaons 5★", destination:"Égypte",
 duration:"8 jours / 7 nuits", ship:"Caprice 5★ (ou similaire)", board:"Formule tout inclus",
 price:1070, currency:"EUR", partner:null, origins:["PARIS","LYON"],
 departures:["2027-01-02","2027-01-09","2027-01-16","2027-01-23","2027-01-30","2027-02-06"],
 included:["Transport France / Louxor / France","1 bagage en soute et 1 bagage à main","Taxes aéroport","Visa et frais de services obligatoires","Accueil et assistance","Transferts aéroport / bateau","Croisière 5★ normes locales","Formule tout inclus","Entrées et visites prévues au programme"],
 disclaimer:"Préinscription gratuite et sans engagement. La date définitive reste soumise à la constitution du groupe et à la disponibilité des places."
};
const buckets=new Map();
function clean(v,n=300){return String(v??"").trim().replace(/\s+/g," ").slice(0,n)}
function limited(req){const now=Date.now(),k=clean(req.headers["x-forwarded-for"]||req.ip||"unknown",100).split(",")[0];let b=buckets.get(k);if(!b||now-b.start>900000)b={start:now,count:0};b.count++;buckets.set(k,b);return b.count>10}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
function validate(body){const name=clean(body.name,120),email=clean(body.email,180).toLowerCase(),phone=clean(body.phone,50);if(clean(body.website,100))return"SPAM";if(name.length<2)return"INVALID_NAME";if(!validEmail(email))return"INVALID_EMAIL";if(phone&&phone.replace(/\D/g,"").length<8)return"INVALID_PHONE";const adults=Number(body.adults||0),children=Number(body.children||0),infants=Number(body.infants||0);if(adults<1||adults>20||children<0||children>20||infants<0||infants>20)return"INVALID_TRAVELLERS";const origins=Array.isArray(body.origins)?body.origins:[],dates=Array.isArray(body.departures)?body.departures:[];if(!origins.length||origins.some(x=>!CAMPAIGN.origins.includes(x)))return"INVALID_ORIGINS";if(!dates.length||dates.some(x=>!CAMPAIGN.departures.includes(x)))return"INVALID_DEPARTURES";if(body.preferredDeparture&&!dates.includes(body.preferredDeparture))return"INVALID_PREFERRED_DEPARTURE";if(!["HIGH","MEDIUM","INFO"].includes(body.intent))return"INVALID_INTENT";if(body.projectContactConsent!==true)return"PROJECT_CONTACT_CONSENT_REQUIRED";return null}
function routes({prisma}={}){const r=express.Router();
 r.get("/api/public/group-campaigns/:slug",(req,res)=>req.params.slug===CAMPAIGN.slug?res.json({ok:true,campaign:CAMPAIGN}):res.status(404).json({ok:false,error:"CAMPAIGN_NOT_FOUND"}));
 r.post("/api/public/group-campaigns/:slug/pre-register",async(req,res)=>{if(req.params.slug!==CAMPAIGN.slug)return res.status(404).json({ok:false,error:"CAMPAIGN_NOT_FOUND"});if(limited(req))return res.status(429).json({ok:false,error:"RATE_LIMITED"});const err=validate(req.body||{});if(err==="SPAM")return res.status(202).json({ok:true});if(err)return res.status(400).json({ok:false,error:err});if(!prisma)return res.status(503).json({ok:false,error:"PERSISTENCE_UNAVAILABLE"});try{const b=req.body,id="gpr_"+randomUUID().replaceAll("-",""),source=clean(b.source,120)||null,total=Number(b.adults||0)+Number(b.children||0)+Number(b.infants||0);const dup=await prisma.$queryRawUnsafe('SELECT "id" FROM "GroupPreRegistration" WHERE "campaignSlug"=$1 AND lower("email")=$2 AND "createdAt">NOW()-INTERVAL \'15 minutes\' LIMIT 1',CAMPAIGN.slug,clean(b.email,180).toLowerCase());if(dup[0])return res.json({ok:true,id:dup[0].id,duplicate:true});await prisma.$executeRawUnsafe('INSERT INTO "GroupPreRegistration" ("id","campaignSlug","name","email","phone","adults","children","infants","travellerCount","origins","departures","preferredDeparture","intent","source","emailMarketingConsent","projectContactConsent","consentVersion","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11::jsonb,$12,$13,$14,$15,$16,$17,NOW(),NOW())',id,CAMPAIGN.slug,clean(b.name,120),clean(b.email,180).toLowerCase(),clean(b.phone,50)||null,Number(b.adults||0),Number(b.children||0),Number(b.infants||0),total,JSON.stringify(b.origins),JSON.stringify(b.departures),b.preferredDeparture||null,b.intent,source,b.emailMarketingConsent===true,true,"2026-09-groups-v1");return res.status(201).json({ok:true,id,duplicate:false,travellerCount:total})}catch(e){console.error("[group-pre-registration]",e);return res.status(500).json({ok:false,error:"GROUP_PRE_REGISTRATION_FAILED"})}});
 r.get("/api/group-campaigns/:slug/pre-registrations",async(req,res)=>{if(req.params.slug!==CAMPAIGN.slug)return res.status(404).json({ok:false,error:"CAMPAIGN_NOT_FOUND"});try{const rows=await prisma.$queryRawUnsafe('SELECT "id","name","email","phone","adults","children","infants","travellerCount","origins","departures","preferredDeparture","intent","source","createdAt" FROM "GroupPreRegistration" WHERE "campaignSlug"=$1 ORDER BY "createdAt" DESC',CAMPAIGN.slug);return res.json({ok:true,items:rows})}catch(e){return res.status(500).json({ok:false,error:"GROUP_PRE_REGISTRATIONS_FAILED"})}});
 r.get("/api/group-campaigns/:slug/analytics",async(req,res)=>{if(req.params.slug!==CAMPAIGN.slug)return res.status(404).json({ok:false,error:"CAMPAIGN_NOT_FOUND"});try{const rows=await prisma.$queryRawUnsafe('SELECT "origins","departures","preferredDeparture","intent","travellerCount","source" FROM "GroupPreRegistration" WHERE "campaignSlug"=$1',CAMPAIGN.slug);const dates=Object.fromEntries(CAMPAIGN.departures.map(d=>[d,{travellers:0,highIntent:0,preferred:0,paris:0,lyon:0}]));for(const x of rows){for(const d of x.departures||[]){if(!dates[d])continue;dates[d].travellers+=x.travellerCount;if(x.intent==="HIGH")dates[d].highIntent+=x.travellerCount;if(x.preferredDeparture===d)dates[d].preferred+=x.travellerCount;if((x.origins||[]).includes("PARIS"))dates[d].paris+=x.travellerCount;if((x.origins||[]).includes("LYON"))dates[d].lyon+=x.travellerCount}}return res.json({ok:true,registrations:rows.length,dates})}catch(e){return res.status(500).json({ok:false,error:"GROUP_ANALYTICS_FAILED"})}});return r}
module.exports={CAMPAIGN,routes};
