"use strict";

export const PARTNER_STAY_LOGO_SOURCES = Object.freeze({
  belambra: { status: "permission-review", sourceType: "brand-permission", sourcePage: "https://www.belambra.fr/mentions-legales", preferredSource: null, targetAsset: "/partners/belambra.webp", note: "Belambra's official legal notice requires prior written authorisation for reproduction/use of logos and marks. Do not ingest automatically." },
  boomerang: { status: "official-source-page", sourceType: "official-site", sourcePage: "https://www.boomerang-voyages.com/", preferredSource: null, targetAsset: "/partners/boomerang.webp", note: "Official brand site confirmed. Acquire only the Boomerang Voyages masterbrand, not Kappa Club, Coralia or Eldorador sub-brands." },
  "jet-tours": { status: "official-source-page", sourceType: "official-site", sourcePage: "https://www.jettours.com/", preferredSource: null, targetAsset: "/partners/jet-tours.webp", note: "Official Jet tours site confirmed. Acquire only the Jet tours masterbrand; do not substitute Club Jet tours or other club/sub-brand marks." },
  "hotels-lagons": { status: "official-source-page", sourceType: "official-site", sourcePage: "https://www.hotels-lagons.com/", preferredSource: null, targetAsset: "/partners/hotels-lagons.webp", note: "Official B2B brand site confirmed. Acquire only the Hôtels & Lagons masterbrand, not an individual hotel or island supplier identity." },
  "lmx-voyages": { status: "official-source-page", sourceType: "official-site", sourcePage: "https://lmx-voyages.fr/", preferredSource: null, targetAsset: "/partners/lmx-voyages.webp", note: "Official French LMX Voyages site confirmed. Use the LMX Voyages French-market masterbrand rather than a generic LMX group or agent-tool mark." },
  "mondial-tourisme": { status: "permission-review", sourceType: "site-terms-restriction", sourcePage: "https://www.mondialtourisme.fr/fr/conditions-generales-d-utilisation", preferredSource: null, targetAsset: "/partners/mondial-tourisme.webp", note: "Mondial Tourisme's official site terms state that site elements may not be reused or exploited for one's own account. Keep the partner publishable, but hold logo ingestion until an authorised brand asset or explicit permission is available." },
  "plein-vent": { status: "permission-review", sourceType: "brand-permission", sourcePage: "https://multimedia.fram.fr/information/pleinvent/mentions-legales.pdf", preferredSource: null, targetAsset: "/partners/plein-vent.webp", note: "Plein Vent's official legal notice states that reproduction or representation of the marks and logos shown on its site requires the express authorisation of the rights holder. Keep the partner publishable, but do not ingest its logo automatically." },
  solea: { status: "official-source-page", sourceType: "official-site", sourcePage: "https://www.solea-voyages.fr/", preferredSource: null, targetAsset: "/partners/solea.webp", note: "Official brand site confirmed. Master logo asset still needs vetting before ingestion." },
  "pacha-tours": { status: "official-source-page", sourceType: "official-site", sourcePage: "https://www.pachatours.fr/", preferredSource: null, targetAsset: "/partners/pacha-tours.webp", note: "Official brand site confirmed. Master logo asset still needs vetting before ingestion." },
  heliades: { status: "permission-review", sourceType: "brand-permission", sourcePage: "https://www.heliades.fr/vacances/conditions-generales-utilisations", preferredSource: null, targetAsset: "/partners/heliades.webp", note: "Héliades' official terms prohibit reproduction of its marks and logos without express authorisation. Do not ingest automatically." },
  voyamar: { status: "permission-review", sourceType: "brand-permission", sourcePage: "https://www.voyamar-vacances.com/vacances/conditions-generales-utilisations", preferredSource: null, targetAsset: "/partners/voyamar.webp", note: "Voyamar's official terms prohibit reproduction of its marks and logos without express authorisation. Do not ingest automatically." },
  "travel-evasion": { status: "official-source-page", sourceType: "official-site", sourcePage: "https://www.travelevasion.fr/", preferredSource: null, targetAsset: "/partners/travel-evasion.webp", note: "Official Travel Evasion site and B2B portal confirm the tour-operator identity. Source only the Travel Evasion masterbrand, not Mon French Club or product artwork." },
});

export function getStayLogoSource(partnerId) {
  return PARTNER_STAY_LOGO_SOURCES[String(partnerId || "").trim()] || null;
}
