import Link from "next/link";
import MainLayout from "../../components/MainLayout";

export const dynamic="force-dynamic";
function origin(){return String(process.env.BACKEND_INTERNAL_URL||process.env.API_INTERNAL_URL||"http://backend:4000").replace(/\/+$/g,"")}
async function load(){const r=await fetch(`${origin()}/api/presence/network/provider-matrix`,{headers:{Accept:"application/json","x-tenant-slug":process.env.NEXT_PUBLIC_TENANT_SLUG||"mondescale"},cache:"no-store"});if(!r.ok)throw new Error(`Matrice Presence HTTP ${r.status}: ${await r.text()}`);return r.json()}
function cellClass(row){if(row.status==="validated")return "bg-emerald-50 text-emerald-900 border-emerald-200";if(row.operationalMode==="blocked")return "bg-red-50 text-red-900 border-red-200";if(row.operationalMode==="manual")return "bg-amber-50 text-amber-900 border-amber-200";if(row.operationalMode==="monitor")return "bg-slate-50 text-slate-700 border-slate-200";return "bg-cyan-50 text-cyan-900 border-cyan-200"}
function label(row){if(row.status==="validated")return "Conforme";if(row.operationalMode==="blocked")return "Bloqué";if(row.operationalMode==="manual")return "Manuel";if(row.operationalMode==="monitor")return "Surveillance";return row.automationEligible?"Automatisable":"À traiter"}
export default async function Page(){let data,error;try{data=await load()}catch(e){error=e}const rows=data?.rows||[],summary=data?.summary||{},providers=[...new Map(rows.map(r=>[r.providerKey,{key:r.providerKey,name:r.directoryName}])).values()],agencies=[...new Map(rows.map(r=>[r.agencyId,{id:r.agencyId,name:r.agencyName}])).values()];const byKey=new Map(rows.map(r=>[`${r.agencyId}:${r.providerKey}`,r]));return <MainLayout title="Matrice Presence" subtitle="Couverture réseau par agence et par provider, avec mode opératoire réel.">{error?<div className="rounded-2xl bg-red-50 p-5 text-red-900">{error.message}</div>:<><div className="grid grid-cols-2 gap-4 md:grid-cols-6"><div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">Cellules</div><div className="text-2xl font-black">{summary.cells||0}</div></div><div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">Conformes</div><div className="text-2xl font-black">{summary.validated||0}</div></div><div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">Automatisables</div><div className="text-2xl font-black">{summary.automationEligible||0}</div></div><div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">Manuelles</div><div className="text-2xl font-black">{summary.manual||0}</div></div><div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">Surveillance</div><div className="text-2xl font-black">{summary.monitorOnly||0}</div></div><div className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">Bloquées</div><div className="text-2xl font-black">{summary.blocked||0}</div></div></div><section className="mt-6 overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="min-w-full border-collapse text-sm"><thead><tr className="bg-slate-50"><th className="sticky left-0 z-10 border-b bg-slate-50 px-4 py-3 text-left">Agence</th>{providers.map(p=><th key={p.key} className="border-b px-3 py-3 text-left">{p.name}</th>)}</tr></thead><tbody>{agencies.map(a=><tr key={a.id} className="border-b last:border-b-0"><td className="sticky left-0 bg-white px-4 py-3 font-bold">{a.name}</td>{providers.map(p=>{const r=byKey.get(`${a.id}:${p.key}`);return <td key={p.key} className="px-3 py-3">{r?<Link href={`/presence/agencies/${a.id}/providers/${p.key}`} className={`block rounded-lg border px-3 py-2 ${cellClass(r)}`}><div className="font-bold">{label(r)}</div><div className="mt-1 text-xs opacity-75">{r.status}</div></Link>:<span className="text-slate-300">—</span>}</td>})}</tr>)}</tbody></table></section></>}</MainLayout>}
