"use client";
import {useMemo,useState} from "react";import styles from "./SmartQuoteRequest.module.css";
const PROJECTS=[{id:"leisure",label:"Voyage & vacances",hint:"Séjour, circuit, croisière ou voyage sur mesure"},{id:"group",label:"Voyage en groupe",hint:"Association, CSE, famille, amis, club ou scolaire"},{id:"business",label:"Business Travel",hint:"Déplacements professionnels et politique voyages"}];
function initialProject(s){return s==="group"?"group":s==="business"?"business":"leisure"}function agencyCity(s){return String(s?.agency?.city||s?.city||"").trim()}
function leadAttribution(){if(typeof window==="undefined")return{};const current=new URL(window.location.href),params=current.searchParams;const referrer=String(document.referrer||"");let sourcePage="",refParams=null;if(referrer)try{const ref=new URL(referrer);sourcePage=ref.origin===current.origin?`${ref.pathname}${ref.search}`:ref.hostname;refParams=ref.searchParams}catch{}const pick=k=>params.get(k)||refParams?.get(k)||"";return{sourcePage,sourcePath:`${current.pathname}${current.search}`,sourceReferrer:referrer,utmSource:pick("utm_source"),utmMedium:pick("utm_medium"),utmCampaign:pick("utm_campaign"),utmContent:pick("utm_content"),utmTerm:pick("utm_term")}}
export default function SmartQuoteRequest({site,source="general"}){const city=agencyCity(site),[project,setProject]=useState(initialProject(source)),[state,setState]=useState("idle"),[error,setError]=useState("");const projectLabel=useMemo(()=>PROJECTS.find(x=>x.id===project)?.label||"Projet de voyage",[project]);
async function submit(e){e.preventDefault();if(state==="sending")return;setState("sending");setError("");const f=new FormData(e.currentTarget),v=Object.fromEntries(f.entries());try{const r=await fetch("/api/public-leads",{method:"POST",headers:{"content-type":"application/json","x-requested-with":"MondescaleLeadForm"},body:JSON.stringify({project,source,siteSlug:site?.slug||"",...leadAttribution(),destination:v.destination,dates:v.dates,travellers:v.travellers,budget:v.budget,wishes:v.wishes,name:v.name,phone:v.phone,email:v.email,website:v.website})});const p=await r.json();if(!r.ok||!p.ok)throw new Error(p.error||"SEND_FAILED");setState("sent");e.currentTarget.reset();}catch{setState("error");setError("Votre demande n’a pas pu être enregistrée. Merci de réessayer ou de contacter directement votre agence.")}}
return <section className={styles.section} id="demande-devis"><div className={`public-site-container ${styles.shell}`}><div className={styles.intro}><p className="public-site-section-kicker">Votre projet commence ici</p><h2>Parlez-nous de votre prochain voyage</h2><p>Quelques informations suffisent pour permettre à votre conseiller{city?` à ${city}`:""} de comprendre votre projet et de revenir vers vous avec une réponse réellement adaptée.</p><div className={styles.promise}><strong>Une demande courte, un échange humain.</strong><span>Nous vous demandons uniquement les éléments utiles pour préparer le premier échange.</span></div></div><form className={styles.form} onSubmit={submit}><input name="website" tabIndex="-1" autoComplete="off" aria-hidden="true" style={{position:"absolute",left:"-10000px"}} />
<fieldset className={styles.projectPicker}><legend>Quel voyage préparez-vous ?</legend><div className={styles.projectGrid}>{PROJECTS.map(i=><label className={project===i.id?styles.projectActive:styles.project} key={i.id}><input type="radio" name="project" value={i.id} checked={project===i.id} onChange={()=>setProject(i.id)}/><strong>{i.label}</strong><span>{i.hint}</span></label>)}</div></fieldset>
<div className={styles.fields}><label><span>{project==="business"?"Votre entreprise / organisation":"Où souhaitez-vous partir ?"}</span><input name="destination" required maxLength="240" placeholder={project==="business"?"Nom de l’entreprise ou destinations habituelles":"Une destination, une région… ou simplement une envie"}/></label><label><span>Quand souhaitez-vous partir ?</span><input name="dates" required maxLength="160" placeholder="Dates précises ou période flexible"/></label><label><span>{project==="group"?"Combien de participants ?":project==="business"?"Combien de voyageurs sont concernés ?":"Combien de voyageurs ?"}</span><input name="travellers" required maxLength="120" placeholder={project==="group"?"Ex. 24 adultes":"Ex. 2 adultes et 2 enfants"}/></label><label><span>{project==="business"?"Budget ou cadre de votre politique voyages":"Quel budget souhaitez-vous consacrer au projet ?"}</span><input name="budget" maxLength="160" placeholder={project==="group"?"Budget par personne ou budget global":"Une fourchette suffit"}/></label><label className={styles.full}><span>{project==="business"?"Quels sont vos besoins prioritaires ?":"Qu’est-ce qui rendrait ce voyage réussi pour vous ?"}</span><textarea name="wishes" maxLength="2500" rows="4" placeholder={project==="business"?"Réservations, assistance, reporting, paiement centralisé, contraintes internes…":"Ambiance, rythme, hébergement, expériences indispensables, contraintes particulières…"}/></label></div>
<div className={styles.identity}><label><span>Votre nom</span><input name="name" autoComplete="name" required maxLength="120"/></label><label><span>Votre téléphone</span><input name="phone" type="tel" autoComplete="tel" required maxLength="50"/></label><label><span>Votre e-mail</span><input name="email" type="email" autoComplete="email" required maxLength="180"/></label></div><div className={styles.submitRow}><div><strong>Votre demande sera adressée à votre agence{city?` de ${city}`:""}.</strong><span>Vos coordonnées sont utilisées uniquement pour répondre à votre projet.</span></div><button className="public-site-button" type="submit" disabled={state==="sending"}>{state==="sending"?"Envoi en cours…":"Envoyer mon projet"}</button></div>{state==="sent"?<p className={styles.sent}>Merci. Votre demande a bien été enregistrée. Votre agence reviendra vers vous pour poursuivre votre projet.</p>:null}{error?<p className={styles.sent} role="alert">{error}</p>:null}</form></div></section>}
export{PROJECTS,agencyCity,initialProject,leadAttribution};
