"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const { stageTargetAgencyCount, campaignAgencyCount, campaignProvenance, recoveryEvidenceStillValid, frozenPreflightTrustBindingClean } = require("./network-rollout-gate");

test("progressive rollout targets ceil of network percentage",()=>{assert.equal(stageTargetAgencyCount(9,25),3);assert.equal(stageTargetAgencyCount(9,50),5);assert.equal(stageTargetAgencyCount(9,100),9);});
test("campaign agency count deduplicates approved scope",()=>{assert.equal(campaignAgencyCount({approvedScope:{agencyIds:[1,2,2,3]}}),3);});
test("rollout evidence provenance distinguishes native recovery and regenerated proofs",()=>{assert.equal(campaignProvenance({approvedScope:{}}).kind,"native");assert.equal(campaignProvenance({approvedScope:{recoveryOfCampaignId:"failed-1"}}).kind,"recovery");assert.equal(campaignProvenance({approvedScope:{regenerationOfCampaignId:"legacy-1",regenerationReason:"legacy_evidence_incompatible"}}).kind,"regenerated");assert.equal(campaignProvenance({approvedScope:{regenerationOfCampaignId:"legacy-1",recoveryOfCampaignId:"failed-1"}}).kind,"regenerated_recovery");});
test("frozen rollout proof requires matching preflight recovery trust binding",()=>{const campaign={preflightId:"pf-1",approvedScope:{preflightRecoveryTrustFingerprint:"fp-1"}};const good={report:{pilotEvidence:{preflightId:"pf-1",preflightRecoveryTrustFingerprint:"fp-1",preflightRecoveryTrustBinding:{ready:true,expected:"fp-1",current:"fp-1"}}}};assert.equal(frozenPreflightTrustBindingClean(campaign,good),true);assert.equal(frozenPreflightTrustBindingClean(campaign,{report:{pilotEvidence:{preflightId:"pf-1"}}}),false);assert.equal(frozenPreflightTrustBindingClean(campaign,{report:{pilotEvidence:{preflightId:"pf-1",preflightRecoveryTrustFingerprint:"fp-2",preflightRecoveryTrustBinding:{ready:true,expected:"fp-2",current:"fp-2"}}}}),false);});
test("ordinary rollout campaign has no recovery evidence constraint",async()=>{const gate=await recoveryEvidenceStillValid({}, {approvedScope:{}}, {report:{}});assert.equal(gate.ready,true);});
test("stale recovery stabilization cannot promote a completed recovery campaign",async()=>{const evidence=[{id:1,eventType:"recovery_qualification",status:"already_applied",operationId:"op",agencyId:1,payload:{sourceCampaignId:"failed-1",campaignIndex:0},result:{classification:"already_applied"},createdAt:new Date("2026-08-26T08:00:00Z")}];const prisma={$queryRaw:async(strings)=>{const sql=Array.isArray(strings)?strings.join(" "):String(strings);if(sql.includes("recovery_stabilization_snapshot"))return[{id:2,operationId:"snap-old",status:"ready",payload:{sourceCampaignId:"failed-1"},result:{snapshotId:"snap-old",evidenceSignature:"old-signature"},createdAt:new Date("2026-08-26T08:05:00Z")}];return evidence;}};const campaign={approvedScope:{recoveryOfCampaignId:"failed-1",recoveryStabilizationSnapshotId:"snap-old",recoveryStabilizationEvidenceSignature:"old-signature"}};const frozen={report:{pilotEvidence:{recoveryEvidence:{sourceCampaignId:"failed-1",stabilizationSnapshotId:"snap-old",stabilizationEvidenceSignature:"old-signature"}}}};const gate=await recoveryEvidenceStillValid(prisma,campaign,frozen);assert.equal(gate.ready,false);assert.ok(gate.blockers.includes("recovery_stabilization_snapshot_stale"));});
