"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const {buildGovernancePolicy,buildRolloutDecisionSnapshot,buildAcknowledgement,listCriticalRolloutAcknowledgements}=require("./network-rollout-decision-snapshot");

test("rollout decision snapshot preserves provenance blockers and governance policy",()=>{const previous=process.env.PRESENCE_ACK_SEALING_MIN_PERCENT;process.env.PRESENCE_ACK_SEALING_MIN_PERCENT="80";try{const snapshot=buildRolloutDecisionSnapshot({ready:false,decision:"no_go",nextStagePercent:50,maxAgencies:5,blockers:["blocked"],stages:[{stagePercent:25,campaignId:"c1",agencyCount:3,reportId:"r1",reportCreatedAt:"2026-08-27T00:00:00Z",provenance:"regenerated_recovery",regenerationOfCampaignId:"legacy",recoveryOfCampaignId:"failed",regenerationReason:"legacy_evidence_incompatible"}]},{ready:true,decision:"go",summary:{total:2,healthy:2,blocked:0,critical:0}});assert.match(snapshot.snapshotId,/^rollout-decision-/);assert.equal(snapshot.decision,"no_go");assert.deepEqual(snapshot.blockers,["blocked"]);assert.equal(snapshot.stages[0].provenance,"regenerated_recovery");assert.equal(snapshot.stages[0].reportId,"r1");assert.equal(snapshot.recoveryTrust.critical,0);assert.equal(snapshot.governancePolicy.acknowledgementSealingMinPercent,80);assert.equal(snapshot.governancePolicy.version,1);}finally{if(previous===undefined)delete process.env.PRESENCE_ACK_SEALING_MIN_PERCENT;else process.env.PRESENCE_ACK_SEALING_MIN_PERCENT=previous;}});

test("governance policy defaults safely when threshold is absent",()=>{const previous=process.env.PRESENCE_ACK_SEALING_MIN_PERCENT;delete process.env.PRESENCE_ACK_SEALING_MIN_PERCENT;try{assert.equal(buildGovernancePolicy().acknowledgementSealingMinPercent,0);}finally{if(previous!==undefined)process.env.PRESENCE_ACK_SEALING_MIN_PERCENT=previous;}});

test("same rollout evidence yields stable snapshot identity",()=>{const gate={ready:true,decision:"go",nextStagePercent:50,maxAgencies:5,blockers:[],stages:[{stagePercent:25,campaignId:"c1",agencyCount:3,reportId:"r1",reportCreatedAt:"2026-08-27T00:00:00Z",provenance:"native"}]};const trust={ready:true,decision:"go",summary:{total:0,healthy:0,blocked:0,critical:0}};assert.equal(buildRolloutDecisionSnapshot(gate,trust).snapshotId,buildRolloutDecisionSnapshot(gate,trust).snapshotId);});

test("critical acknowledgement records decision acknowledgement and root lineage",()=>{const ack=buildAcknowledgement({acknowledgementRequired:true,acknowledgementSeverity:"critical",acknowledgementReason:"Incident réseau reconnu par exploitation",actorId:"presence-admin",previousSnapshotId:"rollout-decision-old",previousAcknowledgementSnapshotId:"rollout-decision-older-ack",rootAcknowledgementSnapshotId:"rollout-decision-root"});assert.equal(ack.required,true);assert.equal(ack.severity,"critical");assert.equal(ack.actor.type,"operator");assert.equal(ack.actor.id,"presence-admin");assert.equal(ack.actor.source,"presence_cockpit");assert.equal(ack.previousSnapshotId,"rollout-decision-old");assert.equal(ack.previousAcknowledgementSnapshotId,"rollout-decision-older-ack");assert.equal(ack.rootAcknowledgementSnapshotId,"rollout-decision-root");assert.match(ack.reason,/Incident réseau/);});

test("ordinary frozen decision does not invent acknowledgement lineage",()=>{const ack=buildAcknowledgement({});assert.equal(ack.actor.id,"presence_cockpit_operator");assert.equal(ack.actor.type,"operator");assert.equal(ack.previousSnapshotId,null);assert.equal(ack.previousAcknowledgementSnapshotId,null);assert.equal(ack.rootAcknowledgementSnapshotId,null);});

test("critical acknowledgement journal preserves full rollout state root and excludes ordinary frozen decisions",async()=>{const prisma={$queryRaw:async()=>[{id:2,status:"no_go",createdAt:new Date("2026-08-27T08:00:00Z"),result:{snapshotId:"new",decision:"no_go",ready:false,nextStagePercent:null,maxAgencies:0,blockers:["critical_recovery"],stages:[],recoveryTrust:{critical:1},governancePolicy:{acknowledgementSealingMinPercent:80,version:1},acknowledgement:{required:true,severity:"critical",reason:"Nouvel état critique reconnu",actor:{type:"operator",id:"presence-admin",source:"presence_cockpit"},previousSnapshotId:"old",previousAcknowledgementSnapshotId:"older-ack",rootAcknowledgementSnapshotId:"root-ack",chainVersion:1,recordedAt:"2026-08-27T08:00:00Z"}}},{id:1,status:"go",createdAt:new Date("2026-08-27T07:00:00Z"),result:{snapshotId:"old",decision:"go",ready:true,nextStagePercent:50,maxAgencies:5,acknowledgement:{required:false,severity:null,reason:null,actor:{type:"operator",id:"presence-admin",source:"presence_cockpit"},previousSnapshotId:null,recordedAt:"2026-08-27T07:00:00Z"}}}]};const rows=await listCriticalRolloutAcknowledgements(prisma,10);assert.equal(rows.length,1);assert.equal(rows[0].snapshotId,"new");assert.equal(rows[0].previousSnapshotId,"old");assert.equal(rows[0].previousAcknowledgementSnapshotId,"older-ack");assert.equal(rows[0].rootAcknowledgementSnapshotId,"root-ack");assert.equal(rows[0].ready,false);assert.equal(rows[0].nextStagePercent,null);assert.equal(rows[0].maxAgencies,0);assert.equal(rows[0].actor.id,"presence-admin");assert.equal(rows[0].governancePolicy.acknowledgementSealingMinPercent,80);assert.match(rows[0].reason,/critique reconnu/);});
