"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const {buildRolloutDecisionSnapshot,buildAcknowledgement}=require("./network-rollout-decision-snapshot");

test("rollout decision snapshot preserves provenance and blockers",()=>{const snapshot=buildRolloutDecisionSnapshot({ready:false,decision:"no_go",nextStagePercent:50,maxAgencies:5,blockers:["blocked"],stages:[{stagePercent:25,campaignId:"c1",agencyCount:3,reportId:"r1",reportCreatedAt:"2026-08-27T00:00:00Z",provenance:"regenerated_recovery",regenerationOfCampaignId:"legacy",recoveryOfCampaignId:"failed",regenerationReason:"legacy_evidence_incompatible"}]},{ready:true,decision:"go",summary:{total:2,healthy:2,blocked:0,critical:0}});assert.match(snapshot.snapshotId,/^rollout-decision-/);assert.equal(snapshot.decision,"no_go");assert.deepEqual(snapshot.blockers,["blocked"]);assert.equal(snapshot.stages[0].provenance,"regenerated_recovery");assert.equal(snapshot.stages[0].reportId,"r1");assert.equal(snapshot.recoveryTrust.critical,0);});

test("same rollout evidence yields stable snapshot identity",()=>{const gate={ready:true,decision:"go",nextStagePercent:50,maxAgencies:5,blockers:[],stages:[{stagePercent:25,campaignId:"c1",agencyCount:3,reportId:"r1",reportCreatedAt:"2026-08-27T00:00:00Z",provenance:"native"}]};const trust={ready:true,decision:"go",summary:{total:0,healthy:0,blocked:0,critical:0}};assert.equal(buildRolloutDecisionSnapshot(gate,trust).snapshotId,buildRolloutDecisionSnapshot(gate,trust).snapshotId);});

test("critical acknowledgement records logical actor and previous snapshot lineage",()=>{const ack=buildAcknowledgement({acknowledgementRequired:true,acknowledgementSeverity:"critical",acknowledgementReason:"Incident réseau reconnu par exploitation",actorId:"presence-admin",previousSnapshotId:"rollout-decision-old"});assert.equal(ack.required,true);assert.equal(ack.severity,"critical");assert.equal(ack.actor.type,"operator");assert.equal(ack.actor.id,"presence-admin");assert.equal(ack.actor.source,"presence_cockpit");assert.equal(ack.previousSnapshotId,"rollout-decision-old");assert.match(ack.reason,/Incident réseau/);});

test("acknowledgement uses explicit logical fallback instead of inventing a person",()=>{const ack=buildAcknowledgement({});assert.equal(ack.actor.id,"presence_cockpit_operator");assert.equal(ack.actor.type,"operator");assert.equal(ack.previousSnapshotId,null);});
