"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const{evaluateRolloutDecisionAcknowledgement,criticalAcknowledgementEvidenceValid,latestDistinctPair}=require("./rollout-decision-ack-gate");const{buildRolloutDecisionSnapshot}=require("./network-rollout-decision-snapshot");
function prismaWith(...snapshots){return{$queryRaw:async()=>snapshots.filter(Boolean).map((previous,index)=>({id:index+1,status:previous.decision,result:previous,createdAt:new Date(`2026-08-27T0${8-index}:00:00Z`)}))};}
function gate(overrides={}){return{ready:true,decision:"go",nextStagePercent:50,maxAgencies:5,blockers:[],stages:[],recoveryTrust:{ready:true,decision:"go",summary:{total:0,healthy:0,blocked:0,critical:0}},...overrides};}
function criticalGate(){return gate({ready:false,decision:"no_go",nextStagePercent:null,maxAgencies:0,blockers:["critical_recovery_trust_blocks_rollout"],recoveryTrust:{ready:false,decision:"no_go",summary:{total:1,healthy:0,blocked:1,critical:1}}});}
test("no frozen baseline does not block first promotion",async()=>{const result=await evaluateRolloutDecisionAcknowledgement(prismaWith(),gate());assert.equal(result.ready,true);assert.equal(result.required,false);});
test("critical drift blocks until current decision is frozen",async()=>{const old={snapshotId:"rollout-decision-old",decision:"go",ready:true,nextStagePercent:50,maxAgencies:5,blockers:[],stages:[],recoveryTrust:{critical:0}};const result=await evaluateRolloutDecisionAcknowledgement(prismaWith(old),criticalGate());assert.equal(result.ready,false);assert.equal(result.drift.severity,"critical");assert.ok(result.blockers.includes("critical_rollout_decision_drift_unacknowledged"));});
test("matching frozen decision without acknowledgement evidence is rejected",async()=>{const currentGate=criticalGate();const frozen={...buildRolloutDecisionSnapshot(currentGate,currentGate.recoveryTrust),acknowledgement:{required:false,severity:null,reason:null,actor:{type:"operator",id:"presence-admin"},previousSnapshotId:null}};const old={snapshotId:"rollout-decision-old",decision:"go",ready:true,nextStagePercent:50,maxAgencies:5,blockers:[],stages:[],recoveryTrust:{critical:0}};const result=await evaluateRolloutDecisionAcknowledgement(prismaWith(frozen,old),currentGate);assert.equal(result.ready,false);assert.ok(result.blockers.includes("critical_rollout_decision_acknowledgement_evidence_invalid"));});
test("matching frozen decision with complete acknowledgement evidence reopens acknowledgement gate",async()=>{const currentGate=criticalGate();const base=buildRolloutDecisionSnapshot(currentGate,currentGate.recoveryTrust);const old={snapshotId:"rollout-decision-old",decision:"go",ready:true,nextStagePercent:50,maxAgencies:5,blockers:[],stages:[],recoveryTrust:{critical:0}};const frozen={...base,acknowledgement:{required:true,severity:"critical",reason:"Incident critique reconnu explicitement",actor:{type:"operator",id:"presence-admin",source:"presence_cockpit"},previousSnapshotId:"rollout-decision-old"}};const result=await evaluateRolloutDecisionAcknowledgement(prismaWith(frozen,old),currentGate);assert.equal(result.ready,true);assert.equal(result.acknowledgementEvidenceValid,true);assert.equal(result.drift.changed,false);});
test("critical acknowledgement evidence requires exact previous snapshot binding",()=>{const old={snapshotId:"old",decision:"go",ready:true,recoveryTrust:{critical:0}};const latest={snapshotId:"new",decision:"no_go",ready:false,recoveryTrust:{critical:1},acknowledgement:{required:true,severity:"critical",reason:"Incident critique reconnu explicitement",actor:{type:"operator",id:"presence-admin"},previousSnapshotId:"other"}};assert.equal(criticalAcknowledgementEvidenceValid(latest,old),false);});
test("duplicate snapshot rows cannot hide the prior distinct critical transition",async()=>{const currentGate=criticalGate();const base=buildRolloutDecisionSnapshot(currentGate,currentGate.recoveryTrust);const old={snapshotId:"rollout-decision-old",decision:"go",ready:true,nextStagePercent:50,maxAgencies:5,blockers:[],stages:[],recoveryTrust:{critical:0}};const duplicate={...base,acknowledgement:{required:false,severity:null,reason:null,actor:{type:"operator",id:"presence-admin"},previousSnapshotId:null}};const pair=latestDistinctPair([duplicate,{...duplicate},old]);assert.equal(pair.prior.snapshotId,"rollout-decision-old");const result=await evaluateRolloutDecisionAcknowledgement(prismaWith(duplicate,{...duplicate},old),currentGate);assert.equal(result.ready,false);assert.ok(result.blockers.includes("critical_rollout_decision_acknowledgement_evidence_invalid"));});
