"use strict";

const assert=require("node:assert/strict");
const test=require("node:test");
const {evaluateSourceEvidenceBinding,sameTimestamp,appendRecoveryTrustBlockers,appendDecisionAcknowledgementBlockers,compactAcknowledgementChainDiagnostic}=require("./rollout-promotion-gate");

test("source evidence timestamp comparison is stable across equivalent date representations",()=>{assert.equal(sameTimestamp("2026-08-25T10:00:00.000Z",new Date("2026-08-25T10:00:00Z")),true);assert.equal(sameTimestamp("2026-08-25T10:00:00.000Z","2026-08-25T10:00:01.000Z"),false);});
test("canary campaign requires no predecessor evidence",async()=>{const gate=await evaluateSourceEvidenceBinding({}, {pilot:true,approvedScope:{agencyIds:[1],maxItems:1,rolloutStage:null,sourceEvidenceCampaignId:null}},9);assert.equal(gate.ready,true);assert.equal(gate.required,false);});
test("promoted campaign is blocked when frozen source report is missing",async()=>{const prisma={$queryRaw:async()=>[]};const campaign={pilot:true,approvedScope:{agencyIds:[1,2,3],maxItems:3,rolloutStage:null,sourceEvidenceCampaignId:"canary-1",sourceEvidenceReportId:"report-1",sourceEvidenceReportCreatedAt:"2026-08-25T10:00:00.000Z"}};const gate=await evaluateSourceEvidenceBinding(prisma,campaign,9);assert.equal(gate.ready,false);assert.ok(gate.blockers.includes("source_evidence_frozen_report_missing"));assert.ok(gate.blockers.includes("source_canary_no_longer_authorized"));});
test("global critical recovery trust blockers are preserved in final promotion diagnostics",()=>{const blockers=[];appendRecoveryTrustBlockers(blockers,{recoveryTrust:{rolloutBlockers:["critical_recovery_trust_blocks_rollout","critical_recovery:r1"]}});assert.deepEqual(blockers,["critical_recovery_trust_blocks_rollout","critical_recovery:r1"]);});
test("acknowledgement lifecycle and chain blockers are preserved in final promotion diagnostics",()=>{const blockers=[];appendDecisionAcknowledgementBlockers(blockers,{blockers:["obsolete_rollout_decision_acknowledgement","critical_rollout_acknowledgement_replacement_chain_invalid","critical_rollout_acknowledgement_chain_fork_detected","critical_rollout_acknowledgement_chain_root_mismatch"]});assert.deepEqual(blockers,["obsolete_rollout_decision_acknowledgement","critical_rollout_acknowledgement_replacement_chain_invalid","critical_rollout_acknowledgement_chain_fork_detected","critical_rollout_acknowledgement_chain_root_mismatch"]);});
test("acknowledgement chain sealing progress is compacted into final promotion diagnostics",()=>{const diagnostic=compactAcknowledgementChainDiagnostic({acknowledgementChainAudit:{ready:true,versioned:true,rootSnapshotId:"ack-root",rootProofMode:"mixed_legacy_explicit",depth:3,roots:["ack-root"],missingParents:[],cycles:[],forks:[],rootMismatches:[],missingRootDeclarations:["ack-root","ack-2"],explicitRootDeclarations:1,legacyRootDeclarations:2,explicitCoveragePercent:33,fullyExplicit:false,latestRootExplicit:true,sealedFromSnapshotId:"ack-3"}});assert.equal(diagnostic.ready,true);assert.equal(diagnostic.rootSnapshotId,"ack-root");assert.equal(diagnostic.rootProofMode,"mixed_legacy_explicit");assert.equal(diagnostic.explicitCoveragePercent,33);assert.equal(diagnostic.fullyExplicit,false);assert.equal(diagnostic.latestRootExplicit,true);assert.equal(diagnostic.sealedFromSnapshotId,"ack-3");assert.deepEqual(diagnostic.missingRootDeclarations,["ack-root","ack-2"]);});
