const express = require("express");
const MAP={countries:"country",regions:"region",cities:"city",themes:"theme","travel-types":"travelType",tags:"tag"};
const clean=(v)=>Object.fromEntries(Object.entries(v||{}).filter(([,x])=>x!==undefined));
module.exports=function createKnowledgeGraphRoutes(prisma){const r=express.Router();
r.get("/knowledge/health",async(_q,res,next)=>{try{const [countries,regions,cities,themes,travelTypes,tags]=await Promise.all([prisma.country.count(),prisma.region.count(),prisma.city.count(),prisma.theme.count(),prisma.travelType.count(),prisma.tag.count()]);res.json({ok:true,version:"0.9.0",counts:{countries,regions,cities,themes,travelTypes,tags}})}catch(e){next(e)}});
for(const [path,model] of Object.entries(MAP)){r.get(`/knowledge/${path}`,async(q,res,next)=>{try{res.json(await prisma[model].findMany({where:q.query.status?{status:String(q.query.status)}:{},orderBy:{name:"asc"},take:Math.min(Number(q.query.limit)||200,500)}))}catch(e){next(e)}});r.post(`/knowledge/${path}`,async(q,res,next)=>{try{res.status(201).json(await prisma[model].create({data:clean(q.body)}))}catch(e){next(e)}});r.patch(`/knowledge/${path}/:id`,async(q,res,next)=>{try{res.json(await prisma[model].update({where:{id:q.params.id},data:clean(q.body)}))}catch(e){next(e)}})}
r.get("/public/knowledge/countries",async(_q,res,next)=>{try{res.json(await prisma.country.findMany({where:{status:"published"},include:{regions:{where:{status:"published"}},cities:{where:{status:"published"}}},orderBy:{name:"asc"}}))}catch(e){next(e)}});
r.get("/public/knowledge/taxonomies",async(_q,res,next)=>{try{const [themes,travelTypes,tags]=await Promise.all([prisma.theme.findMany({where:{status:"published"},orderBy:{name:"asc"}}),prisma.travelType.findMany({where:{status:"published"},orderBy:{name:"asc"}}),prisma.tag.findMany({where:{status:"active"},orderBy:{name:"asc"}})]);res.json({themes,travelTypes,tags})}catch(e){next(e)}});
r.get("/public/knowledge/destinations/:slug",async(q,res,next)=>{try{const x=await prisma.destination.findFirst({where:{slug:q.params.slug,status:"published"},include:{countryRef:true,regionRef:true,cityRef:true,themes:{include:{theme:true},orderBy:{weight:"desc"}},travelTypes:{include:{travelType:true},orderBy:{weight:"desc"}},tags:{include:{tag:true}},sections:{orderBy:{position:"asc"}},faqs:{orderBy:{position:"asc"}}}});if(!x)return res.status(404).json({error:"Destination introuvable"});res.json(x)}catch(e){next(e)}});return r};
