"use strict";
const express=require("express");
const STAGES=new Set(["NEW","TO_CONTACT","IN_PROGRESS","WON","LOST"]);
const PRIORITIES=new Set(["LOW","NORMAL","HIGH","URGENT"]);
const LOST_REASONS=new Set(["PRICE","NO_RESPONSE","COMPETITOR","PROJECT_CANCELLED","NOT_QUALIFIED","OTHER"]);
const clean=(v,n=500)=>String(v??"").trim().replace(/\s+/g," ").slice(0,n);
const valid=id=>/^lead_[a-z0-9]+$/.test(id);
function createLeadPipelineRoutes(prisma){const r=express.Router();
r.patch("/api/leads/:id/pipeline",async(req,res)=>{const id=clean(req.params.id,120),stage=clean(req.body?.stage,30).toUpperCase(),priority=clean(req.body?.priority,20).toUpperCase()||null,lostReason=clean(req.body?.lostReason,40).toUpperCase()||null;if(!valid(id))return res.status(400).json({ok:false,error:"INVALID_LEAD_ID"});if(!STAGES.has(stage))return res.status(400).json({ok:false,error:"INVALID_PIPELINE_STAGE"});if(priority&&!PRIORITIES.has(priority))return res.status(400).json({ok:false,error:"INVALID_PRIORITY"});if(stage==="LOST"&&!LOST_REASONS.has(lostReason))return res.status(400).json({ok:false,error:"LOST_REASON_REQUIRED"});try{const status=stage==="WON"?"CONVERTED":stage==="LOST"?"CLOSED":stage==="NEW"?"NEW":"CONTACTED";const rows=await prisma.$queryRaw`UPDATE "PublicLead" SET "pipelineStage"=${stage},"priority"=COALESCE(${priority},"priority"),"lostReason"=CASE WHEN ${stage}='LOST' THEN ${lostReason} ELSE NULL END,"lostAt"=CASE WHEN ${stage}='LOST' THEN COALESCE("lostAt",NOW()) ELSE NULL END,"status"=${status},"contactedAt"=CASE WHEN ${stage} IN ('TO_CONTACT','IN_PROGRESS','WON') AND "contactedAt" IS NULL THEN NOW() ELSE "contactedAt" END,"convertedAt"=CASE WHEN ${stage}='WON' AND "convertedAt" IS NULL THEN NOW() ELSE "convertedAt" END,"closedAt"=CASE WHEN ${stage}='LOST' AND "closedAt" IS NULL THEN NOW() ELSE "closedAt" END,"nextActionAt"=CASE WHEN ${stage} IN ('WON','LOST') THEN NULL ELSE "nextActionAt" END,"updatedAt"=NOW() WHERE "id"=${id} RETURNING "id","pipelineStage","priority","lostReason","lostAt","status","contactedAt","convertedAt","closedAt","nextActionAt","updatedAt"`;if(!rows[0])return res.status(404).json({ok:false,error:"LEAD_NOT_FOUND"});return res.json({ok:true,lead:rows[0]});}catch(e){console.error("[lead-pipeline] update",e);return res.status(500).json({ok:false,error:"LEAD_PIPELINE_UPDATE_FAILED"});}});
r.get("/api/leads/pipeline/analytics",async(req,res)=>{try{const days=Math.min(Math.max(Number(req.query.days||30),1),365);const stages=await prisma.$queryRaw`SELECT "pipelineStage" AS "stage",COUNT(*)::int AS "count" FROM "PublicLead" WHERE "createdAt">=NOW()-(${days}*INTERVAL '1 day') GROUP BY "pipelineStage" ORDER BY "pipelineStage"`;const priorities=await prisma.$queryRaw`SELECT "priority",COUNT(*)::int AS "count" FROM "PublicLead" WHERE "pipelineStage" NOT IN ('WON','LOST') GROUP BY "priority" ORDER BY "priority"`;const losses=await prisma.$queryRaw`SELECT COALESCE("lostReason",'OTHER') AS "reason",COUNT(*)::int AS "count" FROM "PublicLead" WHERE "pipelineStage"='LOST' AND "lostAt">=NOW()-(${days}*INTERVAL '1 day') GROUP BY COALESCE("lostReason",'OTHER') ORDER BY COUNT(*) DESC`;const advisers=await prisma.$queryRaw`SELECT COALESCE("assignedTo",'Non attribué') AS "assignedTo",COUNT(*)::int AS "total",COUNT(*) FILTER(WHERE "pipelineStage"='WON')::int AS "won",COUNT(*) FILTER(WHERE "pipelineStage"='LOST')::int AS "lost",COUNT(*) FILTER(WHERE "pipelineStage" NOT IN ('WON','LOST'))::int AS "open" FROM "PublicLead" WHERE "createdAt">=NOW()-(${days}*INTERVAL '1 day') GROUP BY COALESCE("assignedTo",'Non attribué') ORDER BY COUNT(*) DESC`;return res.json({ok:true,days,stages,priorities,losses,advisers});}catch(e){console.error("[lead-pipeline] analytics",e);return res.status(500).json({ok:false,error:"LEAD_PIPELINE_ANALYTICS_FAILED"});}});
return r;}
module.exports=createLeadPipelineRoutes;module.exports.STAGES=STAGES;module.exports.PRIORITIES=PRIORITIES;module.exports.LOST_REASONS=LOST_REASONS;