"use strict";
const express = require("express");
const PROJECTS = new Set(["leisure", "group", "business"]);
const SOURCES = new Set(["general", "group", "business"]);
const buckets = new Map();
function clean(v,m=500){return String(v??"").trim().replace(/\s+/g," ").slice(0,m)}
function limited(req){const now=Date.now(),key=clean(req.headers["x-forwarded-for"]||req.ip||"unknown",120).split(",")[0];let b=buckets.get(key);if(!b||now-b.start>900000)b={start:now,count:0};b.count++;buckets.set(key,b);return b.count>8}
function validate(body={}){const d={project:clean(body.project,30),source:clean(body.source,30)||"general",siteSlug:clean(body.siteSlug,160),name:clean(body.name,120),phone:clean(body.phone,50),email:clean(body.email,180).toLowerCase(),destination:clean(body.destination,240),dates:clean(body.dates,160),travellers:clean(body.travellers,120),budget:clean(body.budget,160),wishes:clean(body.wishes,2500)};if(clean(body.website,200))return{spam:true};if(!PROJECTS.has(d.project))return{error:"INVALID_PROJECT"};if(!SOURCES.has(d.source))return{error:"INVALID_SOURCE"};if(!/^[a-z0-9-]{2,160}$/.test(d.siteSlug))return{error:"INVALID_SITE"};if(d.name.length<2)return{error:"INVALID_NAME"};if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.email))return{error:"INVALID_EMAIL"};if(d.phone.replace(/\D/g,"").length<8)return{error:"INVALID_PHONE"};if(!d.destination||!d.dates||!d.travellers)return{error:"MISSING_PROJECT_DETAILS"};return{data:d}}
function createPublicLeadsRoutes(prisma){const router=express.Router();router.post("/api/public/leads",async(req,res)=>{if(limited(req))return res.status(429).json({ok:false,error:"RATE_LIMITED"});const c=validate(req.body);if(c.spam)return res.status(202).json({ok:true});if(c.error)return res.status(400).json({ok:false,error:c.error});try{const site=await prisma.agencySite.findFirst({where:{slug:c.data.siteSlug},select:{id:true,agencyId:true,slug:true}});if(!site)return res.status(404).json({ok:false,error:"SITE_NOT_FOUND"});const rows=await prisma.$queryRaw`INSERT INTO "PublicLead" ("id","agencyId","agencySiteId","siteSlug","projectType","source","name","phone","email","destination","travelDates","travellers","budget","wishes","status","erpSyncStatus","createdAt","updatedAt") VALUES (concat('lead_',replace(gen_random_uuid()::text,'-','')),${site.agencyId},${site.id},${site.slug},${c.data.project},${c.data.source},${c.data.name},${c.data.phone},${c.data.email},${c.data.destination},${c.data.dates},${c.data.travellers},${c.data.budget||null},${c.data.wishes||null},'NEW','DISABLED',NOW(),NOW()) RETURNING "id","status","createdAt"`;return res.status(201).json({ok:true,lead:rows[0]});}catch(e){console.error("[public-leads] intake failed",e);return res.status(500).json({ok:false,error:"LEAD_INTAKE_FAILED"})}});return router}
module.exports=createPublicLeadsRoutes;module.exports.validate=validate;
