const assetEngine = require("./asset-engine");
const createAgencySeoModule = require("./agency-seo");
const miniSite = require("./mini-site");
const seoFactory = require("./seo-factory");
const contentComposer = require("./content-composer");
const contentFactory = require("./content-factory");
const destinationEngine = require("./destination-engine");
const { createSearchConsoleOAuthRoutes } = require("../routes/searchConsoleOAuth");
const createPublicLeadsRoutes = require("../routes/publicLeads");
const platformCore = require("./platform-core");
const aiPlatform = require("./ai-platform");
const seoPlatform = require("./seo-platform");
const knowledgeGraph = require("./knowledge-graph");
const agencySite = require("./agency-site");
const agencyProfile = require("./agency-profile");
const googleBusinessPhotos = require("./google-business-photos");
const contentQuality = require("./content-quality");
const marketingAutomation = require("./marketing-automation");
const editorialCalendar = require("./editorial-calendar");
const editorialAi = require("./editorial-ai");
const networkSiteProvisioning = require("./network-site-provisioning");
const publishers = require("./publishers");
const seoBrain = require("./seo-brain");
const seoAutopilot = require("./seo-autopilot");
const tenantCore = require("./tenant-core");
const brand = require("./brand");
const miniSiteBuilder = require("./mini-site-builder");
const siteProvisioning = require("./site-provisioning");
const campaignManager = require("./campaign-manager");
const contentGeneration = require("./content-generation");
const travelCore = require("./travel-core");
const aiSeoGenerator = require("./ai-seo-generator");
const aiContent = require("./ai-content");
const pageBuilderPersistence = require("./page-builder-persistence");
const minisiteBlueprint = require("./minisite-blueprint");
const minisiteBlueprintPersistence = require("./minisite-blueprint-persistence");
const minisiteSeoEnrichment = require("./minisite-seo-enrichment");
const minisiteSemanticEngine = require("./minisite-semantic-engine");
const minisiteStructuredData = require("./minisite-structured-data");
const searchConsoleSubmission = require("./search-console-submission");
const flexiblePaymentExperience = require("./flexible-payment-experience");
module.exports=function registerModules(app,{prisma}){
 if(tenantCore.routes)app.use(tenantCore.routes({prisma}));
 const tenantService=new tenantCore.TenantService(new tenantCore.TenantRepository(prisma));app.use(tenantCore.createTenantMiddleware(tenantService));
 app.use(createSearchConsoleOAuthRoutes(prisma));app.use(createPublicLeadsRoutes(prisma));
 for(const mod of [brand,miniSiteBuilder,siteProvisioning,campaignManager,contentGeneration,travelCore,aiSeoGenerator,aiContent,destinationEngine,seoPlatform,aiPlatform,platformCore,assetEngine])if(mod.routes)app.use(mod.routes({prisma}));
 const agencySeo=createAgencySeoModule(prisma);if(agencySeo.routes)app.use(agencySeo.routes);
 for(const mod of [miniSite,seoFactory,contentComposer,contentFactory,knowledgeGraph,contentQuality,marketingAutomation,editorialCalendar])if(mod.routes)app.use(mod.routes({prisma}));
 if(editorialAi.routes)app.use(editorialAi.routes({prisma}));if(networkSiteProvisioning.routes)app.use(networkSiteProvisioning.routes({prisma}));if(publishers.googleBusiness?.routes)app.use(publishers.googleBusiness.routes({prisma}));
 for(const mod of [seoBrain,seoAutopilot,agencyProfile,googleBusinessPhotos,pageBuilderPersistence,agencySite,minisiteBlueprint,minisiteBlueprintPersistence,minisiteSeoEnrichment,minisiteSemanticEngine,minisiteStructuredData])if(mod.routes)app.use(mod.routes({prisma}));
 if(searchConsoleSubmission.routes){const provider=searchConsoleSubmission.createConfiguredSearchConsoleProvider({prisma});app.use(searchConsoleSubmission.routes({prisma,provider}));}
 if(flexiblePaymentExperience.routes)app.use(flexiblePaymentExperience.routes({prisma}));
};
