"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { indexationApi } from "../../../lib/indexation-api";

function sites(value) { return Array.isArray(value) ? value : []; }
function statusLabel(value) { return value === "strong" ? "Solide" : value === "improvable" ? "À renforcer" : "Faible"; }
function depthLabel(value) { return value === "deep" ? "Profonde" : value === "partial" ? "Partielle" : "Superficielle"; }
function intentLabel(value) { return value === "strong" ? "Forte" : value === "partial" ? "Partielle" : "Faible"; }
function mark(value) { return value ? "✓" : "✕"; }
function priorityFromSeverity(value) { return value === "critical" || value === "high" ? "high" : value === "medium" ? "medium" : "low"; }
function targetLabel(intent) { const targets = sites(intent?.targets); if (targets.length) return targets.map((target) => `/${target.slug || "accueil"}`).join(", "); return intent?.diffuse ? "intention diffuse — aucune cible locale claire" : "aucune cible locale claire"; }

export default function LocalSeoCoverageClient() {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [queued, setQueued] = useState(() => new Set()); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setData(await indexationApi.localSeoCoverage()); } catch (loadError) { setError(loadError.message || "Impossible de charger l’audit SEO local."); } finally { setLoading(false); } };
  useEffect(() => { let active = true; indexationApi.localSeoCoverage().then((payload) => { if (active) setData(payload); }).catch((loadError) => { if (active) setError(loadError.message || "Impossible de charger l’audit SEO local."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const addGapToQueue = async (site, gap) => { const key = `${site.siteSlug}:${gap.code}:${gap.city || gap.intent || ""}`; setBusy(key); setError(""); try { await indexationApi.createWorkItem({ siteSlug: site.siteSlug, opportunity: { workKey: `local-seo:${gap.code}:${gap.city || gap.intent || "global"}`, label: gap.message, sourceType: "local-seo-coverage", priority: priorityFromSeverity(gap.severity), action: { label: gap.message, rationale: "Corriger cette lacune SEO locale puis mesurer l’effet dans Search Console." } } }); setQueued((current) => new Set([...current, key])); } catch (queueError) { setError(queueError.message || "Impossible d’ajouter cette correction à la file SEO."); } finally { setBusy(""); } };

  return <main className="indexation-shell">
    <header className="indexation-hero"><div><p className="indexation-eyebrow">MSE-25.28 · Local Intent Target Mapping</p><small>MSE-25.27 · Local Search Intent Coverage · MSE-25.26 · Local Semantic Depth</small><h1>Couverture SEO locale</h1><p>Contrôle la pertinence locale, les intentions commerciales et la page éditoriale qui porte réellement chaque intention.</p></div><div className="indexation-actions"><Link className="indexation-nav-link" href="/indexation/work-queue">File SEO</Link><Link className="indexation-nav-link" href="/indexation/performance">Performance</Link><Link className="indexation-nav-link" href="/indexation">Cockpit</Link></div></header>
    <div className="rollout-safety">Une intention locale n’est validée que si la ville et le service sont réunis sur une même page cible. Une présence dispersée dans le mini-site reste à corriger. Audit uniquement : aucune doorway page générée automatiquement.</div>
    {error ? <div className="indexation-message indexation-error">{error}</div> : null}{loading ? <div className="indexation-empty">Audit des mini-sites publiés…</div> : null}
    {data ? <><section className="indexation-metrics"><div className="indexation-metric"><strong>{data.summary?.averageScore || 0}/100</strong><span>score moyen réseau</span></div><div className="indexation-metric"><strong>{data.summary?.semanticallyDeep || 0}/{data.summary?.siteCount || 0}</strong><span>contenus sémantiquement profonds</span></div><div className="indexation-metric"><strong>{data.summary?.coreIntentMapped || 0}/{data.summary?.siteCount || 0}</strong><span>intention agence + ville mappée</span></div><div className="indexation-metric"><strong>{data.summary?.intentTargetsStrong || 0}/{data.summary?.siteCount || 0}</strong><span>mapping d’intentions solide</span></div></section>
      <div className="rollout-safety"><small>Repères historiques : {data.summary?.internallyLinked || 0}/{data.summary?.siteCount || 0} sans page orpheline · {data.summary?.searchIntentStrong || 0}/{data.summary?.siteCount || 0} couverture d’intentions forte</small></div>
      <section className="indexation-card performance-table-card"><div className="indexation-card-head"><div><h2>Matrice de pertinence locale</h2><p>Ville principale, title, meta, H1, contenu publié, NAP, TravelAgency/LocalBusiness, Maillage interne, profondeur sémantique et correspondance intention → page cible.</p></div><button type="button" onClick={load}>Actualiser</button></div><div className="performance-table-wrap"><table className="performance-table"><thead><tr><th>Agence</th><th>Score</th><th>Profondeur locale</th><th>Intentions locales → cibles</th><th>Signaux éditoriaux</th><th>NAP / JSON-LD</th><th>Priorités</th></tr></thead><tbody>{sites(data.sites).map((site) => { const schema = site.structuredData || {}; const semantic = site.semanticDepth || {}; const dimensions = semantic.dimensions || {}; const mapping = site.intentTargetMapping || {}; const historicalIntentCoverage = site.searchIntentCoverage || {}; return <tr key={site.siteSlug}><td><strong>{site.agencyName || site.siteSlug}</strong><br /><small>{site.primaryCity || "Ville non renseignée"} · {site.publishedPageCount} page(s)</small></td><td><strong>{site.score}/100</strong><br /><small>{statusLabel(site.status)}</small></td><td><strong>{semantic.depthScore || 0}/100</strong><br /><small>{depthLabel(semantic.status)} · {semantic.wordCount || 0} mots</small></td><td><strong>{mapping.score || 0}/100</strong><br /><small>{intentLabel(mapping.status)} · {mapping.mappedIntentCount || 0}/{mapping.intentCount || 0} mappées</small><br />{sites(mapping.intents).map((intent) => <span key={intent.key}>{mark(intent.mapped)} {intent.label} → {targetLabel(intent)}<br /></span>)}<small>Couverture historique : {historicalIntentCoverage.coveredIntentCount || 0}/{historicalIntentCoverage.intentCount || 0} · {sites(historicalIntentCoverage.intents).filter((intent) => intent.localQualified).length} localQualified</small></td><td>{mark(dimensions.locality)} ville · {mark(dimensions.services)} services · {mark(dimensions.expertise)} expertise<br />{mark(dimensions.proof)} preuves · {mark(dimensions.localContext)} ancrage territorial · Maillage interne</td><td>{mark(site.nap?.complete)} NAP · {mark(schema.hasTravelAgency && schema.hasLocalBusiness)} schema<br /><small>{mark(schema.hasAddress)} adresse · {mark(schema.hasTelephone)} téléphone · {mark(schema.hasAreaServed)} zone</small></td><td>{site.gaps?.length ? <ul>{site.gaps.slice(0, 10).map((gap) => { const key = `${site.siteSlug}:${gap.code}:${gap.city || gap.intent || ""}`; const done = queued.has(key); return <li key={key}>{gap.message} <button type="button" disabled={done || busy === key} onClick={() => addGapToQueue(site, gap)}>{done ? "Dans la file" : busy === key ? "Ajout…" : "Ajouter à la file SEO"}</button></li>; })}</ul> : "Pertinence locale solide"}</td></tr>; })}</tbody></table></div></section></> : null}
  </main>;
}
