"use client";
import {useEffect,useState} from "react";
import {createSeoDraftPage,fetchPageDetails,fetchSite} from "../../lib/page-builder-v2/page-builder-api";
import {saveLocalDraft,readLocalDraft} from "../../lib/page-builder-v2/draft-storage";
import {buildSeoDraftProposal} from "../../lib/page-builder-v2/seo-draft-proposal";
import {auditSeoDraft} from "../../lib/page-builder-v2/seo-draft-quality";
import NetworkUniquenessAudit from "./NetworkUniquenessAudit";
const MODE_LABELS={reinforce_existing:"Renforcer la page existante",enrich_existing:"Enrichir la page existante",consider_new_page:"Nouvelle page à valider",monitor:"Surveillance SEO"};
export default function SeoDesignerContext({siteId,pageSlug,keyword,mode,brief}){
 const[pageOpened,setPageOpened]=useState(false),[expanded,setExpanded]=useState(Boolean(brief)),[preparing,setPreparing]=useState(false),[proposalNotice,setProposalNotice]=useState(""),[proposalError,setProposalError]=useState(""),[quality,setQuality]=useState(null),[qualityLoading,setQualityLoading]=useState(false);
 useEffect(()=>{if(!pageSlug||pageOpened)return;const normalizedTarget=`/${String(pageSlug).replace(/^\/+|\/+$/g,"")}`;const open=()=>{const target=Array.from(document.querySelectorAll("nav button")).find(button=>button.querySelector("small")?.textContent?.trim()===normalizedTarget);if(!target)return false;target.click();setPageOpened(true);return true};if(open())return;const observer=new MutationObserver(()=>{if(open())observer.disconnect()});observer.observe(document.body,{childList:true,subtree:true});const timeout=window.setTimeout(()=>observer.disconnect(),8000);return()=>{observer.disconnect();window.clearTimeout(timeout)}},[pageSlug,pageOpened]);
 useEffect(()=>{let cancelled=false;async function loadQuality(){if(!siteId||!pageSlug||!brief){setQuality(null);return}setQualityLoading(true);try{const site=await fetchSite(siteId),target=site.pages.find(page=>String(page.slug||"")===String(pageSlug||""));if(!target){if(!cancelled)setQuality(null);return}let page=await fetchPageDetails(site,target);const local=readLocalDraft(site.id,target.id);if(local?.page)page=local.page;if(!cancelled)setQuality(auditSeoDraft(page,brief))}catch{if(!cancelled)setQuality(null)}finally{if(!cancelled)setQualityLoading(false)}}loadQuality();return()=>{cancelled=true}},[siteId,pageSlug,brief,proposalNotice]);
 async function prepareDraftProposal(){if(!siteId||!pageSlug||!brief)return;if(!window.confirm("Préparer les sections recommandées dans un brouillon local de cette page ? Rien ne sera publié automatiquement."))return;setPreparing(true);setProposalError("");setProposalNotice("");try{const site=await fetchSite(siteId),target=site.pages.find(page=>String(page.slug||"")===String(pageSlug||""));if(!target)throw new Error(`La page cible /${pageSlug} n'existe pas dans ce mini-site.`);const detailedPage=await fetchPageDetails(site,target),proposal=buildSeoDraftProposal(detailedPage,brief,mode);if(proposal.duplicate){setProposalNotice(proposal.note);return}const savedAt=saveLocalDraft(site.id,proposal.page);if(!savedAt)throw new Error("Impossible d'enregistrer le brouillon local SEO.");setProposalNotice(`${proposal.note} Le Designer va restaurer ce brouillon local.`);window.setTimeout(()=>window.location.reload(),450)}catch(error){setProposalError(error?.message||"Impossible de préparer la proposition SEO.")}finally{setPreparing(false)}}
 async function createNewDraft(){if(!siteId||!brief)return;const confirmation=`Créer une nouvelle page SEO en BROUILLON pour « ${brief.proposedH1||keyword} » ?\n\nElle restera non publiée et hors navigation jusqu'à validation humaine.`;if(!window.confirm(confirmation))return;setPreparing(true);setProposalError("");setProposalNotice("");try{const site=await fetchSite(siteId);if(!site.agencyId)throw new Error("L'agence du mini-site est introuvable.");const result=await createSeoDraftPage(site.agencyId,{...brief,keyword:brief.keyword||keyword});const slug=result?.page?.slug;if(!slug)throw new Error("La page brouillon a été créée mais son slug est introuvable.");setProposalNotice(result.created?`Page /${slug} créée en brouillon non publié.`:`La page /${slug} existait déjà : aucune duplication créée.`);const url=new URL(window.location.href);url.searchParams.set("seoPageSlug",slug);url.searchParams.set("seoMode","enrich_existing");window.setTimeout(()=>window.location.assign(url.toString()),650)}catch(error){setProposalError(error?.message||"Impossible de créer la page SEO en brouillon.")}finally{setPreparing(false)}}
 if(!keyword&&!pageSlug&&!brief)return null;const canPrepareExisting=Boolean(siteId&&pageSlug&&brief)&&mode!=="consider_new_page"&&mode!=="monitor",canCreateNew=Boolean(siteId&&brief)&&mode==="consider_new_page";
 return <aside style={{position:"fixed",right:20,bottom:20,zIndex:120,width:"min(440px, calc(100vw - 40px))",maxHeight:"calc(100vh - 110px)",overflow:"auto",border:"1px solid #c7d2fe",borderRadius:14,background:"#eef2ff",color:"#1e1b4b",padding:16,boxShadow:"0 16px 40px rgba(30, 41, 59, .18)"}}>
  <div style={{fontSize:11,fontWeight:800,textTransform:"uppercase",letterSpacing:".08em",opacity:.65}}>Contexte SEO local</div><strong style={{display:"block",marginTop:6,fontSize:16}}>{keyword||brief?.proposedH1||"Opportunité éditoriale"}</strong><div style={{marginTop:6,fontSize:13,lineHeight:1.5}}>{MODE_LABELS[mode]||MODE_LABELS.monitor}{pageSlug?` · page cible /${pageSlug}`:" · page cible à valider"}</div>
  {brief?<><button type="button" onClick={()=>setExpanded(v=>!v)} style={{marginTop:12,border:"1px solid #a5b4fc",borderRadius:8,background:"white",padding:"7px 10px",fontWeight:700,color:"#312e81",cursor:"pointer"}}>{expanded?"Masquer le brief":"Afficher le brief SEO"}</button>{expanded?<div style={{marginTop:12,borderTop:"1px solid #c7d2fe",paddingTop:12,fontSize:12,lineHeight:1.55}}><div style={{fontWeight:800}}>H1 proposé</div><div>{brief.proposedH1}</div>{brief.angle?<><div style={{fontWeight:800,marginTop:10}}>Angle éditorial</div><div>{brief.angle}</div></>:null}{brief.sections?.length?<><div style={{fontWeight:800,marginTop:10}}>Sections à traiter</div><ol style={{paddingLeft:20,margin:"5px 0 0"}}>{brief.sections.map((section,index)=><li key={section.code||index} style={{marginBottom:6}}><strong>{section.title}</strong>{section.purpose?` — ${section.purpose}`:""}</li>)}</ol></>:null}{brief.localProofsRequired?.length?<><div style={{fontWeight:800,marginTop:10}}>Preuves locales nécessaires</div><ul style={{paddingLeft:20,margin:"5px 0 0"}}>{brief.localProofsRequired.map((item,index)=><li key={index}>{item}</li>)}</ul></>:null}</div>:null}</>:null}
  {pageSlug&&brief?<div style={{marginTop:14,padding:12,borderRadius:10,background:"white",border:`1px solid ${quality?.ready?"#86efac":"#fca5a5"}`}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><strong>Qualité avant publication</strong><strong>{qualityLoading?"…":quality?`${quality.score}/100`:"—"}</strong></div>{quality?<><div style={{marginTop:5,fontSize:12,color:quality.ready?"#166534":"#991b1b",fontWeight:700}}>{quality.ready?"Aucun blocage critique":"Publication déconseillée"}</div><div style={{marginTop:7,fontSize:11,lineHeight:1.45,color:"#475569"}}>{quality.metrics.wordCount} mots · {quality.metrics.blockCount} blocs · {quality.metrics.draftBlockCount} blocs encore en brouillon</div>{quality.blockers.length?<ul style={{paddingLeft:18,margin:"8px 0 0",fontSize:11,color:"#991b1b"}}>{quality.blockers.map(item=><li key={item.code}><strong>{item.label}</strong> — {item.detail}</li>)}</ul>:null}{quality.warnings.length?<details style={{marginTop:8,fontSize:11}}><summary style={{cursor:"pointer",fontWeight:700}}>{quality.warnings.length} optimisation(s) recommandée(s)</summary><ul style={{paddingLeft:18}}>{quality.warnings.map(item=><li key={item.code}><strong>{item.label}</strong> — {item.detail}</li>)}</ul></details>:null}</>:<div style={{marginTop:6,fontSize:11,color:"#64748b"}}>Le contrôle sera disponible dès que la page cible est chargée.</div>}</div>:null}
  {pageSlug?<NetworkUniquenessAudit siteId={siteId} pageSlug={pageSlug} refreshKey={proposalNotice}/>:null}
  {canPrepareExisting?<button type="button" disabled={preparing} onClick={prepareDraftProposal} style={{marginTop:14,width:"100%",border:0,borderRadius:9,background:"#312e81",color:"white",padding:"10px 12px",fontWeight:800,cursor:preparing?"wait":"pointer",opacity:preparing?0.7:1}}>{preparing?"Préparation…":"Préparer les blocs SEO en brouillon"}</button>:null}
  {canCreateNew?<><div style={{marginTop:12,padding:10,borderRadius:8,background:"#fff7ed",color:"#9a3412",fontSize:12,lineHeight:1.5}}>Cette action crée uniquement une page <strong>brouillon</strong>, non publiée et absente de la navigation publique. Une confirmation explicite est demandée.</div><button type="button" disabled={preparing} onClick={createNewDraft} style={{marginTop:10,width:"100%",border:"1px solid #c2410c",borderRadius:9,background:"#fff",color:"#9a3412",padding:"10px 12px",fontWeight:800,cursor:preparing?"wait":"pointer",opacity:preparing?0.7:1}}>{preparing?"Création…":"Valider et créer la page brouillon"}</button></>:null}
  {proposalNotice?<div style={{marginTop:10,padding:9,borderRadius:8,background:"#ecfdf5",color:"#166534",fontSize:12}}>{proposalNotice}</div>:null}{proposalError?<div style={{marginTop:10,padding:9,borderRadius:8,background:"#fef2f2",color:"#991b1b",fontSize:12}}>{proposalError}</div>:null}<div style={{marginTop:12,fontSize:12,lineHeight:1.5,opacity:.75}}>Aucune publication automatique : création et blocs SEO restent en brouillon jusqu'à validation humaine. Le score qualité est un garde-fou éditorial, pas une garantie de classement Google.</div>
 </aside>
}