"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const crypto=require("node:crypto");const{requestActor,requestActorContext}=require("./request-actor");
function signed(actor,timestamp,secret){return crypto.createHmac("sha256",secret).update(`${actor}\n${timestamp}`).digest("hex")}
test("prefers native authenticated user",()=>{assert.equal(requestActor({user:{email:"nicolas@example.test"}},{TRUST_IDENTITY_HEADERS:"false"}),"nicolas@example.test");assert.deepEqual(requestActorContext({user:{email:"nicolas@example.test"}},{TRUST_IDENTITY_HEADERS:"false"}),{actor:"nicolas@example.test",source:"native",verified:true})});
test("accepts a fresh correctly signed proxy identity",()=>{const now=Date.now(),secret="test-secret",actor="admin";const req={headers:{"x-auth-user":actor,"x-auth-timestamp":String(now),"x-auth-signature":signed(actor,String(now),secret)}};assert.equal(requestActor(req,{IDENTITY_HMAC_SECRET:secret},now),actor);assert.deepEqual(requestActorContext(req,{IDENTITY_HMAC_SECRET:secret},now),{actor,source:"signed_proxy",verified:true})});
test("rejects forged or stale signed identity",()=>{const now=Date.now(),secret="test-secret",actor="admin";const forged={headers:{"x-auth-user":actor,"x-auth-timestamp":String(now),"x-auth-signature":"00"}};assert.equal(requestActor(forged,{IDENTITY_HMAC_SECRET:secret},now),null);const old=now-600000,stale={headers:{"x-auth-user":actor,"x-auth-timestamp":String(old),"x-auth-signature":signed(actor,String(old),secret)}};assert.equal(requestActor(stale,{IDENTITY_HMAC_SECRET:secret,IDENTITY_HMAC_MAX_AGE_MS:"300000"},now),null)});
test("unsigned identity headers remain rejected by default",()=>{const req={headers:{"x-forwarded-user":"proxy-user"}};assert.deepEqual(requestActorContext(req,{TRUST_IDENTITY_HEADERS:"false"}),{actor:null,source:"anonymous",verified:false})});
test("explicit legacy trusted header is marked unverified",()=>{const req={headers:{"x-forwarded-user":"proxy-user"}};assert.deepEqual(requestActorContext(req,{TRUST_IDENTITY_HEADERS:"true"}),{actor:"proxy-user",source:"trusted_header",verified:false})});
test("native identity wins over signed proxy identity",()=>{const now=Date.now(),secret="test-secret";const req={user:{name:"Native User"},headers:{"x-auth-user":"Proxy User","x-auth-timestamp":String(now),"x-auth-signature":signed("Proxy User",String(now),secret)}};assert.deepEqual(requestActorContext(req,{IDENTITY_HMAC_SECRET:secret},now),{actor:"Native User",source:"native",verified:true})});
