"use strict";
const test=require("node:test"),assert=require("node:assert/strict");const{pageText,similarity,sharedSegments,distinctiveTerms,analyzeUniqueness}=require("./content-uniqueness");
test("identical local copy is detected",()=>{assert.equal(similarity("agence voyage locale conseil expert famille paris","agence voyage locale conseil expert famille paris"),1)});
test("different copy remains distinct",()=>{assert.ok(similarity("conseillers bois colombes rendez vous avenue argenteuil voyages sur mesure","equipe gien circuits groupes depart montargis accompagnement croisiere")<0.3)});
test("high network similarity blocks readiness from structured sections",()=>{const sections=[{jsonContent:{html:"Notre agence locale vous accompagne pour construire votre voyage sur mesure avec des conseils personnalises et un suivi avant pendant apres votre depart."}}];const target={id:"a",title:"Voyage sur mesure",sections},other={id:"b",title:"Voyage sur mesure",sections,site:{agencyId:2,agency:{name:"Agence B"}}};const result=analyzeUniqueness(target,[other]);assert.equal(result.ready,false);assert.equal(result.severity,"blocker")});
test("V2 PageBlock content participates in uniqueness analysis",()=>{const blocks=[{content:{title:"Votre agence de voyages locale",html:"Nos conseillers construisent avec vous un itineraire personnalise, suivent votre dossier et restent disponibles avant pendant et apres le voyage.",items:[{title:"Conseil",text:"Rendez vous en agence pour parler de votre projet."}]}}];const target={id:"a",title:"Accueil",blocks},other={id:"b",title:"Accueil",blocks,site:{agencyId:2,agency:{name:"Agence B"}}};assert.match(pageText(target),/itineraire personnalise/);const result=analyzeUniqueness(target,[other]);assert.equal(result.ready,false);assert.equal(result.severity,"blocker");assert.ok(result.metrics.targetWordCount>10)});
test("shared segments explain what must be rewritten",()=>{const common="nos conseillers construisent avec vous un voyage personnalise et restent disponibles avant pendant apres votre depart";const segments=sharedSegments(common+" bois colombes",common+" maurepas",8,5);assert.ok(segments.length>=1);assert.match(segments[0],/conseillers construisent/)});
test("analysis returns actionable local differentiation guidance",()=>{const common="nos conseillers construisent avec vous un voyage personnalise et restent disponibles avant pendant apres votre depart avec un accompagnement attentif";const target={id:"a",title:"Accueil",blocks:[{content:{html:common+" rendez vous bois colombes avenue argenteuil"}}],site:{agencyId:6,agency:{name:"Mondescale Bois-Colombes",city:"Bois-Colombes"}}};const other={id:"b",title:"Accueil",blocks:[{content:{html:common+" rendez vous maurepas centre ville"}}],site:{agencyId:2,agency:{name:"Mondescale Maurepas",city:"Maurepas"}}};const result=analyzeUniqueness(target,[other]);assert.equal(result.version,"1.2");assert.ok(result.sharedSegments.length);assert.ok(result.recommendations.some(r=>r.code==="ADD_LOCAL_PROOFS"));assert.ok(result.distinctiveTerms.some(t=>t.term==="bois"||t.term==="colombes"));assert.equal(result.metrics.sharedSegmentCount,result.sharedSegments.length)});
test("distinctive terms ignore generic travel vocabulary",()=>{const terms=distinctiveTerms("agence voyage voyage bois colombes colombes avenue argenteuil conseillers");assert.ok(!terms.some(t=>t.term==="voyage"));assert.ok(terms.some(t=>t.term==="colombes"))});
