const { TenantScopedRepository } = require("../tenant-core/scoped-repository");
const { pageSlugCandidates } = require("./page-slug");
class AgencySiteRepository extends TenantScopedRepository {
 getAgency(id){return this.prisma.agency.findFirst({where:this.scope({id:Number(id)})})}
 listSites(){return this.prisma.agencySite.findMany({where:{tenantId:this.tenantId},orderBy:{name:"asc"},include:{agency:true,pages:{orderBy:{displayOrder:"asc"},select:{id:true,title:true,slug:true,path:true,status:true,published:true,displayOrder:true}}}})}
 findByAgencyId(agencyId){return this.prisma.agencySite.findFirst({where:this.scope({agencyId:Number(agencyId)}),include:{pages:{orderBy:{displayOrder:"asc"},include:{sections:{orderBy:{displayOrder:"asc"}},blocks:{orderBy:{displayOrder:"asc"}}}}}})}
 async listNetworkPages(excludePageId=null){return this.prisma.agencySitePage.findMany({where:{site:{tenantId:this.tenantId},...(excludePageId?{id:{not:String(excludePageId)}}:{})},include:{sections:{orderBy:{displayOrder:"asc"}},blocks:{orderBy:{displayOrder:"asc"}},site:{include:{agency:{select:{id:true,name:true,city:true}}}}}})}
 async upsertSite(site){const existing=await this.prisma.agencySite.findFirst({where:this.scope({agencyId:Number(site.agencyId)}),select:{id:true}}),data={name:site.name,slug:site.slug,basePath:site.basePath,status:site.status,theme:site.theme,generatedAt:new Date()};if(existing)return this.prisma.agencySite.update({where:{id:existing.id},data});return this.prisma.agencySite.create({data:this.createData({...site,agencyId:Number(site.agencyId),generatedAt:new Date()})})}
 upsertPage(siteId,page,parentId){return this.prisma.agencySitePage.upsert({where:{siteId_slug:{siteId,slug:page.slug}},update:{parentId,title:page.title,path:page.path,pageType:page.pageType,menuTitle:page.menuTitle,menuLocation:page.menu,displayOrder:page.order,seoTitle:page.seoTitle,metaDescription:page.metaDescription,h1:page.h1,schemaType:page.schemaType,status:"draft"},create:{siteId,parentId,title:page.title,slug:page.slug,path:page.path,pageType:page.pageType,menuTitle:page.menuTitle,menuLocation:page.menu,displayOrder:page.order,seoTitle:page.seoTitle,metaDescription:page.metaDescription,h1:page.h1,schemaType:page.schemaType,status:"draft"}})}
 async createDraftPage(siteId,page,parentId=null){const site=await this.prisma.agencySite.findFirst({where:{id:String(siteId),tenantId:this.tenantId},select:{id:true}});if(!site){const e=new Error("Mini-site introuvable pour ce tenant.");e.statusCode=404;e.code="AGENCY_SITE_NOT_FOUND";throw e}const existing=await this.prisma.agencySitePage.findUnique({where:{siteId_slug:{siteId:site.id,slug:page.slug}}});if(existing)return{created:false,reason:"PAGE_ALREADY_EXISTS",page:existing};try{const created=await this.prisma.agencySitePage.create({data:{siteId:site.id,parentId,title:page.title,slug:page.slug,path:page.path,pageType:page.pageType,menuTitle:page.menuTitle,menuLocation:page.menu,displayOrder:page.order,seoTitle:page.seoTitle,metaDescription:page.metaDescription,h1:page.h1,schemaType:page.schemaType,status:"draft",published:false}});return{created:true,reason:"PAGE_CREATED",page:created}}catch(error){if(error?.code==="P2002"){const concurrent=await this.prisma.agencySitePage.findUnique({where:{siteId_slug:{siteId:site.id,slug:page.slug}}});if(concurrent)return{created:false,reason:"PAGE_CREATED_CONCURRENTLY",page:concurrent}}throw error}}
 upsertSection(pageId,section){return this.prisma.agencySiteSection.upsert({where:{pageId_sectionType:{pageId,sectionType:section.sectionType}},update:{jsonContent:section.content,displayOrder:section.displayOrder,status:"draft"},create:{pageId,sectionType:section.sectionType,jsonContent:section.content,displayOrder:section.displayOrder,status:"draft"}})}
 async createSectionIfMissing(pageId,section){const normalizedPageId=String(pageId||"").trim(),sectionType=String(section?.sectionType||"").trim();if(!normalizedPageId||!sectionType){const e=new Error("pageId et sectionType sont obligatoires.");e.statusCode=400;e.code="INVALID_SECTION_CREATE";throw e}const page=await this.prisma.agencySitePage.findFirst({where:{id:normalizedPageId,site:{tenantId:this.tenantId}},select:{id:true}});if(!page){const e=new Error(`Page ${normalizedPageId} introuvable pour ce tenant.`);e.statusCode=404;e.code="AGENCY_SITE_PAGE_NOT_FOUND";throw e}const uniqueWhere={pageId_sectionType:{pageId:normalizedPageId,sectionType}},existing=await this.prisma.agencySiteSection.findUnique({where:uniqueWhere});if(existing)return{created:false,reason:"SECTION_ALREADY_EXISTS",section:existing};try{const created=await this.prisma.agencySiteSection.create({data:{pageId:normalizedPageId,sectionType,jsonContent:section.content??{},displayOrder:Number(section.displayOrder||0),status:"draft"}});return{created:true,reason:"SECTION_CREATED",section:created}}catch(error){if(error?.code==="P2002"){const concurrent=await this.prisma.agencySiteSection.findUnique({where:uniqueWhere});return{created:false,reason:"SECTION_CREATED_CONCURRENTLY",section:concurrent}}throw error}}
 deletePages(siteId){return this.prisma.agencySitePage.deleteMany({where:{siteId,site:{tenantId:this.tenantId}}})} deleteSectionsForSite(siteId){return this.prisma.agencySiteSection.deleteMany({where:{page:{siteId,site:{tenantId:this.tenantId}}}})}
 findPublicSite(siteSlug){return this.prisma.agencySite.findFirst({where:this.scope({slug:siteSlug,status:"published"}),include:{agency:{select:{id:true,name:true,city:true,address:true,postalCode:true,phone:true,email:true,website:true,googleReviewUrl:true,googleLocationId:true}},pages:{where:{OR:[{published:true},{status:"published"}]},orderBy:{displayOrder:"asc"},include:{sections:{orderBy:{displayOrder:"asc"}},blocks:{orderBy:{displayOrder:"asc"}}}}}})}
 findPublicPage(siteSlug,slug){return this.prisma.agencySitePage.findFirst({where:{AND:[{site:{is:this.scope({slug:siteSlug,status:"published"})}},{slug:{in:pageSlugCandidates(slug)}},{OR:[{published:true},{status:"published"}]}]},orderBy:{slug:"desc"},include:{sections:{orderBy:{displayOrder:"asc"}},blocks:{orderBy:{displayOrder:"asc"}},site:{include:{agency:{select:{id:true,name:true,city:true,address:true,postalCode:true,phone:true,email:true,website:true,googleReviewUrl:true,googleLocationId:true}}}}}})}
 findPage(agencyId,slug){const id=Number(agencyId);if(!Number.isInteger(id))return null;return this.prisma.agencySitePage.findFirst({where:{site:{is:{agencyId:id,tenantId:this.tenantId}},slug:{in:pageSlugCandidates(slug)}},orderBy:{slug:"desc"},include:{sections:{orderBy:{displayOrder:"asc"}},blocks:{orderBy:{displayOrder:"asc"}},site:{include:{agency:{select:{id:true,name:true,city:true,address:true,postalCode:true,phone:true,email:true,website:true,googleReviewUrl:true,seoLevel:true,reviews:{where:{rating:{gte:4}},orderBy:[{publishedAt:"desc"},{createdAt:"desc"}],take:20,select:{rating:true,comment:true,publishedAt:true,createdAt:true}},keywords:{where:{active:true},orderBy:{createdAt:"desc"},take:20,select:{keyword:true,city:true}}}}}}}})}
 async replacePageSections(pageId,sections){const page=await this.prisma.agencySitePage.findFirst({where:{id:pageId,site:{tenantId:this.tenantId}},select:{id:true}});if(!page)return null;const typeCounts=new Map(),normalizedSections=sections.map((section,index)=>{const baseType=String(section.jsonContent?.__builderType||section.sectionType||"section").replace(/--\d+$/,"").trim(),count=(typeCounts.get(baseType)||0)+1;typeCounts.set(baseType,count);return{pageId,sectionType:count===1?baseType:`${baseType}--${count}`,jsonContent:{...(section.jsonContent||{}),__builderType:baseType},displayOrder:index,status:section.status||"draft"}});await this.prisma.$transaction(async tx=>{await tx.agencySiteSection.deleteMany({where:{pageId}});if(normalizedSections.length)await tx.agencySiteSection.createMany({data:normalizedSections})});return this.prisma.agencySitePage.findUnique({where:{id:pageId},include:{sections:{orderBy:{displayOrder:"asc"}},blocks:{orderBy:{displayOrder:"asc"}},site:true}})}
}
module.exports=AgencySiteRepository;
