const express = require("express");
const AgencySiteService = require("./service");
module.exports = ({ prisma }) => {
  const router = express.Router();
  const serviceFor = (req) => new AgencySiteService(prisma, req.tenantId);
  router.get("/agency-sites",async(req,res,next)=>{try{res.json(await serviceFor(req).listSites())}catch(e){next(e)}});
  router.post("/agencies/:id/site/generate",async(req,res,next)=>{try{res.status(201).json(await serviceFor(req).generate(req.params.id,req.body||{}))}catch(e){next(e)}});
  router.post("/agencies/:id/site/compose",async(req,res,next)=>{try{res.json(await serviceFor(req).compose(req.params.id))}catch(e){next(e)}});
  router.post("/agencies/:id/site/rebuild",async(req,res,next)=>{try{res.json(await serviceFor(req).rebuild(req.params.id,req.body||{}))}catch(e){next(e)}});
  router.post("/agencies/:id/site/seo-draft-pages",async(req,res,next)=>{try{const result=await serviceFor(req).createSeoDraftPage(req.params.id,req.body||{});res.status(result.created?201:200).json(result)}catch(e){next(e)}});
  router.get("/agencies/:id/site",async(req,res,next)=>{try{res.json(await serviceFor(req).get(req.params.id))}catch(e){next(e)}});
  router.get("/agencies/:id/site/pages/home",async(req,res,next)=>{try{res.json(await serviceFor(req).page(req.params.id,""))}catch(e){next(e)}});
  router.get("/agencies/:id/site/pages/:slug",async(req,res,next)=>{try{res.json(await serviceFor(req).page(req.params.id,req.params.slug))}catch(e){next(e)}});
  router.put("/agencies/:id/site/pages/home/sections",async(req,res,next)=>{try{res.json(await serviceFor(req).replacePageSections(req.params.id,"",req.body||{}))}catch(e){next(e)}});
  router.put("/agencies/:id/site/pages/:slug/sections",async(req,res,next)=>{try{res.json(await serviceFor(req).replacePageSections(req.params.id,req.params.slug,req.body||{}))}catch(e){next(e)}});
  router.get("/public/agency-sites/:siteSlug",async(req,res,next)=>{try{res.json(await serviceFor(req).publicSite(req.params.siteSlug))}catch(e){next(e)}});
  router.get("/public/agency-sites/:siteSlug/pages/home",async(req,res,next)=>{try{res.json(await serviceFor(req).publicPage(req.params.siteSlug,""))}catch(e){next(e)}});
  router.get("/public/agency-sites/:siteSlug/pages/:slug",async(req,res,next)=>{try{res.json(await serviceFor(req).publicPage(req.params.siteSlug,req.params.slug))}catch(e){next(e)}});
  router.get("/agencies/:id/site/sitemap.xml",async(req,res,next)=>{try{res.type("application/xml").send(await serviceFor(req).sitemap(req.params.id,req.query.origin))}catch(e){next(e)}});
  router.get("/agencies/:id/site/robots.txt",async(req,res,next)=>{try{res.type("text/plain").send(await serviceFor(req).robots(req.params.id,req.query.origin))}catch(e){next(e)}});
  return router;
};
