"use client";
import {useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"";
const dates=[["2027-01-02","2 janvier"],["2027-01-09","9 janvier"],["2027-01-16","16 janvier"],["2027-01-23","23 janvier"],["2027-01-30","30 janvier"],["2027-02-06","6 février"]];
export default function GroupPage(){
 const [origins,setOrigins]=useState([]),[deps,setDeps]=useState([]),[preferred,setPreferred]=useState(""),[intent,setIntent]=useState("HIGH"),[state,setState]=useState("idle");
 const [f,setF]=useState({name:"",email:"",phone:"",adults:2,children:0,infants:0,emailMarketingConsent:false,projectContactConsent:false,phoneMarketingConsent:false,website:""});
 const toggle=(v,a,set)=>set(a.includes(v)?a.filter(x=>x!==v):[...a,v]);
 async function submit(e){e.preventDefault();if(!origins.length||!deps.length)return setState("missing");setState("loading");try{const q=new URLSearchParams(location.search);const r=await fetch(API+"/api/public/group-campaigns/gloire-des-pharaons-2027/pre-register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...f,origins,departures:deps,preferredDeparture:preferred||null,intent,source:q.get("src")||q.get("utm_source")||null})});if(!r.ok)throw new Error((await r.json()).error);setState("done")}catch(e){setState("error")}}
 if(state==="done")return <main style={S.main}><section style={S.card}><div style={S.kicker}>MONDESCALE VOYAGES</div><h1 style={S.h1}>Votre préinscription est enregistrée</h1><p style={S.lead}>Merci. Nous vous contacterons lorsque la date réunissant le groupe aura été déterminée.</p><p style={S.note}>Cette préinscription est gratuite et sans engagement.</p></section></main>;
 return <main style={S.main}><section style={S.hero}><div style={S.kicker}>ÉGYPTE · CROISIÈRE SUR LE NIL</div><h1 style={S.h1}>Gloire des Pharaons <span style={{whiteSpace:"nowrap"}}>5★</span></h1><p style={S.lead}>8 jours / 7 nuits à bord du Caprice 5★ ou similaire · Formule tout inclus</p><div style={S.price}>1 070 € <small style={S.small}>/ personne</small></div><p style={S.note}>Paris ou Lyon · Départs en janvier et février 2027 · Visa et frais de services inclus</p></section>
 <form onSubmit={submit} style={S.card}><h2 style={S.h2}>Choisissez vos possibilités de départ</h2><p style={S.text}>Sélectionnez tous les aéroports et toutes les dates qui vous conviennent. Cela nous permettra de retenir la combinaison réunissant le plus de voyageurs.</p>
 <h3 style={S.h3}>1. Aéroport(s) possible(s)</h3><div style={S.grid}>{["PARIS","LYON"].map(x=><button type="button" key={x} onClick={()=>toggle(x,origins,setOrigins)} style={origins.includes(x)?S.selected:S.choice}>{x==="PARIS"?"Paris":"Lyon"}</button>)}</div>
 <h3 style={S.h3}>2. Toutes vos dates disponibles</h3><div style={S.dateGrid}>{dates.map(([v,l])=><button type="button" key={v} onClick={()=>toggle(v,deps,setDeps)} style={deps.includes(v)?S.selected:S.choice}>Samedi {l} 2027</button>)}</div>
 {deps.length>0&&<><h3 style={S.h3}>3. Votre date préférée</h3><select value={preferred} onChange={e=>setPreferred(e.target.value)} style={S.input}><option value="">Peu importe, je privilégie le groupe</option>{dates.filter(([v])=>deps.includes(v)).map(([v,l])=><option key={v} value={v}>{l} 2027</option>)}</select></>}
 <h3 style={S.h3}>4. Votre projet</h3><select value={intent} onChange={e=>setIntent(e.target.value)} style={S.input}><option value="HIGH">Si une de mes dates est retenue, j'envisage très probablement de réserver</option><option value="MEDIUM">Je suis intéressé(e), à confirmer</option><option value="INFO">Je souhaite surtout recevoir les informations</option></select>
 <div style={S.people}><label>Adultes<input type="number" min="1" max="20" value={f.adults} onChange={e=>setF({...f,adults:+e.target.value})} style={S.input}/></label><label>Enfants 2–11 ans<input type="number" min="0" max="20" value={f.children} onChange={e=>setF({...f,children:+e.target.value})} style={S.input}/></label><label>Bébés<input type="number" min="0" max="20" value={f.infants} onChange={e=>setF({...f,infants:+e.target.value})} style={S.input}/></label></div>
 <h3 style={S.h3}>5. Vos coordonnées</h3><input required placeholder="Nom et prénom" value={f.name} onChange={e=>setF({...f,name:e.target.value})} style={S.input}/><input required type="email" placeholder="E-mail" value={f.email} onChange={e=>setF({...f,email:e.target.value})} style={S.input}/><input placeholder="Téléphone (facultatif)" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})} style={S.input}/><input tabIndex="-1" autoComplete="off" value={f.website} onChange={e=>setF({...f,website:e.target.value})} style={{display:"none"}}/>
 <label style={S.check}><input required type="checkbox" checked={f.projectContactConsent} onChange={e=>setF({...f,projectContactConsent:e.target.checked})}/> J'accepte d'être contacté(e) par Mondescale Voyages au sujet de cette préinscription.</label>
 <label style={S.check}><input type="checkbox" checked={f.phoneMarketingConsent} onChange={e=>setF({...f,phoneMarketingConsent:e.target.checked})}/> J’accepte expressément que SAS DANUBE – Mondescale Voyages utilise mon numéro pour me proposer par téléphone des voyages et services, pendant 12 mois maximum. Je peux retirer mon consentement à tout moment, notamment par e-mail auprès de mon agence ou oralement lors d’un appel. La preuve de mon consentement est disponible gratuitement sur demande.</label>\n <label style={S.check}><input type="checkbox" checked={f.emailMarketingConsent} onChange={e=>setF({...f,emailMarketingConsent:e.target.checked})}/> J'accepte de recevoir par e-mail des idées et offres de Mondescale Voyages.</label>
 {state==="missing"&&<p style={S.error}>Sélectionnez au moins un aéroport et une date.</p>}{state==="error"&&<p style={S.error}>Une erreur est survenue. Merci de réessayer.</p>}
 <button disabled={state==="loading"} style={S.cta}>{state==="loading"?"Enregistrement…":"JE ME PRÉINSCRIS SANS ENGAGEMENT"}</button><p style={S.legal}>Préinscription gratuite et sans engagement. Elle ne constitue ni une réservation ni un contrat de voyage. Date et places sous réserve de confirmation. Tarif de 1 070 € par personne, sur la base de l'offre groupe présentée.</p></form></main>
}
const S={main:{minHeight:"100vh",background:"#f6f2ea",padding:"32px 16px",fontFamily:"Arial,sans-serif",color:"#17212b"},hero:{maxWidth:900,margin:"0 auto 22px",padding:"42px 34px",borderRadius:24,background:"linear-gradient(135deg,#fff 0%,#efe5d3 100%)",boxShadow:"0 12px 40px #00000012"},card:{maxWidth:900,margin:"0 auto",padding:"34px",borderRadius:24,background:"#fff",boxShadow:"0 12px 40px #00000012"},kicker:{fontSize:13,fontWeight:800,letterSpacing:2,color:"#9a6a22"},h1:{fontFamily:"Georgia,serif",fontSize:"clamp(38px,7vw,68px)",lineHeight:1,margin:"14px 0"},h2:{fontFamily:"Georgia,serif",fontSize:32,marginTop:0},h3:{margin:"30px 0 12px",fontSize:18},lead:{fontSize:20,lineHeight:1.5,maxWidth:700},price:{fontSize:46,fontWeight:800,marginTop:24,color:"#9a6a22"},small:{fontSize:18},note:{color:"#59636e",lineHeight:1.5},text:{lineHeight:1.6,color:"#46515d"},grid:{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10},dateGrid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10},choice:{padding:"16px",border:"1px solid #d8d2c7",borderRadius:12,background:"#fff",fontWeight:700,cursor:"pointer"},selected:{padding:"16px",border:"2px solid #9a6a22",borderRadius:12,background:"#fff8e9",fontWeight:800,cursor:"pointer"},input:{display:"block",width:"100%",boxSizing:"border-box",padding:"14px",margin:"9px 0",border:"1px solid #cfd4d8",borderRadius:10,fontSize:16},people:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:12,marginTop:18},check:{display:"block",margin:"16px 0",lineHeight:1.5},cta:{width:"100%",marginTop:18,padding:"18px",border:0,borderRadius:12,background:"#9a6a22",color:"#fff",fontSize:16,fontWeight:900,cursor:"pointer"},legal:{fontSize:12,lineHeight:1.5,color:"#6a737c",marginTop:18},error:{color:"#a32020",fontWeight:700}};
