"use client";

import {useEffect,useMemo,useState} from "react";

const API=process.env.NEXT_PUBLIC_API_URL||"";
const MIN_SAMPLE=20;
const AGENCIES={"ambassade-fram-mondescale-bois-colombes":"Bois-Colombes","ambassade-fram-mondescale-ozoir-la-ferriere":"Ozoir-la-Ferrière","ambassade-fram-mondescale-maurepas":"Maurepas","ambassade-fram-mondescale-gien":"Gien","ambassade-fram-mondescale-nevers":"Nevers","ambassade-fram-mondescale-dax":"Dax","mondescale-lamorlaye":"Lamorlaye","tui-store-amilly":"Amilly","tui-store-melun":"Melun"};
const CHANNELS={iga:"IGA / Email",facebook:"Facebook",instagram:"Instagram",google:"Google Business",agency:"QR agence",direct:"Direct"};
const LABELS={views:"Visite",starts:"Démarrage",q1:"Question 1",q2:"Question 2",q3:"Question 3",q4:"Question 4",q5:"Question 5",q6:"Question 6",formReached:"Formulaire",leadSubmits:"Lead"};
const priorityRank={HIGH:3,MEDIUM:2,LOW:1,NONE:0};
function recommendation(row,scope,key){const sample=Number(row?.views||0);if(sample<MIN_SAMPLE)return{scope,key,status:"INSUFFICIENT_DATA",priority:"NONE",sample,title:"Échantillon encore insuffisant",reason:`${sample} visite${sample>1?"s":""} observée${sample>1?"s":""}; ${MIN_SAMPLE} minimum avant recommandation.`,action:"Continuer la collecte sans modifier le funnel."};const d=row?.worstDropoff;if(!d)return{scope,key,status:"NO_SIGNAL",priority:"NONE",sample,title:"Aucun décrochage exploitable",reason:"Aucune perte mesurable entre les étapes observées.",action:"Conserver le funnel et poursuivre la collecte."};let title="Réduire le décrochage dans le questionnaire",action="Examiner le libellé, le nombre de choix et la friction de cette étape avant tout test A/B.";if(d.from==="views"&&d.to==="starts"){title="Renforcer l’entrée dans le quiz";action="Tester en priorité la promesse du hero et le CTA de démarrage, sans modifier le formulaire."}else if(d.from==="formReached"&&d.to==="leadSubmits"){title="Réduire la friction du formulaire final";action="Auditer les champs, la réassurance et la clarté du CTA final avant toute modification."}else if(d.to==="formReached"){title="Fluidifier le passage vers le formulaire";action="Renforcer la transition entre le résultat du quiz et la demande de coordonnées."}const priority=d.lossRate>=50?"HIGH":d.lossRate>=30?"MEDIUM":"LOW";return{scope,key,status:"ACTIONABLE",priority,sample,title,reason:`Décrochage ${LABELS[d.from]||d.from} → ${LABELS[d.to]||d.to} : ${d.lostSessions} session${d.lostSessions>1?"s":""} perdue${d.lostSessions>1?"s":""} (${d.lossRate} %).`,action}}
function Badge({priority}){const text={HIGH:"Priorité haute",MEDIUM:"Priorité moyenne",LOW:"À surveiller",NONE:"Observation"}[priority];return <span className="inline-flex rounded-full border border-slate-200 px-2.5 py-1 text-xs font-semibold text-slate-600">{text}</span>}
function Item({r,label}){return <div className="rounded-xl border border-slate-100 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-xs uppercase tracking-wide text-slate-400">{label}</div><div className="font-semibold text-[#073653] mt-1">{r.title}</div></div><Badge priority={r.priority}/></div><p className="text-sm text-slate-600 mt-2">{r.reason}</p><p className="text-sm text-slate-500 mt-1"><strong>Action proposée :</strong> {r.action}</p></div>}
export default function OptimizationRecommendations({days,site}){const[data,setData]=useState(null),[error,setError]=useState("");useEffect(()=>{let alive=true;const q=new URLSearchParams({days:String(days)});if(site)q.set("siteSlug",site);fetch(`${API}/api/leads/acquisition/funnel-intelligence?${q}`).then(async r=>{const b=await r.json();if(!r.ok||!b.ok)throw new Error(b.error||`HTTP ${r.status}`);if(alive){setError("");setData(b)}}).catch(e=>alive&&setError(e.message));return()=>{alive=false}},[days,site]);const recommendations=useMemo(()=>{if(!data)return null;const network=recommendation(data.network,"network","network");const agencies=(data.agencies||[]).map(r=>recommendation(r,"agency",r.siteSlug)).sort((a,b)=>priorityRank[b.priority]-priorityRank[a.priority]);const channels=(data.channels||[]).map(r=>recommendation(r,"channel",r.source)).sort((a,b)=>priorityRank[b.priority]-priorityRank[a.priority]);return{network,agencies,channels}},[data]);if(error)return <div className="bg-red-50 text-red-700 rounded-xl p-4">Erreur recommandations : {error}</div>;if(!recommendations)return <div className="bg-white rounded-2xl p-5 text-slate-500">Analyse des recommandations…</div>;const actionable=[recommendations.network,...recommendations.agencies,...recommendations.channels].filter(r=>r.status==="ACTIONABLE");return <section className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-bold text-xl text-[#073653]">Recommandations d’optimisation</h2><p className="text-sm text-slate-500 mt-1">Lecture automatique et explicable des décrochages. Aucune modification du funnel n’est appliquée automatiquement.</p></div><div className="text-xs text-slate-400">Garde-fou : {MIN_SAMPLE} visites minimum par segment</div></div><div className="bg-white rounded-2xl shadow-sm p-5"><Item r={recommendations.network} label={site?`Agence ${AGENCIES[site]||site}`:"Réseau"}/></div>{actionable.length>0&&<div className="grid lg:grid-cols-2 gap-6"><div className="bg-white rounded-2xl shadow-sm p-5 space-y-3"><h3 className="font-bold text-[#073653]">Signaux par agence</h3>{recommendations.agencies.filter(r=>r.status==="ACTIONABLE").slice(0,5).map(r=><Item key={r.key} r={r} label={AGENCIES[r.key]||r.key}/>) }{!recommendations.agencies.some(r=>r.status==="ACTIONABLE")&&<p className="text-sm text-slate-500">Pas encore de signal agence suffisamment robuste.</p>}</div><div className="bg-white rounded-2xl shadow-sm p-5 space-y-3"><h3 className="font-bold text-[#073653]">Signaux par canal</h3>{recommendations.channels.filter(r=>r.status==="ACTIONABLE").slice(0,5).map(r=><Item key={r.key} r={r} label={CHANNELS[r.key]||r.key}/>) }{!recommendations.channels.some(r=>r.status==="ACTIONABLE")&&<p className="text-sm text-slate-500">Pas encore de signal canal suffisamment robuste.</p>}</div></div>}</section>}
