"use strict";

const express=require("express");
const { randomUUID }=require("node:crypto");
const { NETWORK_AGENCIES }=require("../acquisition-funnel");
const ALLOWED_EVENTS=new Set(["VIEW","START","QUESTION_ANSWER","FORM_REACHED","LEAD_SUBMIT"]);
function clean(v,max=240){return String(v??"").trim().replace(/\s+/g," ").slice(0,max)}
function clampDays(v){return Math.min(Math.max(Number(v||30),1),365)}
function normalizeSiteSlug(value){const raw=clean(value,160);const agency=NETWORK_AGENCIES.find((item)=>item.publicSiteSlug===raw||item.siteSlug===raw);return agency?.siteSlug||raw}
function normalizeEvent(body={}){const event=clean(body.event,40).toUpperCase();if(!ALLOWED_EVENTS.has(event))return{error:"INVALID_EVENT"};const siteSlug=normalizeSiteSlug(body.siteSlug),campaign=clean(body.campaign,160),funnelId=clean(body.funnelId,180),sessionId=clean(body.sessionId,180);if(!siteSlug||!campaign||!funnelId||!sessionId)return{error:"MISSING_IDENTITY"};const questionNumber=body.questionNumber==null?0:Number(body.questionNumber);if(event==="QUESTION_ANSWER"&&(!Number.isInteger(questionNumber)||questionNumber<1||questionNumber>6))return{error:"INVALID_QUESTION_NUMBER"};if(event!=="QUESTION_ANSWER"&&questionNumber!==0)return{error:"UNEXPECTED_QUESTION_NUMBER"};return{event,siteSlug,campaign,funnelId,sessionId,questionNumber,question:clean(body.question,120)||null,utmSource:clean(body.utmSource,240)||null,utmMedium:clean(body.utmMedium,240)||null,utmCampaign:clean(body.utmCampaign,240)||null,utmContent:clean(body.utmContent,240)||null,referrer:clean(body.referrer,1000)||null,path:clean(body.path,1000)||null}}
function routes({prisma}={}){const router=express.Router();router.post("/api/public/acquisition-telemetry",async(req,res)=>{if(!prisma)return res.status(503).json({ok:false,error:"PERSISTENCE_UNAVAILABLE"});const evt=normalizeEvent(req.body||{});if(evt.error)return res.status(400).json({ok:false,error:evt.error});try{await prisma.$executeRawUnsafe(`INSERT INTO "AcquisitionFunnelEvent" ("id","event","siteSlug","campaign","funnelId","sessionId","questionNumber","question","utmSource","utmMedium","utmCampaign","utmContent","referrer","path","createdAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,NOW()) ON CONFLICT ("sessionId","event","questionNumber") DO NOTHING`,`evt_${randomUUID().replaceAll("-","")}`,evt.event,evt.siteSlug,evt.campaign,evt.funnelId,evt.sessionId,evt.questionNumber,evt.question,evt.utmSource,evt.utmMedium,evt.utmCampaign,evt.utmContent,evt.referrer,evt.path);return res.status(202).json({ok:true})}catch(e){console.error("[acquisition-telemetry] event failed",e);return res.status(500).json({ok:false,error:"TELEMETRY_WRITE_FAILED"})}});router.get("/api/leads/acquisition/funnel-analytics",async(req,res)=>{if(!prisma)return res.status(503).json({ok:false,error:"PERSISTENCE_UNAVAILABLE"});try{const days=clampDays(req.query.days),siteSlug=req.query.siteSlug?normalizeSiteSlug(req.query.siteSlug):null;const rows=await prisma.$queryRawUnsafe(`SELECT "siteSlug", COUNT(DISTINCT "sessionId") FILTER (WHERE "event"='VIEW')::int AS "views", COUNT(DISTINCT "sessionId") FILTER (WHERE "event"='START')::int AS "starts", COUNT(DISTINCT "sessionId") FILTER (WHERE "event"='FORM_REACHED')::int AS "formReached", COUNT(DISTINCT "sessionId") FILTER (WHERE "event"='LEAD_SUBMIT')::int AS "leadSubmits", COUNT(DISTINCT "sessionId") FILTER (WHERE "event"='QUESTION_ANSWER' AND "questionNumber"=1)::int AS "q1", COUNT(DISTINCT "sessionId") FILTER (WHERE "event"='QUESTION_ANSWER' AND "questionNumber"=2)::int AS "q2", COUNT(DISTINCT "sessionId") FILTER (WHERE "event"='QUESTION_ANSWER' AND "questionNumber"=3)::int AS "q3", COUNT(DISTINCT "sessionId") FILTER (WHERE "event"='QUESTION_ANSWER' AND "questionNumber"=4)::int AS "q4", COUNT(DISTINCT "sessionId") FILTER (WHERE "event"='QUESTION_ANSWER' AND "questionNumber"=5)::int AS "q5", COUNT(DISTINCT "sessionId") FILTER (WHERE "event"='QUESTION_ANSWER' AND "questionNumber"=6)::int AS "q6" FROM "AcquisitionFunnelEvent" WHERE "createdAt">=NOW()-($1*INTERVAL '1 day') AND ($2::text IS NULL OR "siteSlug"=$2) GROUP BY "siteSlug" ORDER BY COUNT(DISTINCT "sessionId") FILTER (WHERE "event"='VIEW') DESC`,days,siteSlug);return res.json({ok:true,days,siteSlug,agencies:rows})}catch(e){console.error("[acquisition-telemetry] analytics failed",e);return res.status(500).json({ok:false,error:"TELEMETRY_ANALYTICS_FAILED"})}});return router}
module.exports={ALLOWED_EVENTS,normalizeEvent,normalizeSiteSlug,routes};
